// Task Details Database - Complete 90 days curriculum
// Months 1-3: Foundation (Mes 1), Acceleration (Mes 2), Mastery (Mes 3)

export interface TaskStep {
  stepNumber: number
  title: string
  description: string
  duration: string
  tips?: string[]
  example?: string
}

export interface TaskResource {
  title: string
  type: 'template' | 'article' | 'course' | 'tool' | 'video' | 'framework'
  url: string
  description?: string
  duration?: string
}

export interface TaskDetail {
  day: number
  title: string
  fullDescription: string
  objective: string
  steps: TaskStep[]
  resources: TaskResource[]
  successCriteria: string[]
  expectedOutput?: string
}

const TASK_DETAILS: Record<number, TaskDetail> = {
  // MONTH 1: FOUNDATION (Días 1-30)
  1: { day: 1, title: 'Define tu visión y roadmap', fullDescription: 'Crea un documento estructurado con tu objetivo profesional, los hitos clave y timeline realista.', objective: 'Claridad total sobre qué quieres lograr', steps: [{ stepNumber: 1, title: 'Escribe tu visión', description: 'Define rol, empresa, salario, ubicación en 3 años', duration: '10 min' }, { stepNumber: 2, title: 'Define 3 hitos (30/60/90 días)', description: 'Qué necesitas lograr en cada milestone', duration: '15 min' }, { stepNumber: 3, title: 'Crea plan de acciones', description: 'Desglosaa en acciones semanales', duration: '20 min' }], resources: [{ title: 'Plantilla de Objetivos', type: 'template', url: 'https://www.notion.so/templates/goal-setting', description: 'Plantilla lista para usar' }], successCriteria: ['✓ Visión escrita', '✓ 3 hitos definidos', '✓ Plan en Notion'] },
  2: { day: 2, title: 'Optimiza tu CV y LinkedIn', fullDescription: 'Actualiza ambos documentos con palabras clave del rol objetivo y logros cuantitativos.', objective: 'CV y LinkedIn listos para la búsqueda', steps: [{ stepNumber: 1, title: 'Actualiza CV con palabras clave', description: 'Incorpora palabras clave del rol, logros cuantitativos, skills relevantes', duration: '45 min' }, { stepNumber: 2, title: 'Optimiza LinkedIn', description: 'Foto profesional, headline claro, descripción compelling, skills destacados', duration: '30 min' }, { stepNumber: 3, title: 'Pide retroalimentación', description: 'Comparte con 2-3 personas para opiniones', duration: '15 min' }], resources: [{ title: 'Plantilla de CV', type: 'template', url: 'https://www.canva.com/search/cv/', description: 'Plantillas profesionales' }], successCriteria: ['✓ CV actualizado', '✓ LinkedIn optimizado', '✓ Retroalimentación recibida'] },
  3: { day: 3, title: 'Investiga el mercado y rol objetivo', fullDescription: 'Analiza salarios, skills requeridas, empresas relevantes y ofertas del rol que buscas.', objective: 'Data clara para posicionarte correctamente', steps: [{ stepNumber: 1, title: 'Analiza 5-10 descripciones de roles', description: 'Extrae skills comunes, requisitos, nivel de experiencia', duration: '30 min' }, { stepNumber: 2, title: 'Investiga salarios', description: 'Usa Glassdoor, Levels.fyi, Payscale para rango salarial', duration: '20 min' }, { stepNumber: 3, title: 'Crea lista de 20+ empresas objetivo', description: 'Empresas donde quieres trabajar', duration: '25 min' }], resources: [{ title: 'Glassdoor', type: 'tool', url: 'https://www.glassdoor.com' }], successCriteria: ['✓ Descripciones analizadas', '✓ Salarios investigados', '✓ Empresas listadas'] },
  4: { day: 4, title: 'Auditoría de tus skills actuales', fullDescription: 'Evaluación honesta de qué sabes, qué te falta y en qué eres especialista.', objective: 'Claridad sobre gaps para cerrarlo en 90 días', steps: [{ stepNumber: 1, title: 'Lista tus skills actuales', description: 'Categoriza por expertise (expert, intermediate, beginner)', duration: '30 min' }, { stepNumber: 2, title: 'Compara con job descriptions', description: 'Qué skills requiere el rol vs lo que tienes', duration: '20 min' }, { stepNumber: 3, title: 'Prioriza gaps críticos', description: 'Top 3 skills que DEBES aprender', duration: '15 min' }], resources: [], successCriteria: ['✓ Skills listados y categorizados', '✓ Gaps identificados', '✓ Top 3 prioridades definidas'] },
  5: { day: 5, title: 'Busca e inicia curso/recurso principal', fullDescription: 'Elige y comienza el principal recurso de aprendizaje para cerrar tus gaps de skills.', objective: 'Iniciar aprendizaje formal del skill crítico', steps: [{ stepNumber: 1, title: 'Busca 3-5 cursos relevantes', description: 'Udemy, Coursera, LinkedIn Learning, etc', duration: '20 min' }, { stepNumber: 2, title: 'Elige uno y regístrate', description: 'El que mejor se alinee con tus gaps', duration: '10 min' }, { stepNumber: 3, title: 'Completa Lección 1', description: 'Ve el primer módulo/capítulo', duration: '30 min' }], resources: [{ title: 'Udemy', type: 'tool', url: 'https://www.udemy.com' }, { title: 'Coursera', type: 'tool', url: 'https://www.coursera.org' }], successCriteria: ['✓ Curso elegido', '✓ Registrado', '✓ Lección 1 completada'] },
  6: { day: 6, title: 'Crea tu perfil de marca personal', fullDescription: 'Desarrolla presencia online consistente que demuestre tu expertise.', objective: 'Ser visible en tu industria', steps: [{ stepNumber: 1, title: 'Optimiza LinkedIn headline y resumen', description: '100-120 caracteres enfocados en valor', duration: '20 min' }, { stepNumber: 2, title: 'Crea o actualiza portafolio/GitHub', description: 'Muestra mejor trabajo/proyectos', duration: '60 min' }, { stepNumber: 3, title: 'Comparte primer contenido', description: 'Post o artículo sobre lo que estás aprendiendo', duration: '30 min' }], resources: [], successCriteria: ['✓ LinkedIn optimizado', '✓ Portafolio actualizado', '✓ Contenido compartido'] },
  7: { day: 7, title: 'Inicio de acción: 1ª semana', fullDescription: 'Pon en movimiento las acciones de búsqueda. Primer contacto con mercado.', objective: 'Poner en movimiento tu búsqueda', steps: [{ stepNumber: 1, title: 'Aplica a 3 posiciones', description: 'De tu lista de empresas objetivo', duration: '30 min' }, { stepNumber: 2, title: 'Contacta 5 personas en LinkedIn', description: 'Personalizado, sin copy-paste', duration: '25 min' }, { stepNumber: 3, title: 'Documenta acciones', description: 'Crea tracker en Google Sheets o Notion', duration: '10 min' }], resources: [], successCriteria: ['✓ 3 aplicaciones enviadas', '✓ 5 conexiones iniciadas', '✓ Tracker creado'] },
  8: { day: 8, title: 'Revisión Semana 1: Checkpoint', fullDescription: 'Pausa para evaluar qué funcionó y ajustar si es necesario.', objective: 'Asegurar que vas por buen camino', steps: [{ stepNumber: 1, title: 'Revisa aplicaciones y respuestas', description: 'Quién respondió? De quién tuviste feedback?', duration: '15 min' }, { stepNumber: 2, title: 'Mide KPIs de semana 1', description: 'Aplicaciones, conexiones, entrevistas', duration: '15 min' }, { stepNumber: 3, title: 'Ajusta estrategia si es necesario', description: 'Doble volumen? Cambio de enfoque?', duration: '20 min' }], resources: [], successCriteria: ['✓ Semana revisada', '✓ KPIs medidos', '✓ Ajustes documentados'] },
  9: { day: 9, title: 'Análisis profundo: Mercado y salarios', fullDescription: 'Investigación exhaustiva de tendencias, salarios y habilidades emergentes en tu industria.', objective: 'Entender completamente el mercado y oportunidades', steps: [{ stepNumber: 1, title: 'Análisis de salarios por nivel', description: 'Junior vs Intermedio vs Senior en tu industria/región', duration: '30 min' }, { stepNumber: 2, title: 'Identifica tendencias de mercado', description: 'Skills emergentes, industrias en crecimiento', duration: '25 min' }, { stepNumber: 3, title: 'Crea documento de insights', description: 'Análisis en Notion o Google Doc', duration: '20 min' }], resources: [{ title: 'Levels.fyi', type: 'tool', url: 'https://www.levels.fyi' }, { title: 'Payscale', type: 'tool', url: 'https://www.payscale.com' }], successCriteria: ['✓ Salarios investigados', '✓ Tendencias identificadas', '✓ Insights documentados'] },
  10: { day: 10, title: 'Avanza en Curso: Semana 2', fullDescription: 'Continúa aprendiendo. Completa semana 2 del curso/recurso principal.', objective: 'Mantener momentum de aprendizaje', steps: [{ stepNumber: 1, title: 'Dedica 5+ horas al curso', description: 'Completa lecciones y módulos', duration: '300 min' }, { stepNumber: 2, title: 'Haz ejercicios prácticos', description: 'Implementa lo que aprendes', duration: '45 min' }, { stepNumber: 3, title: 'Documenta conceptos clave', description: 'Lo que más te resonó esta semana', duration: '15 min' }], resources: [], successCriteria: ['✓ 5+ horas dedicadas', '✓ Ejercicios completados', '✓ Conceptos documentados'] },
  11: { day: 11, title: 'Expande tu red: Networking activo', fullDescription: 'Conecta intencionalmente con profesionales en tu industria.', objective: 'Construir relaciones que te abran puertas', steps: [{ stepNumber: 1, title: 'Identifica 5 personas para contactar', description: 'De empresas objetivo o en rol que busca', duration: '20 min' }, { stepNumber: 2, title: 'Envía invitaciones personalizadas', description: 'Menciona algo específico de ellos', duration: '25 min' }, { stepNumber: 3, title: 'Sigue con contactos de hace días', description: 'Dale follow-up a quién respondió', duration: '15 min' }], resources: [], successCriteria: ['✓ 5 personas contactadas', '✓ Personalizadas y con valor', '✓ Follow-ups enviados'] },
  12: { day: 12, title: 'Análisis de Competencia: Diferenciación', fullDescription: 'Estudia a competidores en tu campo. Cómo diferenciarte?', objective: 'Encontrar tu unique selling proposition', steps: [{ stepNumber: 1, title: 'Estudia 5 competidores directos', description: 'Personas buscando el mismo rol', duration: '40 min' }, { stepNumber: 2, title: 'Identifica su positioning', description: 'Cómo se venden? Qué es su diferencial?', duration: '20 min' }, { stepNumber: 3, title: 'Define tu diferenciador', description: 'Qué te hace único?', duration: '20 min' }], resources: [], successCriteria: ['✓ Competidores estudiados', '✓ Su positioning analizado', '✓ Tu diferenciador claro'] },
  13: { day: 13, title: 'Follow-up y Relaciones: Construcción', fullDescription: 'Profundiza las primeras conexiones que hiciste.', objective: 'Convertir contactos en relaciones', steps: [{ stepNumber: 1, title: 'Revisa quién respondió', description: 'De tus 5-10 contactos iniciales', duration: '10 min' }, { stepNumber: 2, title: 'Envía follow-ups personalizados', description: 'Agrega valor real, no solo hablar de ti', duration: '30 min' }, { stepNumber: 3, title: 'Agenda 2-3 llamadas cortas', description: 'Con gente que mostró interés', duration: '20 min' }], resources: [], successCriteria: ['✓ Respuestas identificadas', '✓ Follow-ups enviados', '✓ Llamadas agendadas'] },
  14: { day: 14, title: 'Revisión Semana 2: Checkpoint', fullDescription: 'Evalúa progreso en la segunda semana.', objective: 'Estar seguro que vas adelante', steps: [{ stepNumber: 1, title: 'Mide KPIs de Semana 2', description: 'Entrevistas, contactos, aprendizaje', duration: '15 min' }, { stepNumber: 2, title: 'Compara vs Semana 1', description: 'Qué mejoró? Qué empeoró?', duration: '15 min' }, { stepNumber: 3, title: 'Acelera estrategia ganadora', description: 'Dobla lo que está funcionando', duration: '20 min' }], resources: [], successCriteria: ['✓ Semana 2 medida', '✓ Comparativa realizada', '✓ Aceleraciones planificadas'] },
  15: { day: 15, title: 'Entrevistas de práctica y preparación', fullDescription: 'Realiza 2-3 entrevistas de práctica para ganar confianza y eliminar nerviosismo.', objective: 'Estar listo para entrevistas reales', steps: [{ stepNumber: 1, title: 'Prepara 3 historias STAR', description: 'Situación, Tarea, Acción, Resultado', duration: '30 min' }, { stepNumber: 2, title: 'Agenda 2-3 entrevistas de práctica', description: 'Con mentores o amigos en la industria', duration: '15 min' }, { stepNumber: 3, title: 'Realiza las entrevistas', description: 'Vístete profesional, toma notas de retroalimentación', duration: '90 min' }], resources: [{ title: 'Guía del Método STAR', type: 'article', url: 'https://www.indeed.com/career-advice/interviewing/how-to-answer-behavioral-interview-questions' }], successCriteria: ['✓ Historias STAR preparadas', '✓ Entrevistas de práctica completadas', '✓ Retroalimentación documentada'] },
  16: { day: 16, title: 'Proyecto/Contribución: Construye y Lanza', fullDescription: 'Crea un pequeño proyecto o contribuye a código abierto que demuestre tus skills.', objective: 'Evidencia visible y tangible de tus habilidades', steps: [{ stepNumber: 1, title: 'Elige proyecto o repositorio', description: 'Alineado con rol objetivo', duration: '30 min' }, { stepNumber: 2, title: 'Planifica MVP', description: 'Qué puedes hacer en 3-4 horas', duration: '30 min' }, { stepNumber: 3, title: 'Ejecuta y publica', description: 'GitHub, comparte en LinkedIn', duration: '240 min' }], resources: [{ title: 'GitHub Explore', type: 'tool', url: 'https://github.com/explore' }], successCriteria: ['✓ Código publicado', '✓ README documentado', '✓ Compartido en LinkedIn'] },
  17: { day: 17, title: 'Liderazgo Real: Toma Iniciativa', fullDescription: 'Asume rol de liderazgo en proyecto o en tu comunidad.', objective: 'Demostrar capacidades de liderazgo', steps: [{ stepNumber: 1, title: 'Identifica oportunidad de liderazgo', description: 'Proyecto, grupo, mentoring', duration: '15 min' }, { stepNumber: 2, title: 'Propón idea o estructura', description: 'Toma la iniciativa', duration: '30 min' }, { stepNumber: 3, title: 'Ejecuta y documenta', description: 'Haz visible tu liderazgo', duration: '90 min' }], resources: [], successCriteria: ['✓ Oportunidad identificada', '✓ Idea propuesta', '✓ Ejecutada y documentada'] },
  18: { day: 18, title: 'Contenido: Comparte tu Expertise', fullDescription: 'Escribe un artículo o post sobre lo que aprendiste. Demuestra pensamiento e insights.', objective: 'Construir autoridad y visibilidad en tu industria', steps: [{ stepNumber: 1, title: 'Elige tema de expertise', description: 'Algo que aprendiste recientemente', duration: '15 min' }, { stepNumber: 2, title: 'Escribe artículo/post', description: 'LinkedIn (500-1000 palabras) o Medium', duration: '90 min' }, { stepNumber: 3, title: 'Publica y promociona', description: 'Comparte con tu red', duration: '30 min' }], resources: [], successCriteria: ['✓ Contenido escrito', '✓ Publicado', '✓ Compartido con red'] },
  19: { day: 19, title: 'Práctica intensiva: Algoritmos/Casos', fullDescription: 'Si aplica para tu rol: práctica intensiva de problemas técnicos o casos de negocio.', objective: 'Estar preparado para roundas técnicas', steps: [{ stepNumber: 1, title: 'Dedica 4+ horas a práctica', description: 'LeetCode, hackerrank, o case studies', duration: '240 min' }, { stepNumber: 2, title: 'Resuelve 5-10 problemas', description: 'Rondas técnicas simuladas', duration: '60 min' }, { stepNumber: 3, title: 'Documenta patrones aprendidos', description: 'Qué estrategias funcionan mejor', duration: '20 min' }], resources: [{ title: 'LeetCode', type: 'tool', url: 'https://www.leetcode.com' }], successCriteria: ['✓ 4+ horas dedicadas', '✓ 5-10 problemas resueltos', '✓ Patrones documentados'] },
  20: { day: 20, title: 'Revisión del Punto Medio: Día 20', fullDescription: 'Revisión de punto medio. Evalúa si estás en track para cumplir objetivos del Día 30.', objective: 'Asegurar alineación y ajustar si es necesario', steps: [{ stepNumber: 1, title: 'Revisa visión del Día 1', description: 'Comparar con progreso actual', duration: '15 min' }, { stepNumber: 2, title: 'Mide KPIs principales', description: 'Entrevistas, ofertas, skills, relaciones construidas', duration: '20 min' }, { stepNumber: 3, title: 'Acelera o ajusta', description: 'Qué cambiar para los últimos 10 días', duration: '25 min' }], resources: [], successCriteria: ['✓ KPIs medidos', '✓ Comparativa realizada', '✓ Plan para últimos 10 días'] },
  21: { day: 21, title: 'Networking: Entrevistas Informativas', fullDescription: 'Realiza 2-3 conversaciones con profesionales en tu campo. Aprende, expande red, encuentra mentores.', objective: 'Obtener insights y expandir red de conexiones valiosas', steps: [{ stepNumber: 1, title: 'Identifica 3 personas para entrevistar', description: 'Profesionales en rol/empresa objetivo', duration: '20 min' }, { stepNumber: 2, title: 'Envía invitaciones personalizadas', description: 'Explica por qué quieres hablar con ellos', duration: '15 min' }, { stepNumber: 3, title: 'Realiza 3 llamadas de 30 min', description: 'Escucha, aprende, toma notas', duration: '90 min' }], resources: [], successCriteria: ['✓ 3 personas contactadas', '✓ 2-3 llamadas completadas', '✓ Insights documentados'] },
  22: { day: 22, title: 'Semana 3: Intensificar lo ganador', fullDescription: 'Basado en qué funcionó, aumenta volumen y calidad de esas acciones ganadores.', objective: 'Maximizar retorno de las tácticas probadas', steps: [{ stepNumber: 1, title: 'Analiza Semanas 1-2', description: 'Qué acciones generaron entrevistas/ofertas', duration: '20 min' }, { stepNumber: 2, title: 'Duplica volumen de ganadores', description: '2-3x más de lo que funcionó', duration: '480 min' }, { stepNumber: 3, title: 'Documenta cambios y resultados', description: 'Qué impacto tuvo intensificar', duration: '15 min' }], resources: [], successCriteria: ['✓ Análisis completado', '✓ Volumen duplicado', '✓ Resultados documentados'] },
  23: { day: 23, title: 'Preparación: Entrevista Real Agendada', fullDescription: 'Prepárate intensivamente para la entrevista que ya tienes agendada.', objective: 'Maximizar oportunidades de entrevista real', steps: [{ stepNumber: 1, title: 'Investiga empresa profundamente', description: 'Productos, cultura, valores, noticias recientes', duration: '45 min' }, { stepNumber: 2, title: 'Prepara ejemplos STAR', description: 'Situaciones relevantes para la empresa', duration: '30 min' }, { stepNumber: 3, title: 'Practica y prepara preguntas', description: 'Entrevista de práctica, preguntas para ellos', duration: '45 min' }], resources: [], successCriteria: ['✓ Empresa investigada', '✓ Ejemplos STAR preparados', '✓ Preguntas listas'] },
  24: { day: 24, title: 'Ejecuta: Entrevista Real', fullDescription: 'Realiza la entrevista y haz seguimiento profesional en 24 horas.', objective: 'Convertir entrevista en siguiente ronda', steps: [{ stepNumber: 1, title: 'Realiza entrevista', description: 'Puntual, profesional, auténtico, energético', duration: '60 min' }, { stepNumber: 2, title: 'Envía nota de agradecimiento', description: 'Correo personalizado dentro de 24 horas', duration: '20 min' }, { stepNumber: 3, title: 'Documenta retroalimentación', description: 'Qué te preguntaron, cómo respondiste', duration: '15 min' }], resources: [], successCriteria: ['✓ Entrevista realizada', '✓ Nota de agradecimiento enviada', '✓ Retroalimentación documentada'] },
  25: { day: 25, title: 'Networking: Otra Entrevista Informativa', fullDescription: 'Realiza otra conversación con profesional diferente. Expande red continuamente.', objective: 'Mantener red activa y aprender de otros profesionales', steps: [{ stepNumber: 1, title: 'Identifica otra persona clave', description: 'Diferente industria, empresa o nivel', duration: '10 min' }, { stepNumber: 2, title: 'Envía invitación personalizada', description: 'Referencia común o valor que ofreces', duration: '10 min' }, { stepNumber: 3, title: 'Realiza llamada de 30 min', description: 'Escucha, aprende, crea relación', duration: '30 min' }], resources: [], successCriteria: ['✓ Persona contactada', '✓ Llamada realizada', '✓ Relación iniciada'] },
  26: { day: 26, title: 'Aprendizaje: Continúa con Curso', fullDescription: 'Sigue avanzando en tu educación formal. Completa otro módulo/semana del curso.', objective: 'Mantener momentum de aprendizaje hacia el Día 30', steps: [{ stepNumber: 1, title: 'Dedica 3+ horas al curso', description: 'Completar módulo o 3-4 lecciones', duration: '180 min' }, { stepNumber: 2, title: 'Realiza ejercicios prácticos', description: 'Implementa conceptos aprendidos', duration: '30 min' }, { stepNumber: 3, title: 'Reflexiona sobre progreso', description: 'Cómo esto te prepara para el rol objetivo', duration: '15 min' }], resources: [], successCriteria: ['✓ 3+ horas dedicadas', '✓ Módulo completado', '✓ Progreso reflexionado'] },
  27: { day: 27, title: 'Nuevas aplicaciones y outreach', fullDescription: 'Mantén pipeline activo. Aplica a nuevas posiciones y contacta recruiters.', objective: 'Asegurar múltiples oportunidades en movimiento', steps: [{ stepNumber: 1, title: 'Aplica a 3-5 posiciones nuevas', description: 'De tu lista de empresas objetivo', duration: '60 min' }, { stepNumber: 2, title: 'Contacta 5 recruiters', description: 'Especializados en tu industria/rol', duration: '30 min' }, { stepNumber: 3, title: 'Actualiza tracker', description: 'Documenta todas las acciones', duration: '10 min' }], resources: [], successCriteria: ['✓ 3-5 aplicaciones nuevas', '✓ 5 recruiters contactados', '✓ Tracker actualizado'] },
  28: { day: 28, title: 'Hito 30 días: Revisión Completa', fullDescription: 'Evaluación comprensiva del mes 1. Celebra logros, documenta lecciones, planifica meses 2-3.', objective: 'Consolidar aprendizajes y establecer visión clara para próximos 60 días', steps: [{ stepNumber: 1, title: 'Celebra tus logros', description: 'Documenta TODO lo que lograste en 30 días', duration: '30 min' }, { stepNumber: 2, title: 'Análisis cuantitativo', description: 'KPIs: entrevistas, ofertas, skills, conexiones', duration: '30 min' }, { stepNumber: 3, title: 'Planifica Meses 2-3', description: 'Objetivos, estrategias y tácticas para próximos 60 días', duration: '60 min' }], resources: [], successCriteria: ['✓ Logros celebrados', '✓ Métricas documentadas', '✓ Plan 60 días definido'] },
  29: { day: 29, title: 'Reflexión: Cambios en mentalidad y confianza', fullDescription: 'Reflexiona sobre cambios internos. Mentalidad, confianza, dirección de carrera más clara.', objective: 'Entender transformación personal y ajustar visión si es necesario', steps: [{ stepNumber: 1, title: 'Escribe reflexión personal', description: 'Cambios en cómo te ves profesionalmente', duration: '30 min' }, { stepNumber: 2, title: 'Analiza decisiones tomadas', description: 'Qué funcionó mejor de lo esperado?', duration: '20 min' }, { stepNumber: 3, title: 'Actualiza tu visión', description: 'Tu dirección sigue siendo la misma?', duration: '15 min' }], resources: [], successCriteria: ['✓ Reflexión documentada', '✓ Cambios identificados', '✓ Visión reconfirmada o actualizada'] },
  30: { day: 30, title: 'Mes 1 COMPLETADO: Evaluación Integral', fullDescription: 'Evaluación final comprensiva. Mide éxito, documenta lecciones clave, toma decisiones estratégicas.', objective: 'Tener claridad total sobre progreso y siguiente paso', steps: [{ stepNumber: 1, title: 'Revisión de Números (KPIs)', description: 'Entrevistas logradas, ofertas recibidas, skills adquiridos, conexiones construidas', duration: '30 min' }, { stepNumber: 2, title: 'Análisis Cualitativo', description: 'Mentalidad, confianza, si estás en el camino correcto', duration: '30 min' }, { stepNumber: 3, title: 'Decisiones Clave', description: '¿Continúo? ¿Qué cambio? ¿Próximos pasos inmediatos?', duration: '30 min' }], resources: [], successCriteria: ['✓ KPIs medidos', '✓ Análisis cualitativo completo', '✓ Decisiones registradas', '✓ Próximos 60 días planificados'] },

  // MONTH 2: ACCELERATION (Días 31-60)
  31: { day: 31, title: 'Mes 2 Comienza: Acelera Todo', fullDescription: 'Inicia mes 2 con velocidad. Duplica aplicaciones, intensifica networking, profundiza aprendizaje.', objective: 'Entrar en fase de aceleración', steps: [{ stepNumber: 1, title: 'Revisa lecciones del Mes 1', description: 'Qué funcionó? Dobla eso.', duration: '20 min' }, { stepNumber: 2, title: 'Establece metas agresivas Mes 2', description: 'Entrevistas, ofertas, skills', duration: '20 min' }, { stepNumber: 3, title: 'Inicia nuevo ciclo de acciones', description: 'Aplica 5-10x, contacta 10+ personas', duration: '30 min' }], resources: [{"title":"Udemy","type":"course","url":"https://www.udemy.com"},{"title":"Coursera","type":"course","url":"https://www.coursera.org"},{"title":"Platzi","type":"course","url":"https://www.platzi.com"}], successCriteria: ['✓ Lecciones analizadas', '✓ Metas definidas', '✓ Acciones iniciadas'] },
  32: { day: 32, title: 'Profundiza: Segunda ronda de entrevistas', fullDescription: 'Ya tienes feedback de mock interviews. Prepárate para segundas rondas de empresas.', objective: 'Avanzar en procesos de selección', steps: [{ stepNumber: 1, title: 'Identifica qué procesos están avanzados', description: 'Quién te pidió segunda ronda?', duration: '15 min' }, { stepNumber: 2, title: 'Prepara respuestas específicas por empresa', description: 'Historias adaptadas a cada una', duration: '60 min' }, { stepNumber: 3, title: 'Agenda y confirma entrevistas', description: 'Con HR o hiring manager', duration: '30 min' }], resources: [{"title":"LinkedIn Jobs","type":"tool","url":"https://www.linkedin.com/jobs"},{"title":"Glassdoor","type":"tool","url":"https://www.glassdoor.com"},{"title":"Indeed","type":"tool","url":"https://www.indeed.com"}], successCriteria: ['✓ Procesos identificados', '✓ Respuestas personalizadas', '✓ Entrevistas confirmadas'] },
  33: { day: 33, title: 'Aprendizaje: Certifikate o Capstone', fullDescription: 'Aproximadamente a mitad del curso. Completa proyecto importante o busca certificación.', objective: 'Avanzar significativamente en skill crítico', steps: [{ stepNumber: 1, title: 'Dedica 5+ horas al curso/proyecto', description: 'Push hacia proyecto final', duration: '300 min' }, { stepNumber: 2, title: 'Completa capstone project', description: 'Algo que puedas mostrar', duration: '120 min' }, { stepNumber: 3, title: 'Documenta y comparte progreso', description: 'LinkedIn, portafolio', duration: '30 min' }], resources: [], successCriteria: ['✓ 5+ horas dedicadas', '✓ Proyecto completado', '✓ Compartido'] },
  34: { day: 34, title: 'Content Marketing: Construye Autoridad', fullDescription: 'Publica serie de 2-3 posts sobre lo que aprendes. Construye marca personal.', objective: 'Ser referencia en tu campo', steps: [{ stepNumber: 1, title: 'Diseña serie de contenido', description: '3 temas clave para publicar', duration: '30 min' }, { stepNumber: 2, title: 'Escribe y publica primer post', description: '1000+ palabras, bien estructurado', duration: '120 min' }, { stepNumber: 3, title: 'Promociona en redes', description: 'LinkedIn, Twitter, comunidades', duration: '30 min' }], resources: [], successCriteria: ['✓ Serie planificada', '✓ Primer post publicado', '✓ Promocionado'] },
  35: { day: 35, title: 'Networking: Programa de Mentoring', fullDescription: 'Formaliza relaciones. Busca 1-2 mentores que te guíen.', objective: 'Tener guía experta durante búsqueda', steps: [{ stepNumber: 1, title: 'Identifica potenciales mentores', description: '5-10 personas ideales', duration: '20 min' }, { stepNumber: 2, title: 'Propón relación formal', description: 'Cafés mensuales, feedback estructurado', duration: '30 min' }, { stepNumber: 3, title: 'Asegura 1-2 compromisos', description: 'Mentores que digan sí', duration: '20 min' }], resources: [{"title":"GitHub","type":"tool","url":"https://github.com"},{"title":"Dev.to","type":"article","url":"https://dev.to"},{"title":"Medium","type":"article","url":"https://medium.com"}], successCriteria: ['✓ Potenciales identificados', '✓ Relaciones propuestas', '✓ 1-2 mentores confirmados'] },
  36: { day: 36, title: 'Segunda semana: Amplía applicaciones', fullDescription: 'Duplica volumen de aplicaciones. Expande a nuevas empresas y roles.', objective: 'Máximo volumen en pipeline', steps: [{ stepNumber: 1, title: 'Aplica a 10+ nuevas posiciones', description: 'De lista extendida de empresas', duration: '90 min' }, { stepNumber: 2, title: 'Contacta 15+ nuevas personas', description: 'LinkedIn direct, email, referrals', duration: '60 min' }, { stepNumber: 3, title: 'Registra todas las acciones', description: 'Tracker actualizado', duration: '15 min' }], resources: [], successCriteria: ['✓ 10+ aplicaciones', '✓ 15+ nuevos contactos', '✓ Tracker actualizado'] },
  37: { day: 37, title: 'Refinamiento: Portafolio y Projects', fullDescription: 'Mejora tu portafolio. Agrega últimos proyectos y refina presentación.', objective: 'Portafolio que demuestre expertise', steps: [{ stepNumber: 1, title: 'Revisa portafolio actual', description: 'Qué está desactualizado?', duration: '20 min' }, { stepNumber: 2, title: 'Agrega 2-3 nuevos proyectos', description: 'Lo mejor de últimas semanas', duration: '120 min' }, { stepNumber: 3, title: 'Refina diseño y presentación', description: 'Haz que sea memorable', duration: '60 min' }], resources: [], successCriteria: ['✓ Portafolio revisado', '✓ Nuevos proyectos agregados', '✓ Diseño mejorado'] },
  38: { day: 38, title: 'Checkpoint Mes 2: Semana 5', fullDescription: 'Evalúa progreso a mitad de Mes 2.', objective: 'Asegurar que vas adelante de plan', steps: [{ stepNumber: 1, title: 'Revisa KPIs de últimas 2 semanas', description: 'Entrevistas, ofertas, feedback', duration: '20 min' }, { stepNumber: 2, title: 'Compara vs hitos planificados', description: 'En track? Adelante? Atrás?', duration: '15 min' }, { stepNumber: 3, title: 'Ajusta estrategia si es necesario', description: 'Qué intensificar? Qué soltar?', duration: '25 min' }], resources: [], successCriteria: ['✓ KPIs medidos', '✓ Comparativa realizada', '✓ Ajustes identificados'] },
  39: { day: 39, title: 'Advanced: Prep para Rondas Finales', fullDescription: 'Algunos procesos están en rondas finales. Preparación intensiva.', objective: 'Cerrar ofertas en empresas top', steps: [{ stepNumber: 1, title: 'Identifica procesos en ronda final', description: 'Quién te pidió executive round?', duration: '15 min' }, { stepNumber: 2, title: 'Investigación profunda de empresa', description: 'CEO, strategy, culture, financials', duration: '60 min' }, { stepNumber: 3, title: 'Prepara preguntas estratégicas', description: 'Sobre futuro, visión, rol', duration: '45 min' }], resources: [], successCriteria: ['✓ Procesos finales identificados', '✓ Empresa investigada profundamente', '✓ Preguntas estratégicas preparadas'] },
  40: { day: 40, title: 'Dominio: Tercera ronda de proyecto', fullDescription: 'Si aplica: proyecto técnico o case avanzado de ronda final.', objective: 'Demostrar nivel senior de pensamiento', steps: [{ stepNumber: 1, title: 'Entiende expectativas de proyecto', description: 'Scope, timeline, evalúa criterios', duration: '30 min' }, { stepNumber: 2, title: 'Ejecuta proyecto', description: 'Código limpio, documentación buena', duration: '300 min' }, { stepNumber: 3, title: 'Prepara presentación', description: 'Cómo lo hiciste y por qué', duration: '60 min' }], resources: [], successCriteria: ['✓ Proyecto entendido', '✓ Completado a nivel senior', '✓ Presentación preparada'] },
  41: { day: 41, title: 'Networking: Conexión con decision makers', fullDescription: 'Conecta directamente con hiring managers y leadership.', objective: 'Influir en decisiones de contratación', steps: [{ stepNumber: 1, title: 'Identifica decision makers en empresas', description: 'Engineering leads, VPs, CTOs', duration: '30 min' }, { stepNumber: 2, title: 'Crea pitch personalizado', description: 'Por qué eres match perfecto', duration: '30 min' }, { stepNumber: 3, title: 'Contacta directamente', description: 'Email, LinkedIn, referral', duration: '30 min' }], resources: [], successCriteria: ['✓ Decision makers identificados', '✓ Pitch personalizado', '✓ Contacto establecido'] },
  42: { day: 42, title: 'Tercera semana: Consolidación', fullDescription: 'Consolida los mejores procesos. Sigue aplicando pero enfócate en los que avanzan.', objective: 'Convertir pipeline en ofertas', steps: [{ stepNumber: 1, title: 'Prioriza top 5 procesos', description: 'Donde tienes mejor oportunidad', duration: '20 min' }, { stepNumber: 2, title: 'Intensifica prep para esos 5', description: 'Investigación, referencias, historias', duration: '120 min' }, { stepNumber: 3, title: 'Sigue aplicando: 5 nuevas aplicaciones', description: 'Mantén pipeline vivo', duration: '30 min' }], resources: [{"title":"LinkedIn Groups","type":"tool","url":"https://www.linkedin.com/groups"},{"title":"Discord","type":"tool","url":"https://discord.com"},{"title":"Meetup.com","type":"tool","url":"https://www.meetup.com"}], successCriteria: ['✓ Top 5 procesos priorizados', '✓ Prep intensiva completada', '✓ Nuevas aplicaciones enviadas'] },
  43: { day: 43, title: 'Entrevista Final: Salary Negotiation Prep', fullDescription: 'Prepárate para conversar de compensación. Negocia desde posición fuerte.', objective: 'Maximizar paquete de compensación', steps: [{ stepNumber: 1, title: 'Investiga rango salarial típico', description: 'Levels.fyi, Blind, Glassdoor', duration: '30 min' }, { stepNumber: 2, title: 'Define tu número objetivo', description: 'Base, bonus, equity, benefits', duration: '20 min' }, { stepNumber: 3, title: 'Prepara negociación', description: 'Cómo hacer contrapropuesta', duration: '30 min' }], resources: [], successCriteria: ['✓ Salarios investigados', '✓ Número definido', '✓ Estrategia de negociación lista'] },
  44: { day: 44, title: 'Content: Publica artículo importante', fullDescription: 'Segundo post de serie. Demuestra pensamiento estratégico.', objective: 'Continuar construyendo autoridad', steps: [{ stepNumber: 1, title: 'Elige tema profundo', description: 'Algo donde tienes expertise real', duration: '15 min' }, { stepNumber: 2, title: 'Investiga y escribe', description: '1500+ palabras, bien investigado', duration: '180 min' }, { stepNumber: 3, title: 'Publica y promociona', description: 'LinkedIn, comunidades, newsletters', duration: '30 min' }], resources: [], successCriteria: ['✓ Tema elegido', '✓ Artículo escrito', '✓ Publicado y promocionado'] },
  45: { day: 45, title: 'Checkpoint Profundo: Día 45', fullDescription: 'Evaluación de mitad de camino. Decisiones importantes para últimas 2 semanas Mes 2.', objective: 'Estar en posición de fuerza para cerrar', steps: [{ stepNumber: 1, title: 'Mide todos los KPIs', description: 'Entrevistas, ofertas, cambios, oportunidades', duration: '30 min' }, { stepNumber: 2, title: 'Analiza qué está funcionando', description: 'Patrones de éxito', duration: '20 min' }, { stepNumber: 3, title: 'Define estrategia final', description: 'Cómo cerrar mes 2 fuerte', duration: '30 min' }], resources: [], successCriteria: ['✓ Todos los KPIs medidos', '✓ Patrones identificados', '✓ Estrategia final definida'] },
  46: { day: 46, title: 'Ofertas: Negocia y Compara', fullDescription: 'Si tienes ofertas: compáralas, negocia términos, toma decisiones.', objective: 'Obtener mejor oferta posible', steps: [{ stepNumber: 1, title: 'Documenta cada oferta', description: 'Sueldo, beneficios, ubicación, equipo', duration: '20 min' }, { stepNumber: 2, title: 'Negocia con cada empresa', description: 'Mejora términos si es posible', duration: '90 min' }, { stepNumber: 3, title: 'Compara finalmente', description: 'Qué te atrae más allá del sueldo', duration: '30 min' }], resources: [], successCriteria: ['✓ Todas las ofertas documentadas', '✓ Negociaciones completadas', '✓ Comparación final hecha'] },
  47: { day: 47, title: 'Última semana: Cierre Mes 2', fullDescription: 'Última semana del mes 2. Termina fuerte.', objective: 'Cerrar con decisiones tomadas', steps: [{ stepNumber: 1, title: 'Finaliza decisiones importantes', description: 'Aceptas oferta? Rechazas? Sigues?', duration: '60 min' }, { stepNumber: 2, title: 'Comunica decisiones profesionalmente', description: 'Accept letter, declinations, follow-ups', duration: '30 min' }, { stepNumber: 3, title: 'Documenta aprendizajes', description: 'Qué aprendiste en Mes 2', duration: '20 min' }], resources: [], successCriteria: ['✓ Decisiones finalizadas', '✓ Comunicadas profesionalmente', '✓ Aprendizajes documentados'] },
  48: { day: 48, title: 'Reflexión: Oportunidades Missed', fullDescription: 'Reflexiona sobre oportunidades que no cerraste. Lecciones para Mes 3.', objective: 'Aprender de lo que no funcionó', steps: [{ stepNumber: 1, title: 'Analiza procesos que no avanzaron', description: 'Por qué no pasó a siguiente ronda?', duration: '30 min' }, { stepNumber: 2, title: 'Identifica patrones negativos', description: 'Qué hacer diferente?', duration: '20 min' }, { stepNumber: 3, title: 'Define mejoras para Mes 3', description: 'Cómo no repetir estos errores', duration: '20 min' }], resources: [{"title":"LinkedIn","type":"tool","url":"https://www.linkedin.com"},{"title":"Gmail","type":"tool","url":"https://mail.google.com"}], successCriteria: ['✓ Oportunidades analizadas', '✓ Patrones identificados', '✓ Mejoras definidas'] },
  49: { day: 49, title: 'Dominio: Maestría del Skill Crítico', fullDescription: 'Ya casi terminas el curso. Estás llegando a nivel senior en tu skill crítico.', objective: 'Alcanzar mastery en skill principal', steps: [{ stepNumber: 1, title: 'Dedica 5+ horas al curso final', description: 'Tópicos avanzados y últimas lecciones', duration: '300 min' }, { stepNumber: 2, title: 'Enseña a otros', description: 'Documenta lo que aprendiste', duration: '60 min' }, { stepNumber: 3, title: 'Prepárate para certificación', description: 'Si existe', duration: '30 min' }], resources: [], successCriteria: ['✓ Curso casi completado', '✓ Enseñado a otros', '✓ Listo para certificación'] },
  50: { day: 50, title: 'Revisión Mes 2: Evaluación Completa', fullDescription: 'Revisa mes 2 completamente. Celebra logros, documenta learnings, prepara Mes 3.', objective: 'Consolidar progreso de 60 días', steps: [{ stepNumber: 1, title: 'Revisa objetivos vs realidad Mes 2', description: 'Qué alcanzaste? Qué no?', duration: '30 min' }, { stepNumber: 2, title: 'Mide KPIs finales', description: 'Entrevistas, ofertas, skills, red', duration: '20 min' }, { stepNumber: 3, title: 'Planifica intensivamente Mes 3', description: 'Cómo cerrar fuerte', duration: '60 min' }], resources: [], successCriteria: ['✓ Objetivos vs realidad revisados', '✓ KPIs medidos', '✓ Mes 3 planificado intensamente'] },
  51: { day: 51, title: 'Si NO tienes oferta: Pivota', fullDescription: 'Si aún no cerraste: analiza si pivotar o doblar esfuerzos.', objective: 'Decisión estratégica clara', steps: [{ stepNumber: 1, title: 'Evalúa pipeline actual', description: 'Qué está en movimiento?', duration: '20 min' }, { stepNumber: 2, title: 'Analiza opciones', description: 'Doblar esfuerzo? Cambiar estrategia? Expandir búsqueda?', duration: '30 min' }, { stepNumber: 3, title: 'Define plan Mes 3', description: 'Que sea agresivo y claro', duration: '20 min' }], resources: [], successCriteria: ['✓ Pipeline evaluado', '✓ Opciones analizadas', '✓ Plan Mes 3 definido'] },
  52: { day: 52, title: 'Si TIENES oferta: Prepárate para Day 1', fullDescription: 'Ya aceptaste! Prepárate para empezar tu nuevo rol.', objective: 'Transición suave al nuevo rol', steps: [{ stepNumber: 1, title: 'Conecta con tu futuro team', description: 'Introduce con manager, equipo', duration: '30 min' }, { stepNumber: 2, title: 'Prepárate para Day 1', description: 'Setup, documentación, preguntas', duration: '60 min' }, { stepNumber: 3, title: 'Reflexiona sobre el journey', description: 'De dónde vienes, a dónde vas', duration: '30 min' }], resources: [{"title":"Glassdoor","type":"tool","url":"https://www.glassdoor.com"},{"title":"LinkedIn Job Search","type":"tool","url":"https://www.linkedin.com/jobs"}], successCriteria: ['✓ Team conocido', '✓ Day 1 preparado', '✓ Journey reflexionado'] },
  53: { day: 53, title: 'Continuidad: Sigue preparándote', fullDescription: 'Ya sea con oferta o sin ella, continúa preparándote.', objective: 'Momentum no se detiene', steps: [{ stepNumber: 1, title: 'Termina curso o certificación', description: 'Si aún no lo hiciste', duration: '120 min' }, { stepNumber: 2, title: 'Publica tercer artículo importante', description: 'Cierre de serie de contenido', duration: '120 min' }, { stepNumber: 3, title: 'Expande red una vez más', description: '10+ nuevos contactos significativos', duration: '60 min' }], resources: [], successCriteria: ['✓ Curso terminado', '✓ Artículo publicado', '✓ Red expandida'] },
  54: { day: 54, title: 'Masterclass: Aprende de Tu Journey', fullDescription: 'Crea contenido sobre tu experiencia. Ayuda a otros en su búsqueda.', objective: 'Convertir tu experiencia en valor', steps: [{ stepNumber: 1, title: 'Graba/Escribe masterclass', description: 'Sobre tu journey de 60 días', duration: '120 min' }, { stepNumber: 2, title: 'Comparte en comunidad', description: 'Meetups, grupos, redes', duration: '30 min' }, { stepNumber: 3, title: 'Genera oportunidades de mentoring', description: 'Ofrece ayudar a otros', duration: '20 min' }], resources: [], successCriteria: ['✓ Masterclass creada', '✓ Compartida', '✓ Mentoring ofrecido'] },
  55: { day: 55, title: 'Próximos pasos: Carrera a Largo Plazo', fullDescription: 'Piensa más allá del rol inicial. Dónde quieres estar en 2-3 años?', objective: 'Claridad sobre carrera futura', steps: [{ stepNumber: 1, title: 'Define visión 3 años', description: 'Rol, nivel, empresa, skills', duration: '30 min' }, { stepNumber: 2, title: 'Identifica gaps', description: 'Qué necesitas para llegar', duration: '20 min' }, { stepNumber: 3, title: 'Crea plan de desarrollo', description: 'Skills, experiencia, red', duration: '30 min' }], resources: [{"title":"Notion","type":"tool","url":"https://www.notion.so"},{"title":"Google Sheets","type":"tool","url":"https://sheets.google.com"}], successCriteria: ['✓ Visión 3 años definida', '✓ Gaps identificados', '✓ Plan de desarrollo creado'] },
  56: { day: 56, title: 'Celebración: Mes 2 COMPLETADO', fullDescription: 'Celebra haber llegado al Día 56. 2 meses. Eres diferente.', objective: 'Reconocer transformación', steps: [{ stepNumber: 1, title: 'Reflexiona sobre Day 1 vs Hoy', description: 'Cómo has evolucionado?', duration: '30 min' }, { stepNumber: 2, title: 'Comparte tu éxito', description: 'Con mentores, amigos, familia', duration: '30 min' }, { stepNumber: 3, title: 'Documenta todo para histórico', description: 'Portfolio, LinkedIn, blog', duration: '30 min' }], resources: [], successCriteria: ['✓ Reflexión completada', '✓ Éxito compartido', '✓ Documentado para histórico'] },
  57: { day: 57, title: 'Pre-Mes3: Prepara Sprint Final', fullDescription: 'Los últimos 30 días. Prepárate mentalmente y estratégicamente.', objective: 'Mentalidad de sprint final', steps: [{ stepNumber: 1, title: 'Revisa visión original', description: 'Dónde estabas Day 1?', duration: '15 min' }, { stepNumber: 2, title: 'Define objetivos finales Mes 3', description: 'Qué quieres haber logrado en 90 días?', duration: '30 min' }, { stepNumber: 3, title: 'Planifica semanas 1-4 de Mes 3', description: 'Acciones concretas', duration: '30 min' }], resources: [], successCriteria: ['✓ Visión original revisada', '✓ Objetivos Mes 3 definidos', '✓ Semanas planificadas'] },
  58: { day: 58, title: 'Networking Avanzado: C-Level Connections', fullDescription: 'En Mes 3, conecta con líderes senior. Expande red a nuevas alturas.', objective: 'Acceso a líderes y decisores', steps: [{ stepNumber: 1, title: 'Identifica 5-10 líderes clave', description: 'CEOs, CTOs, VPs de empresas objetivo', duration: '30 min' }, { stepNumber: 2, title: 'Crea estrategia de aproximación', description: 'Referrals, eventos, contenido', duration: '30 min' }, { stepNumber: 3, title: 'Inicia contacto', description: 'De manera profesional y respetuosa', duration: '20 min' }], resources: [], successCriteria: ['✓ Líderes identificados', '✓ Estrategia definida', '✓ Contacto iniciado'] },
  59: { day: 59, title: 'Penúltimo: Reflexión y Cierre', fullDescription: 'Penúltimo día. Prepárate emocionalmente para el Día 90 final.', objective: 'Transición mental para conclusión', steps: [{ stepNumber: 1, title: 'Escribe carta a ti Day 1', description: 'Lo que cambiaste, lo que aprendiste', duration: '45 min' }, { stepNumber: 2, title: 'Prepara presentación de resultados', description: 'Para compartir si lo deseas', duration: '60 min' }, { stepNumber: 3, title: 'Medita sobre journey', description: 'Qué significa este viaje?', duration: '20 min' }], resources: [], successCriteria: ['✓ Carta escrita', '✓ Presentación preparada', '✓ Meditación completada'] },
  60: { day: 60, title: 'Mes 2 COMPLETADO: Ya casi', fullDescription: 'Fin del Mes 2. 60 días. Tienes 30 días más.', objective: 'Reconocer mitad del camino completada', steps: [{ stepNumber: 1, title: 'Mide cambio total', description: 'Day 1 vs Day 60, eres otra persona', duration: '30 min' }, { stepNumber: 2, title: 'Solidifica lo aprendido', description: 'Skills, mentalidad, red', duration: '30 min' }, { stepNumber: 3, title: 'Prepárate para sprint final', description: '30 días decisivos por delante', duration: '30 min' }], resources: [{"title":"Notion","type":"tool","url":"https://www.notion.so"},{"title":"Medium","type":"article","url":"https://medium.com"}], successCriteria: ['✓ Cambio medido', '✓ Aprendizajes solidificados', '✓ Sprint final preparado'] },

  // MONTH 3: MASTERY (Días 61-90)
  61: { day: 61, title: 'Mes 3 COMIENZA: Sprint Final', fullDescription: 'Últimos 30 días. Esta es tu recta final. Máxima intensidad.', objective: 'Cerrar fuerte los 90 días', steps: [{ stepNumber: 1, title: 'Visualiza end state', description: 'Dónde quieres estar Day 90?', duration: '20 min' }, { stepNumber: 2, title: 'Define daily non-negotiables', description: 'Qué haces TODOS los días?', duration: '15 min' }, { stepNumber: 3, title: 'Inicia con energía máxima', description: 'Primer día de últimos 30', duration: '30 min' }], resources: [{"title":"Medium","type":"article","url":"https://medium.com"},{"title":"LinkedIn Articles","type":"article","url":"https://www.linkedin.com"}], successCriteria: ['✓ End state visualizado', '✓ Daily non-negotiables definidos', '✓ Energía al máximo'] },
  62: { day: 62, title: 'Profundidad: Expertise a Nivel Maestría', fullDescription: 'Es tiempo de demostrar mastery. Sé el experto en la sala.', objective: 'Alcanzar nivel de maestría', steps: [{ stepNumber: 1, title: 'Completa tu curso o certificación', description: 'Final push hacia terminación', duration: '120 min' }, { stepNumber: 2, title: 'Enseña a 3+ personas', description: 'Lo que aprendiste este mes', duration: '60 min' }, { stepNumber: 3, title: 'Crea guía/recurso compartible', description: 'Para comunidad', duration: '90 min' }], resources: [], successCriteria: ['✓ Certificación completada', '✓ Enseñado a otros', '✓ Recurso creado'] },
  63: { day: 63, title: 'Cierre de Oportunidades: Accelera Decisiones', fullDescription: 'Si tienes múltiples procesos abiertos, decide y cierra.', objective: 'Tomar decisiones definitivas', steps: [{ stepNumber: 1, title: 'Lista TODOS los procesos activos', description: 'Dónde estás exactamente en cada uno', duration: '20 min' }, { stepNumber: 2, title: 'Acerca el finish line en cada uno', description: 'Push final en top 3', duration: '120 min' }, { stepNumber: 3, title: 'Negocia término final', description: 'Si no lo hiciste ya', duration: '60 min' }], resources: [], successCriteria: ['✓ Procesos listados', '✓ Push final completado', '✓ Negociación finalizada'] },
  64: { day: 64, title: 'Semana 1 Mes 3: Máxima Acción', fullDescription: 'Primera semana de Mes 3. Corre fuerte.', objective: 'Máximo volumen y calidad de acciones', steps: [{ stepNumber: 1, title: 'Aplica a 10+ posiciones nuevas', description: 'Con refinement de 60 días', duration: '90 min' }, { stepNumber: 2, title: 'Contacta 20+ nuevas personas', description: 'Decision makers, recruiters, peers', duration: '90 min' }, { stepNumber: 3, title: 'Realiza 3 informational interviews', description: 'Con expertos seniors', duration: '90 min' }], resources: [], successCriteria: ['✓ 10+ aplicaciones', '✓ 20+ nuevos contactos', '✓ 3 interviews completadas'] },
  65: { day: 65, title: 'Visibility: Tu Mejor Día de Contenido', fullDescription: 'Publica tu mejor pieza de contenido. Resume el journey de 65 días.', objective: 'Máxima visibilidad en tu industria', steps: [{ stepNumber: 1, title: 'Escribe ensayo maestro', description: '2000+ palabras, profundidad total', duration: '240 min' }, { stepNumber: 2, title: 'Diseña infografía o visual', description: 'Journey visual de 65 días', duration: '60 min' }, { stepNumber: 3, title: 'Lanza con máxima promoción', description: 'Todos tus canales, comunidades', duration: '30 min' }], resources: [{"title":"Behance","type":"tool","url":"https://www.behance.net"},{"title":"GitHub","type":"tool","url":"https://github.com"}], successCriteria: ['✓ Ensayo maestro publicado', '✓ Visual creada', '✓ Promoción máxima'] },
  66: { day: 66, title: 'Mentoría: Ahora Mentoriza a Otros', fullDescription: 'Ya estás lo suficientemente avanzado. Ayuda a otros en su journey.', objective: 'Convertir experiencia en legado', steps: [{ stepNumber: 1, title: 'Formaliza 2-3 relaciones de mentoring', description: 'Con personas en etapas tempranas', duration: '30 min' }, { stepNumber: 2, title: 'Crea programa de mentoría', description: 'Regular, structured, impactful', duration: '30 min' }, { stepNumber: 3, title: 'Comienza sesiones', description: 'Primer grupo de mentees', duration: '60 min' }], resources: [], successCriteria: ['✓ Mentorías formalizadas', '✓ Programa creado', '✓ Sesiones iniciadas'] },
  67: { day: 67, title: 'Perspectiva: Análisis Cuantitativo Profundo', fullDescription: 'Mide TODO de los últimos 67 días. Eres un case study de éxito.', objective: 'Entender exactamente qué funcionó', steps: [{ stepNumber: 1, title: 'Crea dashboard completo', description: 'Todas las métricas del journey', duration: '60 min' }, { stepNumber: 2, title: 'Identifica patrones de éxito', description: 'Qué generó resultados?', duration: '30 min' }, { stepNumber: 3, title: 'Crea reporte para compartir', description: 'De aprendizajes clave', duration: '60 min' }], resources: [], successCriteria: ['✓ Dashboard creado', '✓ Patrones identificados', '✓ Reporte escrito'] },
  68: { day: 68, title: 'Desempeño: Prepárate para Éxito en Nuevo Rol', fullDescription: 'Si aceptaste oferta: prepárate en serio para brillar Day 1.', objective: 'Lanzar fuerte en nuevo rol', steps: [{ stepNumber: 1, title: 'Aprende stack técnico/herramientas', description: 'O industria knowledge si aplica', duration: '120 min' }, { stepNumber: 2, title: 'Conecta profundamente con team', description: 'Coffee chats, preguntas, cultura', duration: '60 min' }, { stepNumber: 3, title: 'Prepara "first 30 day plan"', description: 'Qué quieres lograr primero', duration: '60 min' }], resources: [], successCriteria: ['✓ Stack técnico aprendido', '✓ Team conocido profundamente', '✓ 30-day plan creado'] },
  69: { day: 69, title: 'Semana 2 Mes 3: Consolidación', fullDescription: 'Segunda semana de Mes 3. Consolida mejores oportunidades.', objective: 'De cantidad a calidad', steps: [{ stepNumber: 1, title: 'Prioriza top 5 procesos más prometedores', description: 'Donde realmente quieres trabajar', duration: '20 min' }, { stepNumber: 2, title: 'Intensifica prep para esos 5', description: 'Investigación, referencias, stories', duration: '120 min' }, { stepNumber: 3, title: 'Mantén disciplina: 2-3 nuevas aplicaciones', description: 'Para pipeline', duration: '30 min' }], resources: [], successCriteria: ['✓ Top 5 priorizados', '✓ Prep intensificada', '✓ Nuevas aplicaciones enviadas'] },
  70: { day: 70, title: 'Checkpoint: Día 70 de 90', fullDescription: 'Estás en 77% del journey. Evaluación rápida.', objective: 'Asegurar estás donde querías estar', steps: [{ stepNumber: 1, title: 'Revisa objetivos del Day 1', description: 'Estás en la dirección correcta?', duration: '15 min' }, { stepNumber: 2, title: 'Mide progreso vs plan', description: 'Ahead? On track? Behind?', duration: '15 min' }, { stepNumber: 3, title: 'Ajusta últimos 20 días si necesitas', description: 'Qué acelerar, qué dejar', duration: '20 min' }], resources: [{"title":"Dev.to","type":"article","url":"https://dev.to"},{"title":"HackerNews","type":"article","url":"https://news.ycombinator.com"}], successCriteria: ['✓ Objetivos revisados', '✓ Progreso medido', '✓ Ajustes identificados'] },
  71: { day: 71, title: 'Confianza: Deja Ir lo que No Sirvió', fullDescription: 'Ya sabes qué NO funciona. Suelta eso.', objective: 'Psicológica: soltar el pasado', steps: [{ stepNumber: 1, title: 'Identifica qué abandonar', description: 'Estrategias, contactos, procesos que no van', duration: '20 min' }, { stepNumber: 2, title: 'Comunica cierre profesional', description: 'A procesos que no avanzarán', duration: '30 min' }, { stepNumber: 3, title: 'Refocaliza energía', description: 'En lo que SÍ funciona', duration: '20 min' }], resources: [], successCriteria: ['✓ Abandonos identificados', '✓ Cierres comunicados', '✓ Energía refocalizada'] },
  72: { day: 72, title: 'Ofertas Finales: Toma la Decisión', fullDescription: 'Hora de decidir. Acepta, rechaza, o espera sabiendo por qué.', objective: 'Decisión final basada en datos y gut', steps: [{ stepNumber: 1, title: 'Revisa TODAS las ofertas en la mesa', description: 'Salario, beneficios, cultura, crecimiento', duration: '30 min' }, { stepNumber: 2, title: 'Conversa FINAL con personas clave', description: 'Hiring managers, future team', duration: '60 min' }, { stepNumber: 3, title: 'Toma decisión y comunica', description: 'Profesional, claro, sin dudas', duration: '20 min' }], resources: [], successCriteria: ['✓ Todas las ofertas revisadas', '✓ Conversaciones finales completadas', '✓ Decisión comunicada'] },
  73: { day: 73, title: 'Tercera semana Mes 3: Push Final', fullDescription: 'Tercera semana. 17 días para cerrar fuerte.', objective: 'Máximo esfuerzo final', steps: [{ stepNumber: 1, title: 'Dobla volumen en procesos finales', description: 'Último push en top 3', duration: '120 min' }, { stepNumber: 2, title: 'Contacta última ola de recruiters', description: '10+ para mantener opciones', duration: '60 min' }, { stepNumber: 3, title: 'Asegura 2-3 nuevas entrevistas', description: 'Para cerrar Mes 3', duration: '60 min' }], resources: [], successCriteria: ['✓ Procesos finales intensificados', '✓ Última ola contactada', '✓ Nuevas entrevistas aseguradas'] },
  74: { day: 74, title: 'Cierre: Onboarding y Transición', fullDescription: 'Si aceptaste: comienza transition plan formal.', objective: 'Transición suave a nuevo rol', steps: [{ stepNumber: 1, title: 'Completa todo onboarding paperwork', description: 'Antes de Day 1', duration: '60 min' }, { stepNumber: 2, title: 'Setup final: laptop, accesos, etc', description: 'Coordinando con IT', duration: '30 min' }, { stepNumber: 3, title: 'Relaciones finales: despididas y agradecimientos', description: 'Con mentores, contactos, etc', duration: '60 min' }], resources: [], successCriteria: ['✓ Paperwork completado', '✓ Setup coordinado', '✓ Despedidas realizadas'] },
  75: { day: 75, title: 'Legado: Documenta Tu Camino', fullDescription: 'Crea documentación de tu journey para inspirar a otros.', objective: 'Tu experiencia se convierte en recurso', steps: [{ stepNumber: 1, title: 'Escribe guía completa', description: '90 days playbook de tu journey', duration: '180 min' }, { stepNumber: 2, title: 'Crea video o podcast', description: 'Entrevista sobre experiencia', duration: '120 min' }, { stepNumber: 3, title: 'Comparte en comunidad', description: 'Abierto para todos que busquen', duration: '30 min' }], resources: [{"title":"LinkedIn Learning","type":"course","url":"https://www.linkedin.com/learning"},{"title":"Masterclass","type":"course","url":"https://www.masterclass.com"}], successCriteria: ['✓ Guía escrita', '✓ Video/podcast creado', '✓ Compartido'] },
  76: { day: 76, title: 'Penúltima semana: Cierre Mes 3', fullDescription: 'Penúltima semana. 14 días.', objective: 'Cerrar procesos abiertos', steps: [{ stepNumber: 1, title: 'Finaliza cualquier negociación pendiente', description: 'Todos los términos', duration: '30 min' }, { stepNumber: 2, title: 'Comunica updates a tu red', description: 'Resultados, si quieres', duration: '30 min' }, { stepNumber: 3, title: 'Prepara last week mentally', description: 'Emotionalmente, un mes intenso', duration: '20 min' }], resources: [], successCriteria: ['✓ Negociaciones finalizadas', '✓ Red actualizada', '✓ Preparación mental completada'] },
  77: { day: 77, title: 'Reflexión Profunda: Quién Eres Ahora', fullDescription: 'Day 77. Ya no eres quien eras Day 1.', objective: 'Reconocer transformación total', steps: [{ stepNumber: 1, title: 'Escribe reflexión transformación', description: 'Identidad, confianza, dirección', duration: '60 min' }, { stepNumber: 2, title: 'Analiza cambios en mentalidad', description: 'Creencias, miedos, certezas', duration: '30 min' }, { stepNumber: 3, title: 'Visión de futuro con nueva realidad', description: 'Quién eres en 3 meses?', duration: '30 min' }], resources: [], successCriteria: ['✓ Reflexión transformación escrita', '✓ Cambios de mentalidad analizados', '✓ Visión futura clarificada'] },
  78: { day: 78, title: 'Gratitud: Day 78 de Éxito', fullDescription: 'Agradece a todo el que te ayudó.', objective: 'Cerrar con el corazón abierto', steps: [{ stepNumber: 1, title: 'Lista 10-20 personas clave', description: 'Que impactaron tu journey', duration: '20 min' }, { stepNumber: 2, title: 'Escribe notas de agradecimiento', description: 'Personalizadas, auténticas', duration: '90 min' }, { stepNumber: 3, title: 'Envía y sigue conectado', description: 'Mantén relaciones vivas', duration: '20 min' }], resources: [], successCriteria: ['✓ Personas clave listadas', '✓ Notas escritas', '✓ Notas enviadas'] },
  79: { day: 79, title: 'Último viernes: Celebración Final', fullDescription: 'El viernes de penúltima semana. Celebra lo hecho.', objective: 'Celebración merecida', steps: [{ stepNumber: 1, title: 'Organiza pequeña celebración', description: 'Con mentores, amigos, familia', duration: '30 min' }, { stepNumber: 2, title: 'Comparte resultados del journey', description: 'Abiertamente, sin modestia falsa', duration: '60 min' }, { stepNumber: 3, title: 'Reflexiona sobre significancia', description: 'Qué significa esto en tu vida', duration: '30 min' }], resources: [], successCriteria: ['✓ Celebración organizada', '✓ Resultados compartidos', '✓ Significancia reflexionada'] },
  80: { day: 80, title: 'Semana Final: 10 Días Restantes', fullDescription: 'Last week! 10 días nada más.', objective: 'Disfrutar el tramo final', steps: [{ stepNumber: 1, title: 'Haz lista de "no arrepentimientos"', description: 'Qué querías hacer y aún puedes?', duration: '30 min' }, { stepNumber: 2, title: 'Completa 1-2 cosas de esa lista', description: 'Informational interviews, conexiones', duration: '120 min' }, { stepNumber: 3, title: 'Descansa pero enfocado', description: 'Mantén momentum pero disfruta', duration: '20 min' }], resources: [{"title":"Levels.fyi","type":"tool","url":"https://www.levels.fyi"},{"title":"Blind","type":"tool","url":"https://www.payscale.com"}], successCriteria: ['✓ Lista de arrepentimientos hecha', '✓ 1-2 items completados', '✓ Balance reposo/acción logrado'] },
  81: { day: 81, title: 'Día 81: Regala Valor', fullDescription: 'Con 9 días, regala valor a tu comunidad.', objective: 'Impacto antes de terminar', steps: [{ stepNumber: 1, title: 'Ofrece 3-5 coffee calls', description: 'Personas buscando, gratis', duration: '90 min' }, { stepNumber: 2, title: 'Comparte recursos curados', description: 'Lo mejor de 81 días', duration: '60 min' }, { stepNumber: 3, title: 'Haz algo inesperadamente amable', description: 'Con alguien en su journey', duration: '30 min' }], resources: [], successCriteria: ['✓ Coffee calls ofrecidas', '✓ Recursos compartidos', '✓ Acto de amabilidad completado'] },
  82: { day: 82, title: 'Día 82: Integración', fullDescription: 'Si empezaste nuevo rol hoy: primer día integración real.', objective: 'Buena primera impresión', steps: [{ stepNumber: 1, title: 'Conoce a tu equipo en profundidad', description: '1:1s con todos, si no lo hiciste', duration: '120 min' }, { stepNumber: 2, title: 'Empieza projects según plan', description: 'First week deliverables', duration: '60 min' }, { stepNumber: 3, title: 'Reflexiona sobre Day 1 nuevo rol', description: 'Cómo se siente?', duration: '20 min' }], resources: [], successCriteria: ['✓ Team conocido', '✓ Projects iniciados', '✓ Day 1 reflexionado'] },
  83: { day: 83, title: 'Día 83: Future Ready', fullDescription: 'Con 7 días, prepárate para lo que viene después de Day 90.', objective: 'Transición suave a siguiente capítulo', steps: [{ stepNumber: 1, title: 'Define objetivos de próximos 90 días', description: 'En nuevo rol o búsqueda', duration: '30 min' }, { stepNumber: 2, title: 'Crea plan de crecimiento', description: 'Skills, network, visibilidad', duration: '60 min' }, { stepNumber: 3, title: 'Asegura accountability', description: 'Mentores, colegas que te tracking', duration: '20 min' }], resources: [], successCriteria: ['✓ Próximos 90 días definidos', '✓ Plan de crecimiento creado', '✓ Accountability asegurado'] },
  84: { day: 84, title: 'Día 84: Stabilización', fullDescription: '6 días. Estabiliza lo aprendido.', objective: 'Consolidar nuevo estado', steps: [{ stepNumber: 1, title: 'Revisa todos los learnings', description: 'Qué quedará contigo', duration: '30 min' }, { stepNumber: 2, title: 'Integra nuevos hábitos', description: 'Networking, aprendizaje, acción', duration: '30 min' }, { stepNumber: 3, title: 'Comunica a tu sistema interno', description: 'Estos cambios son permanentes', duration: '20 min' }], resources: [], successCriteria: ['✓ Learnings consolidados', '✓ Nuevos hábitos establecidos', '✓ Identidad actualizada'] },
  85: { day: 85, title: 'Día 85: Paz', fullDescription: '5 días. Has hecho todo lo que podías.', objective: 'Paz mental y emocional', steps: [{ stepNumber: 1, title: 'Suelta control sobre resultados', description: 'Hiciste tu parte', duration: '20 min' }, { stepNumber: 2, title: 'Disfruta lo que lograste', description: 'Sin medir contra idealización', duration: '30 min' }, { stepNumber: 3, title: 'Descansa consciente', description: 'Recupera energía', duration: '40 min' }], resources: [{"title":"LinkedIn","type":"tool","url":"https://www.linkedin.com"},{"title":"GitHub","type":"tool","url":"https://github.com"}], successCriteria: ['✓ Control soltado', '✓ Logros disfrutados', '✓ Descanso consciente realizado'] },
  86: { day: 86, title: 'Día 86: Preparación Final', fullDescription: '4 días. Prepárate para terminar.', objective: 'Cierre mental y emocional', steps: [{ stepNumber: 1, title: 'Prepara statement final', description: 'El mensaje de Day 90', duration: '45 min' }, { stepNumber: 2, title: 'Revisa fotos/videos del journey', description: 'Evidencia de transformación', duration: '30 min' }, { stepNumber: 3, title: 'Invita gente a celebración Day 90', description: 'Si quieres compartir', duration: '20 min' }], resources: [], successCriteria: ['✓ Statement preparado', '✓ Fotos/videos revisados', '✓ Celebración invitaciones enviadas'] },
  87: { day: 87, title: 'Día 87: Carta Final', fullDescription: '3 días. Escribe carta a tu yo del futuro.', objective: 'Comunicación con futuro', steps: [{ stepNumber: 1, title: 'Escribe carta a ti en Day 120', description: 'Abierta en 30 días', duration: '45 min' }, { stepNumber: 2, title: 'Documenta promesas a ti mismo', description: 'Qué mantendrás de esto', duration: '30 min' }, { stepNumber: 3, title: 'Sella la carta literalmente o digitalmente', description: 'Símbolo de compromiso', duration: '15 min' }], resources: [], successCriteria: ['✓ Carta escrita', '✓ Promesas documentadas', '✓ Carta sellada'] },
  88: { day: 88, title: 'Día 88: Penúltimo', fullDescription: '2 días. Almost there.', objective: 'Presencia total', steps: [{ stepNumber: 1, title: 'Estate completamente presente hoy', description: 'Sin prisa, sin ansia', duration: '20 min' }, { stepNumber: 2, title: 'Haz algo especial por ti', description: 'Por haber llegado aquí', duration: '60 min' }, { stepNumber: 3, title: 'Prepara tu mente para mañana', description: 'El día antes del final', duration: '20 min' }], resources: [], successCriteria: ['✓ Presencia total lograda', '✓ Algo especial hecho', '✓ Mente preparada'] },
  89: { day: 89, title: 'Día 89: Day Before', fullDescription: '1 día. Tomorrow is Day 90.', objective: 'Anticipación consciente', steps: [{ stepNumber: 1, title: 'Revisa todo lo hecho', description: '89 días de trabajo', duration: '45 min' }, { stepNumber: 2, title: 'Prepara tu presentación Day 90', description: 'Si quieres compartir hoy', duration: '60 min' }, { stepNumber: 3, title: 'Duerme bien', description: 'Mañana celebramos', duration: '20 min' }], resources: [], successCriteria: ['✓ Todo revisado', '✓ Presentación preparada', '✓ Sueño reparador'] },
  90: { day: 90, title: '90 DÍAS COMPLETADOS: Has Ganado', fullDescription: 'Day 90. You made it. Eres diferente. Eres mejor. Eres ready.', objective: 'Celebrar completación y nueva realidad', steps: [{ stepNumber: 1, title: 'Celebra de manera especial', description: 'Sin moderación, hoy es tuyo', duration: '120 min' }, { stepNumber: 2, title: 'Comparte tu statement con el mundo', description: 'Si quieres que otros se inspiren', duration: '30 min' }, { stepNumber: 3, title: 'Define siguiente capítulo', description: 'Day 1 de lo que sigue', duration: '60 min' }], resources: [{"title":"Notion","type":"tool","url":"https://www.notion.so"},{"title":"Medium","type":"article","url":"https://medium.com"}], successCriteria: ['✓ Celebración completada', '✓ Statement compartido', '✓ Próximo capítulo definido', '✓ 90 DÍAS GANADOS'] }
}

export function getTaskDetail(day: number): TaskDetail | undefined {
  return TASK_DETAILS[day]
}

export function getAvailableDays(): number[] {
  return Object.keys(TASK_DETAILS).map(Number).sort((a, b) => a - b)
}
