import { NextResponse } from 'next/server'
import { resolveServerUser } from '@/lib/auth/server-user'
import { createAdminClient } from '@/lib/supabase/server'
import { checkA4Access, getA4AccessDenialMessage } from '@/lib/a4/access-control'
import { fetchChileTrabajosOpportunities } from '@/lib/opportunities/sources/chiletrabajos'
import { planOpportunityQueries } from '@/lib/opportunities/search-intent'
import { readVerifiedOpportunities, upsertVerifiedOpportunities } from '@/lib/opportunities/verified-index'
import { categorizeOpportunity } from '@/lib/opportunities/taxonomy'
export const runtime='nodejs';export const dynamic='force-dynamic'
const norm=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')
export async function GET(){const user=await resolveServerUser();if(!user)return NextResponse.json({error:'No autenticado'},{status:401});const supabase=createAdminClient();const access=await checkA4Access(user.id,supabase);if(!access.canAccess)return NextResponse.json({error:getA4AccessDenialMessage(),code:access.reason},{status:403});const {data:intent,error}=await supabase.from('career_search_intents').select('*').eq('user_id',user.id).eq('is_active',true).eq('is_primary',true).maybeSingle();if(error)return NextResponse.json({error:'No fue posible cargar tu búsqueda.'},{status:500});
 let index=await readVerifiedOpportunities(supabase,100);if(!index.length){const jobs=await fetchChileTrabajosOpportunities('','Santiago',18);await upsertVerifiedOpportunities(supabase,jobs);index=await readVerifiedOpportunities(supabase,100)}
 if(!intent)return NextResponse.json({needs_intent:true,mode:'available_now',source:'verified_index',fetched_at:new Date().toISOString(),count:index.slice(0,18).length,opportunities:index.slice(0,18).map(toPublic)})
 const roles=Array.isArray(intent.target_roles)?intent.target_roles.filter((v:unknown):v is string=>typeof v==='string'):[];const regions=Array.isArray(intent.locations)?intent.locations.filter((v:unknown):v is string=>typeof v==='string'):[];const roleTerms=planOpportunityQueries({targetRoles:roles,breadth:intent.breadth,locations:regions,workModes:Array.isArray(intent.work_modes)?intent.work_modes:[]});const categoryLabels=new Set(roles.map((r:string)=>categorizeOpportunity(r).label));
 let matches=index.filter(job=>{const title=norm(String(job.normalized_title||job.title||''));const category=String(job.category_label||'');const roleOk=!roles.length||roleTerms.some(term=>title.includes(norm(term)))||categoryLabels.has(category);const regionOk=!regions.length||!job.region||regions.includes(String(job.region));return roleOk&&regionOk});
 if(!matches.length&&roles.length){const location=regions[0]||'Santiago';for(const query of roleTerms.slice(0,6)){const jobs=await fetchChileTrabajosOpportunities(query,location,8);await upsertVerifiedOpportunities(supabase,jobs)}index=await readVerifiedOpportunities(supabase,100);matches=index.filter(job=>{const title=norm(String(job.normalized_title||job.title||''));const category=String(job.category_label||'');return roleTerms.some(term=>title.includes(norm(term)))||categoryLabels.has(category)})}
 return NextResponse.json({needs_intent:false,source:'verified_index',fetched_at:new Date().toISOString(),count:matches.slice(0,18).length,opportunities:matches.slice(0,18).map(toPublic)})}
function toPublic(job:any){return {sourceId:job.source_id,title:job.title,company:job.company||'Empresa no informada',location:job.location,publishedAt:job.published_at,expiresAt:job.expires_at,originalUrl:job.original_url,verificationStatus:job.verification_status}}
