import { NextResponse } from 'next/server'
import { resolveServerUser } from '@/lib/auth/server-user'
import { createAdminClient } from '@/lib/supabase/server'
import { checkA4Access, getA4AccessDenialMessage } from '@/lib/a4/access-control'
import { fetchChileTrabajosOpportunities } from '@/lib/opportunities/sources/chiletrabajos'
import { catalogFromJobs, regionCatalogFromJobs } from '@/lib/opportunities/taxonomy'
import { readVerifiedOpportunities, upsertVerifiedOpportunities } from '@/lib/opportunities/verified-index'
export const runtime='nodejs';export const dynamic='force-dynamic'
const SEEDS=['Santiago','Valparaíso','Concepción','Antofagasta','Puerto Montt']
export async function GET(request:Request){const user=await resolveServerUser();if(!user)return NextResponse.json({error:'No autenticado'},{status:401});const supabase=createAdminClient();const access=await checkA4Access(user.id,supabase);if(!access.canAccess)return NextResponse.json({error:getA4AccessDenialMessage(),code:access.reason},{status:403});let cached=await readVerifiedOpportunities(supabase,150);if(!cached.length){const batches=await Promise.allSettled(SEEDS.map(location=>fetchChileTrabajosOpportunities('',location,12)));const seen=new Set<string>();const jobs=[] as Awaited<ReturnType<typeof fetchChileTrabajosOpportunities>>;for(const batch of batches){if(batch.status!=='fulfilled')continue;for(const job of batch.value){if(!seen.has(job.originalUrl)){seen.add(job.originalUrl);jobs.push(job)}}}await upsertVerifiedOpportunities(supabase,jobs);cached=await readVerifiedOpportunities(supabase,150)}
 const url=new URL(request.url);const selectedRegions=url.searchParams.getAll('region').filter(Boolean);const selectedModes=url.searchParams.getAll('mode').filter(Boolean);const filtered=cached.filter(job=>(!selectedRegions.length||selectedRegions.includes(String(job.region||'')))&&(!selectedModes.length||!job.work_mode||selectedModes.includes(String(job.work_mode))));const catalog=catalogFromJobs(filtered);const regions=regionCatalogFromJobs(cached);return NextResponse.json({source:'verified_index',fetched_at:new Date().toISOString(),coverage:{verified_jobs:cached.length,filtered_jobs:filtered.length},total:filtered.length,total_available:cached.length,areas:catalog.areas.filter(x=>x.count>0),roles:catalog.roles.filter(x=>x.count>0).slice(0,50),regions,filters:{regions:selectedRegions,modes:selectedModes}})}
