import {
  Moon,
  SunMedium,
  type LucideIcon,
  TrendingUp,
  Brain,
  Target,
  Users,
  Award,
  GraduationCap,
  Building,
  Home,
  User,
  FileText,
  Search,
  BookOpen,
  MessageSquare,
  Settings,
  Menu,
  ChevronDown,
  ChevronRight,
  Check,
  X,
  Plus,
  Minus,
  Calendar,
  Clock,
  Star,
  Trophy,
  Zap,
  Shield,
  Heart,
  Globe,
  Mail,
  Phone,
  MapPin,
  Github,
  Twitter,
  Linkedin,
  Facebook,
  Instagram,
  Youtube,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  logo: TrendingUp,
  brain: Brain,
  target: Target,
  users: Users,
  award: Award,
  graduation: GraduationCap,
  building: Building,
  home: Home,
  user: User,
  fileText: FileText,
  search: Search,
  bookOpen: BookOpen,
  messageSquare: MessageSquare,
  settings: Settings,
  menu: Menu,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  check: Check,
  x: X,
  plus: Plus,
  minus: Minus,
  calendar: Calendar,
  clock: Clock,
  star: Star,
  trophy: Trophy,
  zap: Zap,
  shield: Shield,
  heart: Heart,
  globe: Globe,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  gitHub: Github,
  twitter: Twitter,
  linkedin: Linkedin,
  facebook: Facebook,
  instagram: Instagram,
  youtube: Youtube,
}
