import {
  BarChart3,
  BookOpen,
  Brain,
  Briefcase,
  FileText,
  GraduationCap,
  Home,
  MessageSquare,
  User,
  Users,
  Target,
  School,
  Code,
  Heart,
} from "lucide-react"

export const navigationItems = [
  { name: "Dashboard", href: "/dashboard", icon: Home },
  { name: "Perfil", href: "/profile", icon: User },
  { name: "CV Builder", href: "/cv-builder", icon: FileText },
  { name: "Coach de Carrera", href: "/career-coach", icon: MessageSquare },
  {
    name: "Evaluaciones",
    href: "/skills-assessment",
    icon: Brain,
    submenu: [
      { name: "Test de Personalidad", href: "/personality-test", icon: Brain },
      { name: "Test DISC", href: "/disc-test", icon: Target },
      { name: "Habilidades Técnicas", href: "/technical-skills-test", icon: Code },
      { name: "Habilidades Blandas", href: "/soft-skills-test", icon: Heart },
      { name: "Evaluación General", href: "/skills-assessment", icon: BarChart3 },
    ],
  },
  { name: "Búsqueda de Empleo", href: "/job-search", icon: Briefcase },
  { name: "Biblioteca", href: "/library", icon: BookOpen },
  { name: "Bachilleratos", href: "/bachillerato", icon: School },
  { name: "Carreras UDD", href: "/udd-careers", icon: GraduationCap },
  { name: "Simulador de Entrevistas", href: "/interview-simulator", icon: Users },
]
