'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Briefcase, Check, ChevronDown, MapPin, Search, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

const REGIONS=['Arica y Parinacota','Tarapacá','Antofagasta','Atacama','Coquimbo','Valparaíso','Metropolitana','O’Higgins','Maule','Ñuble','Biobío','La Araucanía','Los Ríos','Los Lagos','Aysén','Magallanes']
const MODES=[['onsite','Presencial'],['hybrid','Híbrido'],['remote','Remoto']] as const

function Tick({checked}:{checked:boolean}){return <span className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-md border transition ${checked?'border-[hsl(var(--dtc-indigo-300))] bg-[hsl(var(--dtc-indigo-900))] text-white':'border-border bg-background'}`}>{checked&&<Check className="h-3.5 w-3.5"/>}</span>}
function Chip({label,onRemove}:{label:string;onRemove:()=>void}){return <span className="inline-flex items-center gap-1.5 rounded-full border border-border bg-muted/70 px-3 py-1.5 text-xs font-medium text-foreground">{label}<button type="button" onClick={onRemove} aria-label={`Quitar ${label}`} className="rounded-full p-0.5 text-muted-foreground hover:bg-background hover:text-foreground"><X className="h-3 w-3"/></button></span>}
function Menu({open,children}:{open:boolean;children:React.ReactNode}){if(!open)return null;return <div className="absolute left-0 right-0 top-full z-40 mt-2 max-h-72 overflow-y-auto rounded-xl border border-border bg-popover p-2 shadow-2xl">{children}</div>}

export function SearchIntentForm({seedRole,onSaved}:{seedRole?:string|null;onSaved?:()=>void}) {
 const [roles,setRoles]=useState<string[]>(seedRole?.trim()?[seedRole.trim()]:[])
 const [role,setRole]=useState('')
 const [regions,setRegions]=useState<string[]>(['Metropolitana'])
 const [modes,setModes]=useState<string[]>(['hybrid','remote'])
 const [regionOpen,setRegionOpen]=useState(false)
 const [modeOpen,setModeOpen]=useState(false)
 const [saving,setSaving]=useState(false)
 const [message,setMessage]=useState<string|null>(null)\n const [catalog,setCatalog]=useState<{total:number;areas:{label:string;count:number}[];roles:{label:string;count:number}[]}|null>(null)\n useEffect(()=>{fetch('/api/a4/opportunities/catalog',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(v=>{if(v)setCatalog(v)}).catch(()=>{})},[])
 const modeLabels=useMemo(()=>MODES.filter(([v])=>modes.includes(v)).map(([,l])=>l),[modes])
 function addRole(){const v=role.trim();if(v&&!roles.some(r=>r.toLowerCase()===v.toLowerCase()))setRoles(x=>[...x,v]);setRole('')}
 function toggle(value:string,setter:React.Dispatch<React.SetStateAction<string[]>>){setter(xs=>xs.includes(value)?xs.filter(x=>x!==value):[...xs,value])}
 async function submit(event:FormEvent){event.preventDefault();setMessage(null);if(!roles.length){setMessage('Agrega al menos un cargo o área.');return}setSaving(true);try{const response=await fetch('/api/a4/search-intents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetRoles:roles,breadth:'related',locations:regions,workModes:modes.length?modes:['onsite','hybrid','remote'],isPrimary:true})});const data=await response.json();if(!response.ok)throw new Error(data.error||'No pudimos realizar la búsqueda.');onSaved?.()}catch(error){setMessage(error instanceof Error?error.message:'No pudimos realizar la búsqueda.')}finally{setSaving(false)}}
 return <Card className="overflow-visible border-border/80 bg-card shadow-sm">
  <CardHeader className="pb-5"><div className="flex items-start gap-3"><div className="hidden h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[hsl(var(--dtc-indigo-900))] text-white shadow-sm sm:flex"><Search className="h-5 w-5"/></div><div><CardTitle className="text-2xl tracking-tight">¿Qué trabajo estás buscando?</CardTitle><p className="mt-1 text-sm text-muted-foreground">Elige tus preferencias y encuentra oportunidades disponibles.</p>{catalog&&<p className="mt-2 text-xs font-medium text-muted-foreground">{catalog.total} oportunidades verificadas alimentan las sugerencias actuales.</p>}</div></div></CardHeader>
  <CardContent><form onSubmit={submit} className="space-y-5">
   <div className="grid gap-4 xl:grid-cols-3">
    <div className="space-y-2"><label className="text-xs font-semibold uppercase tracking-wide text-foreground">Cargos o áreas</label><div className="flex gap-2"><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input value={role} onChange={e=>setRole(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addRole()}}} placeholder="Buscar cargos o áreas…" className="h-11 w-full rounded-xl border border-input bg-background pl-10 pr-3 text-sm outline-none transition focus:border-[hsl(var(--dtc-indigo-300))] focus:ring-2 focus:ring-[hsl(var(--dtc-indigo-300))]/20"/></div><Button type="button" variant="outline" className="h-11 rounded-xl px-4" onClick={addRole}>Agregar</Button></div></div>
    <div className="relative space-y-2"><label className="text-xs font-semibold uppercase tracking-wide text-foreground">Regiones</label><button type="button" onClick={()=>{setRegionOpen(v=>!v);setModeOpen(false)}} className="flex h-11 w-full items-center rounded-xl border border-input bg-background px-3 text-left text-sm transition hover:border-muted-foreground/50"><MapPin className="mr-2 h-4 w-4 shrink-0 text-muted-foreground"/><span className="min-w-0 flex-1 truncate">{regions.length?regions.join(', '):'Todas las regiones'}</span><ChevronDown className={`ml-2 h-4 w-4 shrink-0 text-muted-foreground transition ${regionOpen?'rotate-180':''}`}/></button><Menu open={regionOpen}>{REGIONS.map(r=><button type="button" key={r} onClick={()=>toggle(r,setRegions)} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm hover:bg-muted"><Tick checked={regions.includes(r)}/><span className="min-w-0 flex-1">{r}</span></button>)}</Menu></div>
    <div className="relative space-y-2"><label className="text-xs font-semibold uppercase tracking-wide text-foreground">Modalidad</label><button type="button" onClick={()=>{setModeOpen(v=>!v);setRegionOpen(false)}} className="flex h-11 w-full items-center rounded-xl border border-input bg-background px-3 text-left text-sm transition hover:border-muted-foreground/50"><Briefcase className="mr-2 h-4 w-4 shrink-0 text-muted-foreground"/><span className="min-w-0 flex-1 truncate">{modeLabels.length?modeLabels.join(', '):'Cualquier modalidad'}</span><ChevronDown className={`ml-2 h-4 w-4 shrink-0 text-muted-foreground transition ${modeOpen?'rotate-180':''}`}/></button><Menu open={modeOpen}><button type="button" onClick={()=>setModes([])} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm hover:bg-muted"><Tick checked={modes.length===0}/><span>Cualquier modalidad</span></button>{MODES.map(([v,l])=><button type="button" key={v} onClick={()=>toggle(v,setModes)} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm hover:bg-muted"><Tick checked={modes.includes(v)}/><span>{l}</span></button>)}</Menu></div>
   </div>
   {(roles.length>0||regions.length>0||modes.length>0)&&<div className="flex flex-wrap items-center gap-2 border-t border-border/70 pt-4">{roles.map(v=><Chip key={`r-${v}`} label={v} onRemove={()=>setRoles(x=>x.filter(i=>i!==v))}/>)}{regions.map(v=><Chip key={`g-${v}`} label={v} onRemove={()=>setRegions(x=>x.filter(i=>i!==v))}/>)}{MODES.filter(([v])=>modes.includes(v)).map(([v,l])=><Chip key={v} label={l} onRemove={()=>setModes(x=>x.filter(i=>i!==v))}/>)}<button type="button" onClick={()=>{setRoles([]);setRegions([]);setModes([])}} className="ml-auto text-xs font-medium text-muted-foreground hover:text-foreground">Limpiar todo</button></div>}
   {message&&<p role="status" className="text-sm text-destructive">{message}</p>}
   <div className="flex justify-end"><Button disabled={saving} className="h-11 rounded-xl bg-[hsl(var(--dtc-indigo-900))] px-7 text-white shadow-sm hover:opacity-90"><Search className="mr-2 h-4 w-4"/>{saving?'Buscando…':'Buscar oportunidades'}</Button></div>
  </form></CardContent>
 </Card>
}
