// A2 90-Day Roadmap Configuration
// Each day unlocks sequentially after completion

export interface A2Day {
  dia: number
  title: string
  subtitle: string
  description: string
  phase: 'clarity' | 'material' | 'interview' | 'real-action' | 'refinement'
  unlocksA3Module: string | null // Which A3 module unlocks on this day
  tasks: string[]
  learningGoals: string[]
  actionItems: string[]
  notionTemplate: string
  estimatedHours: number
}

export const A2_DAYS: Record<number, A2Day> = {
  // Phase 1: Claridad (Días 1-10)
  1: {
    dia: 1,
    title: 'Define tu visión y roadmap',
    subtitle: 'Claridad total sobre qué quieres lograr',
    description: 'Crea una visión clara del rol que buscas, el ambiente ideal, y tu resultado deseado. Define 3 hitos en tu roadmap de 30 días.',
    phase: 'clarity',
    unlocksA3Module: null,
    tasks: ['Escribe tu visión profesional', 'Define 3 hitos (día 10, 20, 30)', 'Crea plan de acciones'],
    learningGoals: ['Entender tu dirección profesional', 'Definir éxito en 30 días'],
    actionItems: ['Guardar roadmap en Notion', 'Subir documento a DTC'],
    notionTemplate: 'https://notion.so/plantilla-dia-1',
    estimatedHours: 1.5
  },
  2: {
    dia: 2,
    title: 'Identifica tus fortalezas y bloques',
    subtitle: 'Diagnóstico profesional real',
    description: 'Realiza un análisis honesto de tus fortalezas actuales, experiencia transferible, y los bloques que te limitan en tu búsqueda.',
    phase: 'clarity',
    unlocksA3Module: null,
    tasks: ['Documentar 5 fortalezas clave', 'Identificar 3 bloques principales', 'Mapear experiencia transferible'],
    learningGoals: ['Autoconocimiento profesional', 'Identificar patrones de carrera'],
    actionItems: ['Crear matriz de fortalezas', 'Registrar en workbook'],
    notionTemplate: 'https://notion.so/plantilla-dia-2',
    estimatedHours: 1
  },
  3: {
    dia: 3,
    title: 'Investiga el mercado y rol objetivo',
    subtitle: 'Entiende el rol que buscas',
    description: 'Investigación profunda del rol objetivo: requisitos, salario, empresas, tendencias, variaciones. Construye tu compresión real del mercado.',
    phase: 'clarity',
    unlocksA3Module: 'rol-objetivo',
    tasks: ['Investigar 5 empresas objetivo', 'Leer 10 descripciones de rol', 'Mapear requisitos clave vs tuyo'],
    learningGoals: ['Entender dinámicas del mercado', 'Identificar gaps de preparación'],
    actionItems: ['Crear lista de empresas', 'Documentar requisitos pattern'],
    notionTemplate: 'https://notion.so/plantilla-dia-3',
    estimatedHours: 1.5
  },
  4: {
    dia: 4,
    title: 'Construye tu proposición de valor',
    subtitle: 'Por qué deberían contratarte',
    description: 'Define claramente qué valor único aportas. Crea 3-4 proposiciones para diferentes tipos de empresas. Sé específico y honesto.',
    phase: 'clarity',
    unlocksA3Module: null,
    tasks: ['Definir proposición 1 (startup)', 'Definir proposición 2 (empresa)', 'Crear pitch de 2 minutos'],
    learningGoals: ['Articular tu valor', 'Diferenciarte en el mercado'],
    actionItems: ['Escribir proposiciones', 'Practicar con mentor'],
    notionTemplate: 'https://notion.so/plantilla-dia-4',
    estimatedHours: 1
  },
  5: {
    dia: 5,
    title: 'Analiza tu competencia indirecta',
    subtitle: 'Quién más busca tu rol',
    description: 'Analiza perfiles de personas en roles similares: edad, experiencia, background, ubicación. Identifica patrones de contratación.',
    phase: 'clarity',
    unlocksA3Module: null,
    tasks: ['Analizar 20 perfiles en LinkedIn', 'Identificar 3 patrones comunes', 'Mapear diferencias contigo'],
    learningGoals: ['Entender el mercado competitivo', 'Identificar diferenciadores'],
    actionItems: ['Crear mapa competitivo', 'Actualizar perfil LinkedIn'],
    notionTemplate: 'https://notion.so/plantilla-dia-5',
    estimatedHours: 1
  },
  6: {
    dia: 6,
    title: 'Crea tu perfil de marca personal',
    subtitle: 'Tu presencia profesional online',
    description: 'Diseña cómo te verán las empresas. Define tu marca: qué eres, qué comunicas, cómo te posicionas. Cubre todos los canales.',
    phase: 'clarity',
    unlocksA3Module: 'marca-personal',
    tasks: ['Definir marca + pitch', 'Auditoria de presencia online', 'Plan de mejora integral'],
    learningGoals: ['Crear marca consistente', 'Optimizar presencia'],
    actionItems: ['Actualizar bio Twitter/LinkedIn', 'Crear resumen personal'],
    notionTemplate: 'https://notion.so/plantilla-dia-6',
    estimatedHours: 1.5
  },
  7: {
    dia: 7,
    title: 'Define estrategia de búsqueda activa',
    subtitle: 'Plan concreto para conectar',
    description: 'Crea tu estrategia de búsqueda: dónde buscar, a quién contactar, qué canales usar. Prioriza acción directa sobre postulaciones.',
    phase: 'clarity',
    unlocksA3Module: null,
    tasks: ['Identificar 50 personas relevantes', 'Mapear 10 empresas target', 'Definir canales de búsqueda'],
    learningGoals: ['Estrategia de networking', 'Acción directa vs pasiva'],
    actionItems: ['Crear lista de contactos', 'Planificar alcance diario'],
    notionTemplate: 'https://notion.so/plantilla-dia-7',
    estimatedHours: 1
  },
  8: {
    dia: 8,
    title: 'Prepara respuestas de entrevista base',
    subtitle: 'Estructura tus historias',
    description: 'Identifica las 5 preguntas más comunes y crea respuestas estructuradas. No memorices, aprende estructura. Practica storytelling profesional.',
    phase: 'clarity',
    unlocksA3Module: null,
    tasks: ['Crear respuesta para "Cuéntame de ti"', 'Preparar 3 historias de logros', 'Estructurar respuesta para debilidades'],
    learningGoals: ['Storytelling profesional', 'Gestionar narrativa'],
    actionItems: ['Escribir respuestas', 'Grabar videos practicando'],
    notionTemplate: 'https://notion.so/plantilla-dia-8',
    estimatedHours: 1.5
  },
  9: {
    dia: 9,
    title: 'Optimiza tu LinkedIn profesional',
    subtitle: 'Tu resume online debe brillar',
    description: 'Optimiza completamente tu perfil: foto, titular, resumen, experiencia, skills. Cada línea cuenta. Haz que sea atractivo y claro.',
    phase: 'clarity',
    unlocksA3Module: null,
    tasks: ['Mejorar foto de perfil', 'Reescribir titular con keywords', 'Actualizar resumen profesional'],
    learningGoals: ['SEO LinkedIn', 'Atracción de reclutadores'],
    actionItems: ['Publicar cambios', 'Solicitar endorsements'],
    notionTemplate: 'https://notion.so/plantilla-dia-9',
    estimatedHours: 1
  },
  10: {
    dia: 10,
    title: 'Checkpoint: Claridad profesional',
    subtitle: 'Tu comprensión del mercado es clara',
    description: 'Revisa todo lo construido: visión clara, fortalezas identificadas, mercado entendido, marca definida, estrategia lista. Cierra ciclo 1.',
    phase: 'clarity',
    unlocksA3Module: null,
    tasks: ['Revisar documento de claridad', 'Sesión de feedback con mentor', 'Ajustar si es necesario'],
    learningGoals: ['Integrar aprendizajes', 'Solidificar dirección'],
    actionItems: ['Actualizar roadmap general', 'Compartir avance'],
    notionTemplate: 'https://notion.so/plantilla-dia-10',
    estimatedHours: 1
  },

  // Phase 2: Material Profesional (Días 11-30)
  11: {
    dia: 11,
    title: 'Audita tu CV actual',
    subtitle: 'Línea base de donde estás',
    description: 'Análisis honesto de tu CV: qué funciona, qué no, qué falta. Compáralo con lo que el mercado busca. Identifica gaps.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Documento estructura CV', 'Identificar puntos débiles', 'Mapear cambios necesarios'],
    learningGoals: ['Entender expectativas de CV', 'Identificar poder de logros'],
    actionItems: ['Crear versión mejorada draft', 'Revisión de pares'],
    notionTemplate: 'https://notion.so/plantilla-dia-11',
    estimatedHours: 1
  },
  12: {
    dia: 12,
    title: 'Transforma experiencia en logros',
    subtitle: 'Los números y resultados cuentan',
    description: 'Convierte cada responsabilidad en logro medible. Usa formato STAR. Cuantifica impacto. Haz que cada línea brille con resultados concretos.',
    phase: 'material',
    unlocksA3Module: 'logros-medibles',
    tasks: ['Convertir 3 roles a logros', 'Cuantificar 5 resultados clave', 'Aplicar formato STAR'],
    learningGoals: ['Comunicar impacto', 'Storytelling cuantitativo'],
    actionItems: ['Actualizar CV con logros', 'Crear lista de stories'],
    notionTemplate: 'https://notion.so/plantilla-dia-12',
    estimatedHours: 1.5
  },
  13: {
    dia: 13,
    title: 'Crea tu CV versión 1.0 optimizado',
    subtitle: 'Documento profesional brillante',
    description: 'CV completo, optimizado, atractivo. Incluye: título fuerte, resumen de 2 líneas, experiencia con logros, skills relevantes, educación. Enfocado en tu rol objetivo.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Escribir CV version 1.0', 'Formato profesional', 'Optimizar para ATS'],
    learningGoals: ['CV que convierte', 'ATS optimization'],
    actionItems: ['Descargar en PDF', 'Pedir feedback'],
    notionTemplate: 'https://notion.so/plantilla-dia-13',
    estimatedHours: 1.5
  },
  14: {
    dia: 14,
    title: 'Documenta tus logros y proyectos clave',
    subtitle: 'Portfolio de impacto real',
    description: 'Lista de 8-10 logros principales con contexto, acciones, resultados. Prepáralos como historias para entrevistas. Cuantifica siempre.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Documentar 10 logros clave', 'Formato: Context-Action-Result', 'Crear worksheet de historias'],
    learningGoals: ['Narrativa de logros', 'Evidencia de impacto'],
    actionItems: ['Compartir historias en entrevista', 'Memorizar estructura'],
    notionTemplate: 'https://notion.so/plantilla-dia-14',
    estimatedHours: 1
  },
  15: {
    dia: 15,
    title: 'Construye tu portfolio profesional',
    subtitle: 'Demuestra lo que sabes hacer',
    description: 'Portfolio que muestre tu trabajo: proyectos completados, resultados, impacto. Puede ser: GitHub, Medium, Google Drive folder, sitio web. Lo importante es evidencia.',
    phase: 'material',
    unlocksA3Module: 'portafolio-digital',
    tasks: ['Seleccionar 5-7 proyectos clave', 'Documentar resultados de cada uno', 'Crear carpeta compartible'],
    learningGoals: ['Evidencia visual de impacto', 'Diferenciación'],
    actionItems: ['Crear portfolio link', 'Compartir en LinkedIn'],
    notionTemplate: 'https://notion.so/plantilla-dia-15',
    estimatedHours: 1.5
  },
  16: {
    dia: 16,
    title: 'Obtén recomendaciones profesionales',
    subtitle: 'Validación de terceros',
    description: 'Solicita recomendaciones en LinkedIn a personas clave: jefes, colegas, clientes. Mínimo 5-7. Pide que sean específicas sobre tus fortalezas.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Seleccionar 7 personas', 'Escribir requests personalizados', 'Seguimiento si es necesario'],
    learningGoals: ['Red de validación', 'Credibilidad externa'],
    actionItems: ['Enviar solicitudes personalizadas', 'Agradecer públicamente'],
    notionTemplate: 'https://notion.so/plantilla-dia-16',
    estimatedHours: 1
  },
  17: {
    dia: 17,
    title: 'Crea cover letter template',
    subtitle: 'Tu carta de presentación',
    description: 'Cover letter que sea flexible pero poderosa. Template que adaptes por empresa. Cuenta quién eres, por qué te interesa el rol, qué valor aportas. Máximo 200 palabras.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Escribir cover letter template', 'Crear versiones por tipo empresa', 'Practicar personalización'],
    learningGoals: ['Comunicación persuasiva', 'Adaptación por audiencia'],
    actionItems: ['Guardar templates por empresa', 'Feedback de pares'],
    notionTemplate: 'https://notion.so/plantilla-dia-17',
    estimatedHours: 1
  },
  18: {
    dia: 18,
    title: 'Prepara tu pitch de 2 minutos',
    subtitle: 'Tu introducción de elevator pitch',
    description: 'Pitch corto, poderoso, flexible. Incluye: quién eres, qué haces, rol que buscas, por qué, qué buscas. Grabaló, practícalo. Debe sonar natural.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Escribir pitch', 'Grabar video practicando', 'Ajustar timings'],
    learningGoals: ['Comunicación concisa', 'Confianza al hablar'],
    actionItems: ['Practicar diariamente', 'Pedir feedback'],
    notionTemplate: 'https://notion.so/plantilla-dia-18',
    estimatedHours: 1
  },
  19: {
    dia: 19,
    title: 'Crea resumen ejecutivo de tu carrera',
    subtitle: 'Tu história profesional resumida',
    description: 'Narrativa de tu carrera en 1 página: dónde empezaste, qué aprendiste, cómo evolucionaste, dónde estás, hacia dónde vas. Coherente y progresiva.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Escribir narrativa de carrera', 'Conectar puntos lógicamente', 'Mostrar progresión'],
    learningGoals: ['Coherencia de carrera', 'Narrativa personal'],
    actionItems: ['Usar en entrevistas', 'Compartir con networking'],
    notionTemplate: 'https://notion.so/plantilla-dia-19',
    estimatedHours: 1
  },
  20: {
    dia: 20,
    title: 'Checkpoint: Material profesional base',
    subtitle: 'Tu presentación profesional está lista',
    description: 'CV optimizado, cover letter, pitch, recomendaciones, portfolio. Todo lo necesario para postularte. Revisa calidad y consistencia de mensajes.',
    phase: 'material',
    unlocksA3Module: 'presentacion-profesional',
    tasks: ['Revisar todos los documentos', 'Feedback externo', 'Ajustes finales'],
    learningGoals: ['Integración de material', 'Coherencia de marca'],
    actionItems: ['Archivar versiones finales', 'Compartir con mentores'],
    notionTemplate: 'https://notion.so/plantilla-dia-20',
    estimatedHours: 1
  },
  21: {
    dia: 21,
    title: 'Estructura tus respuestas de entrevista',
    subtitle: 'Historias y respuestas preparadas',
    description: 'Crea worksheet con 10-15 respuestas a preguntas comunes. Formato: Pregunta - Respuesta estructura - Ejemplos reales. No memorizar, internalizar estructura.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Crear 15 respuestas base', 'Agregar ejemplos de historias', 'Practicar fluidez'],
    learningGoals: ['Preparación estructurada', 'Flexibilidad en respuestas'],
    actionItems: ['Grabar práctica', 'Sesión mock interview'],
    notionTemplate: 'https://notion.so/plantilla-dia-21',
    estimatedHours: 1.5
  },
  22: {
    dia: 22,
    title: 'Prepara preguntas para entrevistadores',
    subtitle: 'Lidera la conversación',
    description: 'Lista de 10-15 preguntas inteligentes que hagas: sobre el rol, equipo, cultura, métricas de éxito, desafíos, crecimiento. Muestra interés real.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Crear 15 preguntas inteligentes', 'Adaptarlas por tipo empresa', 'Practicar flujo'],
    learningGoals: ['Due diligence', 'Evaluación de oportunidad'],
    actionItems: ['Usar en mock interviews', 'Ajustar según feedback'],
    notionTemplate: 'https://notion.so/plantilla-dia-22',
    estimatedHours: 1
  },
  23: {
    dia: 23,
    title: 'Crea tu "desafío para resolver"',
    subtitle: 'Muestra lo que sabes hacer',
    description: 'Documento o proyecto que demuestre habilidades clave. Puede ser: análisis, propuesta, solución a caso real. Algo que puedas mostrar si te lo piden.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Seleccionar caso/desafío', 'Crear solución', 'Documentar proceso'],
    learningGoals: ['Demostración práctica', 'Pensamiento crítico'],
    actionItems: ['Guardar en portfolio', 'Mostrar en entrevistas'],
    notionTemplate: 'https://notion.so/plantilla-dia-23',
    estimatedHours: 1.5
  },
  24: {
    dia: 24,
    title: 'Prepara tus referencias profesionales',
    subtitle: 'Validación de terceros lista',
    description: '3-5 referencias profesionales confirmadas. Jefes, colegas, clientes. Asegúrate que hablen bien de ti y sepan qué tipo de rol buscas.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Confirmar con 5 referencias', 'Compartir tu CV y rol objetivo', 'Practicar cómo van a hablar de ti'],
    learningGoals: ['Red de validación', 'Control de narrativa'],
    actionItems: ['Contacto previo a entrevista', 'Brief si es necesario'],
    notionTemplate: 'https://notion.so/plantilla-dia-24',
    estimatedHours: 1
  },
  25: {
    dia: 25,
    title: 'Crea tu perfil de empresa ideal',
    subtitle: 'Qué tipo de empresa buscas',
    description: 'Define con precisión: tamaño, industria, cultura, ubicación, crecimiento, compensación. Esto te ayuda a filtrar oportunidades y preparar targeting.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Definir 5 características de empresa ideal', 'Crear criterios de evaluación', 'Listar 20 empresas que cumplan'],
    learningGoals: ['Claridad de oportunidad', 'Evaluación de fit'],
    actionItems: ['Priorizar empresas', 'Investigar cada una'],
    notionTemplate: 'https://notion.so/plantilla-dia-25',
    estimatedHours: 1
  },
  26: {
    dia: 26,
    title: 'Analiza beneficios y compensación',
    subtitle: 'Entiende tu valor de mercado',
    description: 'Investigación: salario promedio para tu rol, beneficios estándares, negociación típica. Entiende tu poder de negociación y límites.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Investigar 20 salarios para tu rol', 'Benchmarking de beneficios', 'Determinar tu rango'],
    learningGoals: ['Valor de mercado', 'Negociación informada'],
    actionItems: ['Fijar rango mínimo', 'Practicar negociación'],
    notionTemplate: 'https://notion.so/plantilla-dia-26',
    estimatedHours: 1
  },
  27: {
    dia: 27,
    title: 'Crea plantilla para seguimiento de postulaciones',
    subtitle: 'Tracking de tu proceso',
    description: 'Worksheet para seguir: empresa, rol, fecha postulación, status, contacto, próximo paso. Básico pero efectivo para no olvidar nada.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Crear plantilla de tracking', 'Campos: empresa, rol, fecha, status', 'Establecer rutina de actualización'],
    learningGoals: ['Organización de proceso', 'Follow-up sistemático'],
    actionItems: ['Empezar a registrar', 'Revisar diariamente'],
    notionTemplate: 'https://notion.so/plantilla-dia-27',
    estimatedHours: 0.5
  },
  28: {
    dia: 28,
    title: 'Prepare videos de presentación',
    subtitle: 'Contenido visual para reclutadores',
    description: 'Crea 1-3 videos cortos (30-60 seg): intro, resumen de carrera, por qué buscas cambio. Profesionales pero auténticos. Subir a LinkedIn.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Grabar video de introducción', 'Grabar video de motivación', 'Editar básicamente'],
    learningGoals: ['Presencia video', 'Diferenciación'],
    actionItems: ['Subir a LinkedIn', 'Compartir en networking'],
    notionTemplate: 'https://notion.so/plantilla-dia-28',
    estimatedHours: 1
  },
  29: {
    dia: 29,
    title: 'Revisa y actualiza todo tu material',
    subtitle: 'Pulir antes de la acción',
    description: 'Última revisión: CV, cover letter, pitch, respuestas, preguntas, portfolio. Todo debe estar alineado, consistente, pulido y listo.',
    phase: 'material',
    unlocksA3Module: null,
    tasks: ['Revisar toda documentación', 'Pedir feedback final', 'Hacer ajustes'],
    learningGoals: ['Calidad final', 'Atención a detalles'],
    actionItems: ['Archivar versiones finales', 'Estar 100% listo'],
    notionTemplate: 'https://notion.so/plantilla-dia-29',
    estimatedHours: 1
  },
  30: {
    dia: 30,
    title: 'Checkpoint: Material + Preparación completa',
    subtitle: 'Día 30 - Estás completamente listo',
    description: 'Revisión final de TODO: material, respuestas, preguntas, referencias, tracking. Estás listo para fase de acción real. Celebra progreso.',
    phase: 'material',
    unlocksA3Module: 'material-completo',
    tasks: ['Revisión completa final', 'Sesión de checkpoint con mentor', 'Planificar semanas 5-6'],
    learningGoals: ['Integración de aprendizajes', 'Confianza para acción'],
    actionItems: ['Preparar para búsqueda activa', 'Actualizar calendario'],
    notionTemplate: 'https://notion.so/plantilla-dia-30',
    estimatedHours: 1.5
  },

  // Phase 3: Acción Real e Interviews (Días 31-60)
  31: {
    dia: 31,
    title: 'Inicia búsqueda activa - Networking directo',
    subtitle: 'Comienza a conectar con personas',
    description: 'Primera semana de acción: identifica 50 personas relevantes, conecta con 20, inicia conversaciones genuinas. Networking > postulaciones.',
    phase: 'real-action',
    unlocksA3Module: 'busqueda-activa',
    tasks: ['Identificar 50 personas relevantes', 'Conectar con 20 en LinkedIn', 'Enviar mensajes personalizados'],
    learningGoals: ['Networking activo', 'Conexiones auténticas'],
    actionItems: ['Mantener CRM de contactos', 'Seguimiento sistemático'],
    notionTemplate: 'https://notion.so/plantilla-dia-31',
    estimatedHours: 2
  },
  32: {
    dia: 32,
    title: 'Postúlate a 10+ oportunidades',
    subtitle: 'Volumen estratégico',
    description: 'Postúlate a mínimo 10 roles que match tu perfil. Usa CV y cover letter optimizados. Registra en tracking. Combina: postulación + contacto directo.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Postularte a 10-15 roles', 'Personalizar cada aplicación', 'Contactar directamente a hiring manager'],
    learningGoals: ['Volumen de acción', 'Persistencia'],
    actionItems: ['Registrar en tracking', 'Seguimiento x 48h'],
    notionTemplate: 'https://notion.so/plantilla-dia-32',
    estimatedHours: 2
  },
  33: {
    dia: 33,
    title: 'Primera mock interview',
    subtitle: 'Práctica con feedback real',
    description: 'Sesión con mentor o coach: 30-45 min simulando entrevista real. Preguntas inesperadas, presión, evaluación de respuestas. Feedback honesto.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Sesión mock interview', 'Recibir feedback', 'Ajustar respuestas'],
    learningGoals: ['Manejo de presión', 'Mejora en tiempo real'],
    actionItems: ['Registrar puntos débiles', 'Practicar esos puntos'],
    notionTemplate: 'https://notion.so/plantilla-dia-33',
    estimatedHours: 1
  },
  34: {
    dia: 34,
    title: 'Preparación intensiva para entrevista',
    subtitle: 'Semana de práctica antes del primer call',
    description: 'Si tienes entrevista programada, prepárate intensivamente. Si no, practica igual como si la tuvieras. Grabate, mejora constantemente.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Investigar empresa a fondo', 'Practicar respuestas específicas', 'Preparar contrapreguntas'],
    learningGoals: ['Dominio de contenido', 'Confianza ante específico'],
    actionItems: ['Dormir bien antes', 'Mantener calma'],
    notionTemplate: 'https://notion.so/plantilla-dia-34',
    estimatedHours: 2
  },
  35: {
    dia: 35,
    title: 'Primera entrevista real o video screening',
    subtitle: 'Tu primer contacto con empresa',
    description: 'Primera entrevista de verdad. Video screening o teléfono. Aplica todo lo aprendido. Toma notas durante. Después, documenta lo que pasó.',
    phase: 'real-action',
    unlocksA3Module: 'primera-entrevista',
    tasks: ['Participar en entrevista', 'Tomar notas', 'Seguimiento x 24h'],
    learningGoals: ['Experiencia real', 'Aprendizaje de cada interview'],
    actionItems: ['Enviar thank you', 'Analizar cómo fue'],
    notionTemplate: 'https://notion.so/plantilla-dia-35',
    estimatedHours: 1
  },
  36: {
    dia: 36,
    title: 'Análisis de entrevistas - Que funciona',
    subtitle: 'Aprender de la experiencia',
    description: 'Documenta qué pasó en la entrevista: preguntas que te hicieron, cómo respondiste, qué funcionó, qué mejorar. Ajusta para próximas.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Documentar detalles de entrevista', 'Identificar puntos débiles', 'Ajustar respuestas'],
    learningGoals: ['Aprendizaje iterativo', 'Mejora continua'],
    actionItems: ['Actualizar worksheet', 'Practicar áreas débiles'],
    notionTemplate: 'https://notion.so/plantilla-dia-36',
    estimatedHours: 1
  },
  37: {
    dia: 37,
    title: 'Intensifica networking - 2da ronda',
    subtitle: 'Expande tu círculo',
    description: 'Segunda ronda de networking: contacta 20 personas más, profundiza con las primeras 20. Busca referrals y recomendaciones. Calidad sobre cantidad.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Conectar con 20 personas más', 'Profundizar con primeras 20', 'Pedir recomendaciones'],
    learningGoals: ['Red de conexiones', 'Influencia indirecta'],
    actionItems: ['Follow-up sistemático', 'Ofrecer valor primero'],
    notionTemplate: 'https://notion.so/plantilla-dia-37',
    estimatedHours: 2
  },
  38: {
    dia: 38,
    title: 'Segunda ronda de postulaciones masivas',
    subtitle: 'Más volumen, más posibilidades',
    description: 'Postúlate a 15-20 más roles. Sigue siendo selectivo pero agresivo. Ajusta CV/cover letter basado en feedback de primera ronda.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Postularte a 15-20 roles', 'Contacto directo a recruiters', 'Tracking sistemático'],
    learningGoals: ['Volumen de acción', 'Refinamiento de targeting'],
    actionItems: ['Análisis de conversión', 'Optimizar pitch'],
    notionTemplate: 'https://notion.so/plantilla-dia-38',
    estimatedHours: 2
  },
  39: {
    dia: 39,
    title: '2da mock interview - Más difícil',
    subtitle: 'Simulación de 2do round',
    description: 'Segunda mock interview, esta vez más desafiante: preguntas técnicas, situacionales complejas, feedback duro. Prepárate para lo real.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Mock interview avanzado', 'Feedback profundo', 'Ajustes mayores'],
    learningGoals: ['Preparación para later rounds', 'Confianza bajo presión'],
    actionItems: ['Practicar weaknesses identificados', 'Mejorar antes de real'],
    notionTemplate: 'https://notion.so/plantilla-dia-39',
    estimatedHours: 1
  },
  40: {
    dia: 40,
    title: 'Checkpoint: Acción es real, entrevistas vienen',
    subtitle: 'Ves movimiento de verdad',
    description: 'Revisión de semana 5-6: ¿cuántas entrevistas tienes? ¿cuántas postulaciones? ¿feedback? Ajusta estrategia si es necesario. Mantén momentum.',
    phase: 'real-action',
    unlocksA3Module: 'accion-real-iniciada',
    tasks: ['Revisar métrica de acción', 'Sesión de estrategia', 'Ajustar si falta momentum'],
    learningGoals: ['Métricas de éxito', 'Adaptación estratégica'],
    actionItems: ['Intensificar si falta movimiento', 'Mantener confianza'],
    notionTemplate: 'https://notion.so/plantilla-dia-40',
    estimatedHours: 1
  },
  41: {
    dia: 41,
    title: 'Manejo de rechazo y feedback',
    subtitle: 'No todos dicen sí, y está bien',
    description: 'Algunas entrevistas no avanzan. Eso es normal. Solicita feedback cuando sea posible. Documenta patrones. Aprende. No desistes.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Solicitar feedback en rechazo', 'Documentar patrones', 'Ajustar si hay patrón'],
    learningGoals: ['Resiliencia', 'Aprendizaje de fracaso'],
    actionItems: ['Mantener perspectiva', 'Seguir actuando'],
    notionTemplate: 'https://notion.so/plantilla-dia-41',
    estimatedHours: 1
  },
  42: {
    dia: 42,
    title: 'Seguimiento estratégico de candidaturas',
    subtitle: 'No esperes, recuerda que existes',
    description: 'Sistemas de seguimiento: con qué empresas ya hablaste, a cuáles debes hacer follow-up, a cuáles contactar de nuevo. Sé persistente pero respetuoso.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Crear sistema de follow-up', 'Contactar empresas en pausa', 'Personalizar cada follow-up'],
    learningGoals: ['Persistencia estratégica', 'CRM personal'],
    actionItems: ['Actualizaciones diarias', 'Recordatorios automáticos'],
    notionTemplate: 'https://notion.so/plantilla-dia-42',
    estimatedHours: 1
  },
  43: {
    dia: 43,
    title: 'Tercera ronda de networking + postulaciones',
    subtitle: 'Sigue expandiendo el funnel',
    description: 'Networking y postulaciones son tu pan diario ahora. Conecta 30 personas más. Postúlate a 20+ roles. El volumen es key.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Conectar con 30 personas más', 'Postularse a 20 roles', 'Contacto directo a 10 hiring managers'],
    learningGoals: ['Consistencia de acción', 'Escalabilidad del funnel'],
    actionItems: ['Automatizar parte del proceso', 'Mantener autenticidad'],
    notionTemplate: 'https://notion.so/plantilla-dia-43',
    estimatedHours: 2
  },
  44: {
    dia: 44,
    title: 'Preparación para "second round" interviews',
    subtitle: 'Ya pasó la primera ronda',
    description: 'Si tienes 2do round programado, prepárate específicamente: preguntas por ese nivel, demostrar profundidad, preparar contrapreguntas avanzadas.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Investigación profunda de empresa', 'Preparar para preguntas técnicas', 'Prácticas de caso'],
    learningGoals: ['Preparación para later stages', 'Demostración de profundidad'],
    actionItems: ['Sesión final antes de entrevista', 'Confianza en lo que sabes'],
    notionTemplate: 'https://notion.so/plantilla-dia-44',
    estimatedHours: 1.5
  },
  45: {
    dia: 45,
    title: 'Participación en múltiples entrevistas',
    subtitle: 'Semana intensa de procesos',
    description: 'Esta semana probablemente tengas 3-5 entrevistas con diferentes empresas. Manejo de múltiples procesos. Toma notas. Mantén tracking.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Participar en 3-5 entrevistas', 'Tomar notas de cada una', 'Seguimiento post-interview'],
    learningGoals: ['Manejo de múltiples procesos', 'Gestión de tiempo'],
    actionItems: ['Tracking actualizado', 'Descanso entre entrevistas'],
    notionTemplate: 'https://notion.so/plantilla-dia-45',
    estimatedHours: 2
  },
  46: {
    dia: 46,
    title: 'Análisis de progreso - ¿dónde estás?',
    subtitle: 'Revisión de mitad de camino',
    description: 'Estás en día 46 de 90. ¿Progreso? ¿ Oferta cercana? ¿Múltiples procesos avanzados? Si sí, aceleración. Si no, intensificar acción.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Análisis de funil de candidaturas', 'Revisión de conversión', 'Decisión de intensificación'],
    learningGoals: ['Evaluación objetiva', 'Ajuste de estrategia'],
    actionItems: ['Reunión con mentor', 'Planificar próximas 2 semanas'],
    notionTemplate: 'https://notion.so/plantilla-dia-46',
    estimatedHours: 1
  },
  47: {
    dia: 47,
    title: 'Preparación para negociación',
    subtitle: 'Por si viene oferta pronto',
    description: 'Cuando venga oferta, quieres estar listo. Prepara: tu rango salarial mínimo/ideal, beneficios no-negociables, preguntas sobre compensación variable.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Definir rango salarial', 'Listar beneficios que importan', 'Preparar estrategia de negociación'],
    learningGoals: ['Conocimiento de tu valor', 'Confianza en negociación'],
    actionItems: ['Revisar market rates', 'Practicar conversación'],
    notionTemplate: 'https://notion.so/plantilla-dia-47',
    estimatedHours: 1
  },
  48: {
    dia: 48,
    title: 'Cuarta ronda de acción agresiva',
    subtitle: 'Escalation final antes de cierre',
    description: 'Si aún sin oferta, escalación: networking con 50 personas, postulaciones a 30 roles. Sé visible. Sea el que todos conocen buscando rol.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Networking masivo: 50 personas', 'Postularse a 30 roles', 'Contacto directo a 15 recruiters'],
    learningGoals: ['Visibilidad de mercado', 'Saturación positiva del funnel'],
    actionItems: ['Publicar actualizaciones en LinkedIn', 'Mencionar búsqueda activa'],
    notionTemplate: 'https://notion.so/plantilla-dia-48',
    estimatedHours: 2
  },
  49: {
    dia: 49,
    title: 'Refinamiento final de propuesta de valor',
    subtitle: 'Ajusta mensaje basado en feedback',
    description: 'Basado en todas las entrevistas, feedback de networking, refina tu propuesta de valor. ¿Qué es lo que resonó? Amplifica eso.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Analizar feedback de entrevistas', 'Identificar qué resonó', 'Actualizar pitch y CV'],
    learningGoals: ['Market-driven iteration', 'Optimización de mensaje'],
    actionItems: ['Nuevo CV v2.0', 'Actualizar LinkedIn'],
    notionTemplate: 'https://notion.so/plantilla-dia-49',
    estimatedHours: 1
  },
  50: {
    dia: 50,
    title: 'Checkpoint: Semana 8 - Acción consistente',
    subtitle: 'Día 50 de 90 - Seguimos en la lucha',
    description: 'Mitad de la jornada. Revisar: ¿cómo va el funil? ¿ofertas en la mesa? ¿múltiples procesos avanzados? Ajusta roadmap para últimas 6 semanas.',
    phase: 'real-action',
    unlocksA3Module: 'semana-8-checkpoint',
    tasks: ['Revisión completa de progreso', 'Sesión con mentor o coach', 'Planificación finales 6 semanas'],
    learningGoals: ['Evaluación de trayectoria', 'Ajuste de tácticas'],
    actionItems: ['Determinar próximas prioridades', 'Mantener o intensificar'],
    notionTemplate: 'https://notion.so/plantilla-dia-50',
    estimatedHours: 1.5
  },
  51: {
    dia: 51,
    title: 'Deep dive en empresa(s) con proceso avanzado',
    subtitle: 'Prepárate para la recta final',
    description: 'Si tienes proceso avanzado, investiga profundamente: equipo, productos, estrategia, competencia, cultura. Prepárate como si fuese tu trabajo ya.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Investigación profunda de empresa', 'Análisis de competencia', 'Preparar insight para entrevistas'],
    learningGoals: ['Demostración de interés genuino', 'Preparación de expert'],
    actionItems: ['Tomar notas de insights', 'Preparar preguntas inteligentes'],
    notionTemplate: 'https://notion.so/plantilla-dia-51',
    estimatedHours: 1
  },
  52: {
    dia: 52,
    title: 'Última ronda de entrevistas hard',
    subtitle: 'Final rounds',
    description: 'Si llegas aquí, probablemente tienes final interview con alguien senior. Máxima preparación. Muestra que QUIERES ese rol. Lidera la conversación.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Preparación intensiva final', 'Mock interview final', 'Descanso mental'],
    learningGoals: ['Excelencia en presión máxima', 'Cierre de venta'],
    actionItems: ['Dormir bien', 'Llegar temprano'],
    notionTemplate: 'https://notion.so/plantilla-dia-52',
    estimatedHours: 1
  },
  53: {
    dia: 53,
    title: 'Oferta negoción y decisión',
    subtitle: 'Posible cierre',
    description: 'Si recibes oferta, negocia smart. Si no, sigue en acción. Ambos son OK. Una oferta puede llegar en cualquier momento en los próximos 40 días.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Negocia si hay oferta', 'Sigue en acción si no hay', 'Toma decisión informada'],
    learningGoals: ['Negociación efectiva', 'Discernimiento en oferta'],
    actionItems: ['Consulta con mentores', 'Revisa contrato'],
    notionTemplate: 'https://notion.so/plantilla-dia-53',
    estimatedHours: 1
  },
  54: {
    dia: 54,
    title: 'Mantén el momentum - 5ta ronda de acción',
    subtitle: 'No bajes la guardia',
    description: 'Incluso con oferta en negociación o procesos avanzados, sigue aplicando. Networking continuo. Esto diversifica tu riesgo y mantiene opciones abiertas.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Networking continuo', 'Postularse a 15+ roles', 'Keep múltiples opciones'],
    learningGoals: ['Mantenimiento de poder de negociación', 'Opciones abiertas'],
    actionItems: ['Seguimiento estratégico', 'Mantenimiento de ofertas vivas'],
    notionTemplate: 'https://notion.so/plantilla-dia-54',
    estimatedHours: 2
  },
  55: {
    dia: 55,
    title: 'Decisión y aceptación de rol',
    subtitle: 'El momento',
    description: 'Si tienes oferta que suena bien, acepta. Si tienes múltiples, compara usando matriz que definiste. Toma decisión. Notifica a otras empresas.',
    phase: 'real-action',
    unlocksA3Module: 'oferta-aceptada',
    tasks: ['Comparar ofertas si aplica', 'Tomar decisión final', 'Aceptar/declinar'],
    learningGoals: ['Decisión alineada con valores', 'Cierre de ciclo'],
    actionItems: ['Notificar a otras empresas', 'Iniciar onboarding'],
    notionTemplate: 'https://notion.so/plantilla-dia-55',
    estimatedHours: 1
  },
  56: {
    dia: 56,
    title: 'Post-oferta: Preparación para start',
    subtitle: 'Transición y onboarding',
    description: 'Antes de start, prepárate: preguntas para primer día, investigación final de cultura, preparación mental, despedidas en empleo anterior si aplica.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Preparar preguntas para onboarding', 'Investigación final de cultura', 'Preparación mental/material'],
    learningGoals: ['Preparación para nuevo rol', 'Transición suave'],
    actionItems: ['Conectar con futuros colegas', 'Descansar antes'],
    notionTemplate: 'https://notion.so/plantilla-dia-56',
    estimatedHours: 1
  },
  57: {
    dia: 57,
    title: 'Primer día en nuevo rol',
    subtitle: 'Day 1',
    description: 'Primer día. Absorbe. Escucha más que hablas. Toma notas. Conoce a la gente. Introduce el ritmo. Observa cultura real.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Primer día', 'Conocer equipo', 'Setup de workspace'],
    learningGoals: ['Observación de cultura', 'Integración inicial'],
    actionItems: ['Tomar notas', 'Almuerzo con colegas'],
    notionTemplate: 'https://notion.so/plantilla-dia-57',
    estimatedHours: 0.5
  },
  58: {
    dia: 58,
    title: 'Primera semana - Aprender y adaptarse',
    subtitle: 'Semana 1 en nuevo rol',
    description: 'Primera semana completa. Focus: aprender cómo funciona todo, conocer a la gente, entender procesos, empezar a generar ideas.',
    phase: 'real-action',
    unlocksA3Module: null,
    tasks: ['Onboarding completo', 'Reuniones 1:1 con colegas', 'Entender procesos clave'],
    learningGoals: ['Integración rápida', 'Comprensión de contexto'],
    actionItems: ['Hacer preguntas', 'Documentar procesos'],
    notionTemplate: 'https://notion.so/plantilla-dia-58',
    estimatedHours: 1
  },
  59: {
    dia: 59,
    title: 'Checkpoint: Has llegado - Reflexión',
    subtitle: 'Día 59 de 90 - Celebra el logro',
    description: 'Lo hiciste. Entraste en un rol nuevo. Ya sea que empezaste el nuevo rol o estés en últimas rondas de negociación, refleja. Has avanzado enormemente.',
    phase: 'real-action',
    unlocksA3Module: 'nuevo-rol-iniciado',
    tasks: ['Reflexión de jornada 90 días', 'Documentar lecciones', 'Celebrar logros'],
    learningGoals: ['Cierre de ciclo', 'Reconocimiento de progreso'],
    actionItems: ['Compartir experiencia', 'Mentorear a otros'],
    notionTemplate: 'https://notion.so/plantilla-dia-59',
    estimatedHours: 1
  },
  60: {
    dia: 60,
    title: 'Final: 60 días - Punto de partida nuevo',
    subtitle: 'Día 60 - Final de Fase Acción',
    description: 'Independientemente de si tienes oferta aceptada o estás en búsqueda activa intensiva, has completado 60 días de trabajo real. Ya no eres el mismo.',
    phase: 'real-action',
    unlocksA3Module: 'fase-accion-completa',
    tasks: ['Documentar todo lo aprendido', 'Crear resumen de 60 días', 'Planificar próximos 30'],
    learningGoals: ['Integración de aprendizajes', 'Preparación para próxima fase'],
    actionItems: ['Sesión final con mentor', 'Preparar planes de refuerzo'],
    notionTemplate: 'https://notion.so/plantilla-dia-60',
    estimatedHours: 1
  },

  // Phase 4: Refinement & Execution (Días 61-90)
  61: {
    dia: 61,
    title: 'Solidificación en nuevo rol - Week 1',
    subtitle: 'Construye credibilidad en primer mes',
    description: 'Segunda semana en nuevo rol. Empieza a hacer contribuciones. Construye relaciones. Demuestra tu valor. Pide feedback regularmente.',
    phase: 'refinement',
    unlocksA3Module: 'solidificacion-inicial',
    tasks: ['Completar onboarding', 'Primera contribución significativa', 'Feedback 1:1 con jefe'],
    learningGoals: ['Generación de valor rápido', 'Integración cultural'],
    actionItems: ['Identificar quick wins', 'Establecer rutinas'],
    notionTemplate: 'https://notion.so/plantilla-dia-61',
    estimatedHours: 1
  },
  62: {
    dia: 62,
    title: 'Personal Branding - Document tu jornada',
    subtitle: 'Comunica tu éxito',
    description: 'Comparte tu experiencia de 60 días: qué aprendiste, cómo te preparaste, lecciones clave. Post en LinkedIn. Ayuda a otros. Construye credibilidad como experto.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Escribir artículo sobre jornada', 'Publicar en LinkedIn', 'Mentorear a 1-2 personas'],
    learningGoals: ['Personal branding', 'Thought leadership'],
    actionItems: ['Engagement con comunidad', 'Networking continuado'],
    notionTemplate: 'https://notion.so/plantilla-dia-62',
    estimatedHours: 1.5
  },
  63: {
    dia: 63,
    title: 'Estrategia de crecimiento en nuevo rol',
    subtitle: 'Mapeo de oportunidades internas',
    description: 'Después de mes en rol, mapea: oportunidades de crecimiento, proyectos clave, personas influyentes, caminos a siguiente level. Planifica movimientos.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Mapear oportunidades de crecimiento', 'Identificar proyectos clave', 'Planificar siguiente 6-12 meses'],
    learningGoals: ['Visión de carrera interna', 'Planificación de crecimiento'],
    actionItems: ['Conversación de desarrollo con jefe', 'Identificar mentores internos'],
    notionTemplate: 'https://notion.so/plantilla-dia-63',
    estimatedHours: 1
  },
  64: {
    dia: 64,
    title: 'Master primera gran tarea/proyecto',
    subtitle: 'Demuestra valor',
    description: 'Identifica proyecto importante. Ejecútalo excelentemente. Esto construye reputación. Documenta aprendizajes. Esto es tu platform.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Asumir proyecto significativo', 'Execución excelente', 'Documentar resultados'],
    learningGoals: ['Execución de alto impacto', 'Construcción de reputación'],
    actionItems: ['Compartir resultados', 'Reconocimiento de equipo'],
    notionTemplate: 'https://notion.so/plantilla-dia-64',
    estimatedHours: 2
  },
  65: {
    dia: 65,
    title: 'Red interna - Construye alliances',
    subtitle: 'Networking dentro de empresa',
    description: 'No solo haz tu trabajo. Construye relaciones estratégicas dentro: mentores, pares en otras áreas, líderes. Networking interno es clave para crecimiento.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Almuerzo/café con 5 personas clave', 'Identificar mentores potenciales', 'Ofrecer ayuda a otros'],
    learningGoals: ['Networking interno', 'Influencia lateral'],
    actionItems: ['Crear círculo de mentoría', 'Seguimiento regular'],
    notionTemplate: 'https://notion.so/plantilla-dia-65',
    estimatedHours: 1
  },
  66: {
    dia: 66,
    title: 'Feedback continuo - Actualiza tu desempeño',
    subtitle: 'Mejora iterativa basada en feedback',
    description: 'Busca feedback constantemente. De jefe, pares, reportes si los tienes. Identifica áreas de mejora. Actúa sobre ellas. Esto acelerará tu crecimiento.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Solicitar feedback a 3 personas', 'Documentar áreas de mejora', 'Crear plan de mejora'],
    learningGoals: ['Aprendizaje continuo', 'Adaptabilidad'],
    actionItems: ['Check-in mensual sobre progreso', 'Ajustar si es necesario'],
    notionTemplate: 'https://notion.so/plantilla-dia-66',
    estimatedHours: 1
  },
  67: {
    dia: 67,
    title: 'Visible en empresa - Comparte tu trabajo',
    subtitle: 'Sé conocido por tu valor',
    description: 'Presenta tu trabajo en reuniones. Contribuye en discusiones. Participa en eventos. Hazte visible. La visibilidad es importante para crecimiento.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Presentar en meeting de equipo', 'Participar en iniciativa cross-functional', 'Hablar en town hall si aplica'],
    learningGoals: ['Visibilidad organizacional', 'Leadership comunicacional'],
    actionItems: ['Practicar presentaciones', 'Construir confianza en comunicación'],
    notionTemplate: 'https://notion.so/plantilla-dia-67',
    estimatedHours: 1
  },
  68: {
    dia: 68,
    title: 'Desarrollo de skills - Plan 6 meses',
    subtitle: 'Qué quieres aprender',
    description: 'Basado en feedback y rol, identifica skills a desarrollar. Crea plan: cursos, proyectos, mentorship. Comienza hoy. Esto es para diferenciación.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Identificar skills a desarrollar', 'Crear plan de aprendizaje', 'Comenzar cursos/proyectos'],
    learningGoals: ['Aprendizaje continuo estratégico', 'Diferenciación skill-based'],
    actionItems: ['Registrar en cursos', 'Dedicar 5 horas/semana'],
    notionTemplate: 'https://notion.so/plantilla-dia-68',
    estimatedHours: 1.5
  },
  69: {
    dia: 69,
    title: 'Checkpoint: 69 días - Integración completa',
    subtitle: 'Ya eres parte del equipo',
    description: 'Dos meses en nuevo rol. Ya no eres nuevo. Has contribuido. Tienes relaciones. Conoces cómo funciona. Celebra y prepárate para next phase.',
    phase: 'refinement',
    unlocksA3Module: 'integracion-completa',
    tasks: ['Reflexión de primeros 2 meses', 'Revisión de contribuciones', 'Planificación de próximos 3 meses'],
    learningGoals: ['Reconocimiento de integración', 'Preparación para crecimiento acelerado'],
    actionItems: ['Sesión con jefe sobre trayectoria', 'Actualizar objetivos de desarrollo'],
    notionTemplate: 'https://notion.so/plantilla-dia-69',
    estimatedHours: 1
  },
  70: {
    dia: 70,
    title: 'Liderazgo emergente - Empieza a liderar',
    subtitle: 'De contributor a multiplicador',
    description: 'Comienza a liderar: un proyecto pequeño, mentoría de junior, facilitación de iniciativa. Multiplica tu impacto a través de otros.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Asumir liderazgo de proyecto', 'Mentorear a 1 persona', 'Facilitar iniciativa cruzada'],
    learningGoals: ['Liderazgo emergente', 'Multiplicación de impacto'],
    actionItems: ['Practicar skills de leadership', 'Feedback sobre liderazgo'],
    notionTemplate: 'https://notion.so/plantilla-dia-70',
    estimatedHours: 1
  },
  71: {
    dia: 71,
    title: 'Expande rol - Busca responsabilidades más',
    subtitle: 'Crecimiento acelerado',
    description: 'Una vez solidificado, expande: proyectos mayores, más responsabilidad, scope mayor. Esto acelera tu crecimiento y comprobación de valor.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Identificar proyecto más grande', 'Proponer expansión de rol', 'Asumir nuevas responsabilidades'],
    learningGoals: ['Crecimiento acelerado', 'Demostración de ambición'],
    actionItems: ['Conversación con jefe', 'Planificación de escalación'],
    notionTemplate: 'https://notion.so/plantilla-dia-71',
    estimatedHours: 1
  },
  72: {
    dia: 72,
    title: 'Impacto visible - Resultados concretos',
    subtitle: 'Números y logros que hablen',
    description: 'Documenta impacto: proyectos completados, resultados, números, reconocimiento. Esto será evidencia de tu valor para futuras negociaciones.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Compilar logros de 3 meses', 'Cuantificar impacto', 'Documentar reconocimiento'],
    learningGoals: ['Evidencia de valor', 'Portfolio de impacto'],
    actionItems: ['Guardar para futuro', 'Compartir si aplica'],
    notionTemplate: 'https://notion.so/plantilla-dia-72',
    estimatedHours: 1
  },
  73: {
    dia: 73,
    title: 'Mentoría y knowledge sharing',
    subtitle: 'Contribuye al crecimiento de otros',
    description: 'Activamente mentoriza, enseña, comparte. No solo creces tú. Construyes reputación como alguien que eleva al equipo. Esto es leadership verdadera.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Mentoría regular a 1-2 personas', 'Compartir conocimiento en equipo', 'Documentar best practices'],
    learningGoals: ['Leadership multiplicador', 'Cultura de crecimiento'],
    actionItems: ['Sesiones regulares de mentoría', 'Documentación de procesos'],
    notionTemplate: 'https://notion.so/plantilla-dia-73',
    estimatedHours: 1
  },
  74: {
    dia: 74,
    title: 'Innovación - Identifica mejoras',
    subtitle: 'Sé catalizador de cambio',
    description: 'Identifica cosas que pueden mejorar. Propone innovaciones. No solo ejecutas, mejoras. Esto te posiciona como pensador estratégico.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Identificar 3 mejoras potenciales', 'Proponer soluciones', 'Facilitar implementación'],
    learningGoals: ['Pensamiento estratégico', 'Proactividad'],
    actionItems: ['Presentar ideas', 'Championing de cambio'],
    notionTemplate: 'https://notion.so/plantilla-dia-74',
    estimatedHours: 1.5
  },
  75: {
    dia: 75,
    title: 'Checkpoint: Día 75 - 85% done',
    subtitle: 'Últimas 2.5 semanas de transformación',
    description: 'Estás casi completo. Reflexión: ¿quién eras hace 75 días? ¿quién eres ahora? Cambio es evidente. Prepárate para cierre de ciclo.',
    phase: 'refinement',
    unlocksA3Module: 'refinement-phase-complete',
    tasks: ['Reflexión profunda de transformación', 'Documentar learnings', 'Preparar cierre'],
    learningGoals: ['Reconocimiento de transformación', 'Integración de learnings'],
    actionItems: ['Compartir historia', 'Preparar próxima fase'],
    notionTemplate: 'https://notion.so/plantilla-dia-75',
    estimatedHours: 1
  },
  76: {
    dia: 76,
    title: 'Evaluación de desempeño - 90 días',
    subtitle: 'Revisión formal de primer trimestre',
    description: 'Si aplica en tu rol, evaluación formal de 90 días. Documentar logros, recibir feedback, discutir next steps. Esto es importante para tu trayectoria.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Preparar auto-evaluación', 'Sesión de review con jefe', 'Discusión de compensación si aplica'],
    learningGoals: ['Evaluación formal', 'Negociación de compensación si es el momento'],
    actionItems: ['Documentar para futuro', 'Alinear expectations'],
    notionTemplate: 'https://notion.so/plantilla-dia-76',
    estimatedHours: 1
  },
  77: {
    dia: 77,
    title: 'Consolidación - Cristaliza tu lugar',
    subtitle: 'Ya eres indispensable',
    description: 'Consolida: relaciones fuertes, rol claro, contribuciones evidentes, reputación establecida. Ya no estás en probación. Eres parte del equipo.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Consolidar posición en equipo', 'Clarificar rol y responsabilidades', 'Asegurar compensación está OK'],
    learningGoals: ['Estabilidad en rol', 'Seguridad psicológica'],
    actionItems: ['Relaciones estables', 'Reconocimiento público'],
    notionTemplate: 'https://notion.so/plantilla-dia-77',
    estimatedHours: 1
  },
  78: {
    dia: 78,
    title: 'Próximos objetivos - Qué viene',
    subtitle: 'Planificación de 90 siguientes',
    description: 'Ahora que estás establecido, qué sigue: proyectos mayores, próximo nivel, especialización, lateral move. Diseña tu siguiente 90 días.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Definir objetivos próximos 90 días', 'Mapear proyectos ambiciosos', 'Hablar con jefe sobre trajectory'],
    learningGoals: ['Planificación de carrera', 'Ambición calibrada'],
    actionItems: ['OKRs para próximo quarter', 'Mentoría de jefe sobre growth path'],
    notionTemplate: 'https://notion.so/plantilla-dia-78',
    estimatedHours: 1
  },
  79: {
    dia: 79,
    title: 'Red externa - Mantén el networking vivo',
    subtitle: 'No te aisles, sigue en el mercado',
    description: 'No porque entraste a rol olvidarás el mercado. Mantén networking vivo. Contacta con gente, asiste eventos, mantén visibilidad. Esto es carrera long-term.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Contactar 5-10 personas de network', 'Asistir a un evento industria', 'Coffee/café con pares en otros roles'],
    learningGoals: ['Mantenimiento de red', 'Market awareness'],
    actionItems: ['Calendario de networking regular', 'Eventos de industria'],
    notionTemplate: 'https://notion.so/plantilla-dia-79',
    estimatedHours: 1
  },
  80: {
    dia: 80,
    title: 'Thought leadership - Construye platform',
    subtitle: 'Sé voz en industria',
    description: 'Construye tu platform: escribe artículos, habla en eventos, contribuye a conversaciones de industria. Esto amplifica tu alcance y valor.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Escribir 1-2 artículos sobre learnings', 'Presentar en evento o webinar', 'Contribuir a discusión industria'],
    learningGoals: ['Thought leadership', 'Amplificación de voz'],
    actionItems: ['Publicaciones regulares', 'Speaking opportunities'],
    notionTemplate: 'https://notion.so/plantilla-dia-80',
    estimatedHours: 1.5
  },
  81: {
    dia: 81,
    title: 'Especialización - Dominio en área clave',
    subtitle: 'Diferenciación profesional',
    description: 'Ahora, crea especialidad: domina área clave, conviértete en experto. Esto te diferencia. Búsqueda de expertise es tendencia en mercado.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Elegir especialidad', 'Construir expertise mediante proyectos', 'Documentar learnings'],
    learningGoals: ['Diferenciación como experto', 'Valor agregado único'],
    actionItems: ['Cursos avanzados', 'Proyectos de especialidad'],
    notionTemplate: 'https://notion.so/plantilla-dia-81',
    estimatedHours: 2
  },
  82: {
    dia: 82,
    title: 'Mentoría formal - Lidera desarrollo de otros',
    subtitle: 'Impacto a través de otros',
    description: 'Formaliza mentoría: 1-3 juniors que mentorices. Esto amplifica tu impacto, construye liderazgo, y es profundamente satisfactorio.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Asumir rol formal de mentor', 'Sesiones regulares de mentoría', 'Evaluación de progreso de mentees'],
    learningGoals: ['Liderazgo formal', 'Impacto multiplicado'],
    actionItems: ['Programa de mentoría', 'Seguimiento regular'],
    notionTemplate: 'https://notion.so/plantilla-dia-82',
    estimatedHours: 1
  },
  83: {
    dia: 83,
    title: 'Impacto estratégico - Beyond tu rol',
    subtitle: 'Pensamiento a nivel empresa',
    description: 'Piensa a nivel empresa, no solo tu rol. Contribuye a decisiones estratégicas. Participa en iniciativas cross-functional mayores. Eleva perspectiva.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Proponer iniciativa estratégica', 'Participar en planificación de empresa', 'Contribuir a decisiones mayores'],
    learningGoals: ['Pensamiento estratégico a nivel empresa', 'Influencia organizacional'],
    actionItems: ['Conversación con leadership', 'Participación en iniciativas clave'],
    notionTemplate: 'https://notion.so/plantilla-dia-83',
    estimatedHours: 1
  },
  84: {
    dia: 84,
    title: 'Revisión de learnings - 84 días después',
    subtitle: 'Qué aprendiste realmente',
    description: 'Revisión profunda: ¿qué aprendiste sobre ti? ¿sobre el mercado? ¿sobre carrera? ¿qué habrías hecho diferente? Documenta para futuro.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Reflexión profunda de aprendizajes', 'Documentar lecciones clave', 'Crear guía para ti mismo'],
    learningGoals: ['Sabiduría acumulada', 'Preparación para próxima etapa'],
    actionItems: ['Compartir learnings', 'Mentorar a otros basado en esto'],
    notionTemplate: 'https://notion.so/plantilla-dia-84',
    estimatedHours: 1
  },
  85: {
    dia: 85,
    title: 'Checkpoint: Semana 12 - En recta final',
    subtitle: 'Día 85 de 90 - Una semana más',
    description: 'Una semana para finalizar. Reflexión: lograste lo que querías? Estás donde esperabas? Qué sigue? Prepárate para día 90.',
    phase: 'refinement',
    unlocksA3Module: 'recta-final-iniciada',
    tasks: ['Reflexión final de 90 días', 'Evaluación vs objetivos iniciales', 'Planificación de próximas etapas'],
    learningGoals: ['Cierre de ciclo', 'Visión de futuro'],
    actionItems: ['Documentar logros', 'Definir próximas prioridades'],
    notionTemplate: 'https://notion.so/plantilla-dia-85',
    estimatedHours: 1
  },
  86: {
    dia: 86,
    title: 'Celebración de progreso - Reconoce el camino',
    subtitle: 'Celebra lo que lograste',
    description: 'Celebra. Fuiste lejos. Transformaste carrera. Tienes nuevo rol, nuevo nivel, nuevas habilidades. Reconoce el esfuerzo. Comparte tu historia.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Celebración personal', 'Compartir logros con comunidad', 'Agradecimientos a mentores'],
    learningGoals: ['Reconocimiento de logros', 'Gratitud'],
    actionItems: ['Publicación en LinkedIn', 'Eventos de agradecimiento'],
    notionTemplate: 'https://notion.so/plantilla-dia-86',
    estimatedHours: 1
  },
  87: {
    dia: 87,
    title: 'Preparación para día 90 - Final',
    subtitle: 'Últimas 72 horas',
    description: 'Últimos 3 días. Documentación final. Reflexión final. Preparación mental para día 90. Este es tu último empujón.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Documentación final de jornada', 'Reflexión de transformación', 'Preparación de cierre'],
    learningGoals: ['Finalización de ciclo', 'Preparación psicológica para siguiente'],
    actionItems: ['Escritura final', 'Meditación/reflexión'],
    notionTemplate: 'https://notion.so/plantilla-dia-87',
    estimatedHours: 1
  },
  88: {
    dia: 88,
    title: '2 días para el final - Cierre',
    subtitle: 'Último push',
    description: 'Dos días. Asegúrate que todo esté documentado. Que hayas hablado con mentores. Que tengas claridad sobre qué sigue. Prepárate.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Sesión final con mentor/coach', 'Documentación de proceso', 'Planificación de 90 siguientes'],
    learningGoals: ['Cierre completo', 'Transición hacia siguiente'],
    actionItems: ['Conversación de despedida de ciclo', 'Claridad de próximos pasos'],
    notionTemplate: 'https://notion.so/plantilla-dia-88',
    estimatedHours: 1
  },
  89: {
    dia: 89,
    title: '1 día para el final - Víspera',
    subtitle: 'Mañana es el fin',
    description: 'Un día. Reflexión final. Última noche de 90 días. Descansa. Mañana celebras haber completado transformación de carrera de 90 días.',
    phase: 'refinement',
    unlocksA3Module: null,
    tasks: ['Reflexión profunda final', 'Descanso mental', 'Meditación/conexión'],
    learningGoals: ['Paz mental', 'Gratitud'],
    actionItems: ['Descanso', 'Preparación psicológica'],
    notionTemplate: 'https://notion.so/plantilla-dia-89',
    estimatedHours: 0.5
  },
  90: {
    dia: 90,
    title: 'DÍA 90 - Lo lograste',
    subtitle: 'Final y nuevo inicio',
    description: 'Hoy es día 90. Completaste. Has transformado carrera, conseguiste rol nuevo (o estás en búsqueda avanzada), tienes nuevas habilidades, eres versión mejorada de ti. Celebra.',
    phase: 'refinement',
    unlocksA3Module: 'dia-90-completado',
    tasks: ['Celebración final', 'Documentación de logros', 'Agradecimiento a comunidad'],
    learningGoals: ['Reconocimiento de transformación', 'Preparación para siguiente capítulo'],
    actionItems: ['Compartir experiencia completa', 'Mentoriar a otros en jornada'],
    notionTemplate: 'https://notion.so/plantilla-dia-90',
    estimatedHours: 0.5
  }
}
