// Task Details Database - All 30 days with comprehensive breakdowns and daily microactions

export interface TaskStep {
  stepNumber: number
  title: string
  description: string
  duration: string
  tips?: string[]
  example?: string
}

export interface TaskResource {
  title: string
  type: 'template' | 'article' | 'course' | 'tool' | 'video' | 'framework'
  url: string
  duration?: string
  description?: string
}

export interface TaskDetail {
  day: number
  title: string
  fullDescription: string
  objective: string
  steps: TaskStep[]
  resources: TaskResource[]
  expectedOutput?: string
  commonMistakes?: string[]
  successCriteria?: string[]
}

export const TASK_DETAILS: Record<number, TaskDetail> = {
  1: { day: 1, title: 'Define tu visión y roadmap', fullDescription: 'Crea un documento estructurado con tu objetivo profesional, los hitos clave y timeline realista.', objective: 'Claridad total sobre qué quieres lograr', steps: [{ stepNumber: 1, title: 'Escribe tu visión', description: 'Define rol, empresa, salario, ubicación en 3 años', duration: '10 min' }, { stepNumber: 2, title: 'Define 3 hitos (30/60/90 días)', description: 'Qué necesitas lograr en cada milestone', duration: '15 min' }, { stepNumber: 3, title: 'Crea plan de acciones', description: 'Desglosaa en acciones semanales', duration: '20 min' }], resources: [{ title: 'Plantilla de Objetivos', type: 'template', url: 'https://www.notion.so/templates/goal-setting', description: 'Plantilla lista para usar' }], successCriteria: ['✓ Visión escrita', '✓ 3 hitos definidos', '✓ Plan en Notion'] },

  2: { day: 2, title: 'Optimiza tu CV y LinkedIn', fullDescription: 'Actualiza ambos documentos con palabras clave del rol objetivo y logros cuantitativos.', objective: 'CV y LinkedIn listos para la búsqueda', steps: [{ stepNumber: 1, title: 'Actualiza CV con palabras clave', description: 'Incorpora palabras clave del rol, logros cuantitativos, skills relevantes', duration: '45 min' }, { stepNumber: 2, title: 'Optimiza LinkedIn', description: 'Foto profesional, headline claro, descripción compelling, skills destacados', duration: '30 min' }, { stepNumber: 3, title: 'Pide retroalimentación', description: 'Comparte con 2-3 personas para opiniones', duration: '15 min' }], resources: [{ title: 'Plantilla de CV', type: 'template', url: 'https://www.canva.com/search/cv/', description: 'Plantillas profesionales' }], successCriteria: ['✓ CV actualizado', '✓ LinkedIn optimizado', '✓ Retroalimentación recibida'] },

  3: { day: 3, title: 'Investiga el mercado y rol objetivo', fullDescription: 'Analiza salarios, skills requeridas, empresas relevantes y ofertas del rol que buscas.', objective: 'Data clara para posicionarte correctamente', steps: [{ stepNumber: 1, title: 'Analiza 5-10 descripciones de roles', description: 'Extrae skills comunes, requisitos, nivel de experiencia', duration: '30 min' }, { stepNumber: 2, title: 'Investiga salarios', description: 'Usa Glassdoor, Levels.fyi, Payscale para rango salarial', duration: '20 min' }, { stepNumber: 3, title: 'Crea lista de 20+ empresas objetivo', description: 'Empresas donde quieres trabajar', duration: '25 min' }], resources: [{ title: 'Glassdoor', type: 'tool', url: 'https://www.glassdoor.com' }], successCriteria: ['✓ Descripciones analizadas', '✓ Salarios investigados', '✓ Empresas listadas'] },

  4: { day: 4, title: 'Auditoria: Skills actuales vs objetivo', fullDescription: 'Compara tus skills actuales con los requeridos para el rol. Identifica gaps.', objective: 'Mapa claro de qué skills necesitas desarrollar', steps: [{ stepNumber: 1, title: 'Haz lista de skills actuales', description: 'Todo lo que sabes hacer bien hoy', duration: '15 min' }, { stepNumber: 2, title: 'Lista skills objetivo', description: 'Del rol que investigaste en Día 3', duration: '10 min' }, { stepNumber: 3, title: 'Identifica 3 gaps críticos', description: 'Prioriza los skills más importantes faltantes', duration: '10 min' }], resources: [], successCriteria: ['✓ Skills actuales documentados', '✓ Skills objetivo identificados', '✓ 3 gaps prioritarios'] },

  5: { day: 5, title: 'Busca e inicia curso/recurso principal', fullDescription: 'Elige y comienza el principal recurso de aprendizaje para cerrar tus gaps de skills.', objective: 'Iniciar aprendizaje formal del skill crítico', steps: [{ stepNumber: 1, title: 'Busca 3-5 cursos relevantes', description: 'Udemy, Coursera, LinkedIn Learning, etc', duration: '20 min' }, { stepNumber: 2, title: 'Elige uno y regístrate', description: 'El que mejor se alinee con tus gaps', duration: '10 min' }, { stepNumber: 3, title: 'Completa Lección 1', description: 'Ve el primer módulo/capítulo', duration: '30 min' }], resources: [{ title: 'Udemy', type: 'tool', url: 'https://www.udemy.com' }, { title: 'Coursera', type: 'tool', url: 'https://www.coursera.org' }], successCriteria: ['✓ Curso elegido', '✓ Registrado', '✓ Lección 1 completada'] },

  6: { day: 6, title: 'Crea tu perfil de marca personal', fullDescription: 'Define quién eres profesionalmente. Crea narrativa coherente para todas tus plataformas.', objective: 'Brand personal consistente en todas plataformas', steps: [{ stepNumber: 1, title: 'Define tu proposición única', description: 'Qué te hace diferente/mejor en tu industria', duration: '15 min' }, { stepNumber: 2, title: 'Escribe bio de marca', description: '2-3 frases que capturen tu esencia profesional', duration: '10 min' }, { stepNumber: 3, title: 'Actualiza bio en todas plataformas', description: 'LinkedIn, GitHub, Twitter, sitio web (si tienes)', duration: '15 min' }], resources: [], successCriteria: ['✓ Proposición única definida', '✓ Bio de marca creada', '✓ Bios actualizadas en todas plataformas'] },

  7: { day: 7, title: 'Inicio de acción: 1ª semana', fullDescription: 'Primer contacto real. Comienza a aplicar a posiciones y a hacer networking.', objective: 'Poner en movimiento tus acciones de búsqueda', steps: [{ stepNumber: 1, title: 'Aplica a 3-5 posiciones', description: 'De la lista de empresas objetivo del Día 3', duration: '30 min' }, { stepNumber: 2, title: 'Contacta 5 personas para networking', description: 'LinkedIn, email, conocidos en la industria', duration: '25 min' }, { stepNumber: 3, title: 'Documenta en tu tracker', description: 'Guarda aplicaciones y contactos realizados', duration: '10 min' }], resources: [], successCriteria: ['✓ 3-5 aplicaciones', '✓ 5 contactos de networking', '✓ Tracker actualizado'] },

  8: { day: 8, title: 'Semana 1 - Checkpoint', fullDescription: 'Revisión de progreso de la primer semana. Qué funcionó y qué necesita ajuste.', objective: 'Evaluar estrategia y realinear si es necesario', steps: [{ stepNumber: 1, title: 'Revisa tus números', description: 'Aplicaciones, contactos, respuestas recibidas', duration: '15 min' }, { stepNumber: 2, title: 'Analiza qué funcionó', description: 'Qué acciones tuvieron mejor respuesta', duration: '10 min' }, { stepNumber: 3, title: 'Ajusta estrategia', description: 'Doble apuestas en lo que funciona', duration: '15 min' }], resources: [], successCriteria: ['✓ Metrics revisadas', '✓ Qué funcionó identificado', '✓ Ajustes realizados'] },

  9: { day: 9, title: 'Análisis profundo: Mercado y salarios', fullDescription: 'Investigación exhaustiva de tendencias, salarios y habilidades emergentes en tu industria.', objective: 'Entender completamente el mercado y oportunidades', steps: [{ stepNumber: 1, title: 'Análisis de salarios por nivel', description: 'Junior vs Intermedio vs Senior en tu industria/región', duration: '30 min' }, { stepNumber: 2, title: 'Identifica tendencias de mercado', description: 'Skills emergentes, industrias en crecimiento', duration: '25 min' }, { stepNumber: 3, title: 'Crea documento de insights', description: 'Análisis en Notion o Google Doc', duration: '20 min' }], resources: [{ title: 'Levels.fyi', type: 'tool', url: 'https://www.levels.fyi' }, { title: 'Payscale', type: 'tool', url: 'https://www.payscale.com' }], successCriteria: ['✓ Salarios investigados', '✓ Tendencias identificadas', '✓ Insights documentados'] },

  10: { day: 10, title: 'Avanza en tu curso principal', fullDescription: 'Progreso significativo en tu educación formal. Completa al menos 2-3 módulos.', objective: 'Mantener momentum de aprendizaje', steps: [{ stepNumber: 1, title: 'Dedica 2 horas al curso', description: 'Sin distracciones, toma notas', duration: '120 min' }, { stepNumber: 2, title: 'Completa ejercicios prácticos', description: 'Implementa lo aprendido', duration: '30 min' }, { stepNumber: 3, title: 'Reflexiona y documenta', description: 'Cómo aplicas esto en tu rol objetivo', duration: '15 min' }], resources: [], successCriteria: ['✓ 2+ módulos completados', '✓ Ejercicios realizados', '✓ Reflexión documentada'] },

  11: { day: 11, title: 'Expande tu red: Outreach plan', fullDescription: 'Crea estrategia de networking. Identifica y contacta personas clave en tu industria.', objective: 'Red de contactos fortalecida con personas estratégicas', steps: [{ stepNumber: 1, title: 'Identifica 10-15 personas clave', description: 'CEOs, managers, profesionales en rol objetivo', duration: '20 min' }, { stepNumber: 2, title: 'Personaliza mensajes', description: 'Mensajes genuinos mencionando algo específico', duration: '30 min' }, { stepNumber: 3, title: 'Envía conectes/mensajes', description: 'LinkedIn, email, o ambos', duration: '15 min' }], resources: [], successCriteria: ['✓ 10-15 personas identificadas', '✓ Mensajes personalizados', '✓ Contactos enviados'] },

  12: { day: 12, title: 'Análisis de competencia', fullDescription: 'Estudia a otros candidatos o profesionales en tu rol objetivo. Qué hacen bien? Qué te diferencia?', objective: 'Entender qué te hace competitivo y único', steps: [{ stepNumber: 1, title: 'Encuentra 5-10 perfiles similares', description: 'LinkedIn, GitHub, portfolios', duration: '20 min' }, { stepNumber: 2, title: 'Analiza sus fortalezas', description: 'Skills, experiencia, cómo se posicionan', duration: '20 min' }, { stepNumber: 3, title: 'Define tu diferenciador', description: 'Qué hace que seas único/mejor', duration: '15 min' }], resources: [], successCriteria: ['✓ Competencia estudiada', '✓ Fortalezas identificadas', '✓ Diferenciador definido'] },

  13: { day: 13, title: 'Follow-up y seguimiento', fullDescription: 'Contacta a personas donde enviaste aplicaciones hace 1-2 semanas. Mantén visibilidad.', objective: 'Mantener momentum y generar top-of-mind', steps: [{ stepNumber: 1, title: 'Identifica aplicaciones sin respuesta', description: 'De hace 7-14 días', duration: '10 min' }, { stepNumber: 2, title: 'Envía follow-ups profesionales', description: 'Personalizados, sin insistir', duration: '20 min' }, { stepNumber: 3, title: 'Re-contacta conexiones iniciales', description: 'Si hace > 1 semana sin contacto', duration: '15 min' }], resources: [], successCriteria: ['✓ Follow-ups enviados', '✓ Nuevas respuestas', '✓ Contactos re-activados'] },

  14: { day: 14, title: 'Semana 2 - Checkpoint & Ajustes', fullDescription: 'Segunda revisión. Ajusta lo que no está funcionando, acelera lo que sí.', objective: 'Optimizar estrategia basada en resultados reales', steps: [{ stepNumber: 1, title: 'Revisa KPIs de Semana 2', description: 'Aplicaciones, entrevistas agendadas, feedback', duration: '15 min' }, { stepNumber: 2, title: 'Compara con Semana 1', description: 'Ves progreso o decaimiento?', duration: '10 min' }, { stepNumber: 3, title: 'Realinea tácticas', description: 'Intensifica lo ganador, cambia lo que falla', duration: '20 min' }], resources: [], successCriteria: ['✓ KPIs revisados', '✓ Comparativa completada', '✓ Nueva estrategia definida'] },

  15: { day: 15, title: 'Entrevistas de práctica y preparación', fullDescription: 'Realiza 2-3 entrevistas de práctica para ganar confianza y eliminar nerviosismo.', objective: 'Estar listo para entrevistas reales', steps: [{ stepNumber: 1, title: 'Prepara 3 historias STAR', description: 'Situación, Tarea, Acción, Resultado', duration: '30 min' }, { stepNumber: 2, title: 'Agenda 2-3 entrevistas de práctica', description: 'Con mentores o amigos en la industria', duration: '15 min' }, { stepNumber: 3, title: 'Realiza las entrevistas', description: 'Vístete profesional, toma notas de retroalimentación', duration: '90 min' }], resources: [{ title: 'Guía del Método STAR', type: 'article', url: 'https://www.indeed.com/career-advice/interviewing/how-to-answer-behavioral-interview-questions' }], successCriteria: ['✓ Historias STAR preparadas', '✓ Entrevistas de práctica completadas', '✓ Retroalimentación documentada'] },

  16: { day: 16, title: 'Proyecto/Contribución: Construye y Lanza', fullDescription: 'Crea un pequeño proyecto o contribuye a código abierto que demuestre tus skills.', objective: 'Evidencia visible y tangible de tus habilidades', steps: [{ stepNumber: 1, title: 'Elige proyecto o repositorio', description: 'Alineado con rol objetivo', duration: '30 min' }, { stepNumber: 2, title: 'Planifica MVP', description: 'Qué puedes hacer en 3-4 horas', duration: '30 min' }, { stepNumber: 3, title: 'Ejecuta y publica', description: 'GitHub, comparte en LinkedIn', duration: '240 min' }], resources: [{ title: 'GitHub Explore', type: 'tool', url: 'https://github.com/explore' }], successCriteria: ['✓ Código publicado', '✓ README documentado', '✓ Compartido en LinkedIn'] },

  17: { day: 17, title: 'Proyecto práctico: Liderazgo real', fullDescription: 'Aplica liderazgo en un contexto real. Lidera un pequeño proyecto o iniciativa con tu equipo.', objective: 'Ganar experiencia de liderazgo tangible', steps: [{ stepNumber: 1, title: 'Identifica proyecto pequeño', description: 'Algo que puedas liderar en 1-2 semanas', duration: '20 min' }, { stepNumber: 2, title: 'Define equipo y objetivos', description: 'Quiénes participan, qué se logra', duration: '15 min' }, { stepNumber: 3, title: 'Ejecuta y documenta lecciones', description: 'Registra qué aprendiste de liderar', duration: '240 min' }], resources: [], successCriteria: ['✓ Proyecto liderado', '✓ Equipo comprometido', '✓ Lecciones documentadas'] },

  18: { day: 18, title: 'Contenido: Comparte tu Expertise', fullDescription: 'Escribe un artículo o post sobre lo que aprendiste. Demuestra pensamiento e insights.', objective: 'Construir autoridad y visibilidad en tu industria', steps: [{ stepNumber: 1, title: 'Elige tema de expertise', description: 'Algo que aprendiste recientemente', duration: '15 min' }, { stepNumber: 2, title: 'Escribe artículo/post', description: 'LinkedIn (500-1000 palabras) o Medium', duration: '90 min' }, { stepNumber: 3, title: 'Publica y promociona', description: 'Comparte con tu red', duration: '30 min' }], resources: [], successCriteria: ['✓ Contenido escrito', '✓ Publicado', '✓ Compartido con red'] },

  19: { day: 19, title: 'Práctica intensiva: Skills críticos', fullDescription: 'Dedica tiempo a ejercicios intensivos de la skill más crítica para tu rol.', objective: 'Dominar la skill técnica más importante', steps: [{ stepNumber: 1, title: 'Identifica skill crítica', description: 'La más requerida y donde debes mejorar más', duration: '15 min' }, { stepNumber: 2, title: 'Practica 3+ horas', description: 'Ejercicios, problemas, simulaciones', duration: '180 min' }, { stepNumber: 3, title: 'Mide y documenta progreso', description: 'Qué mejoró, qué falta', duration: '15 min' }], resources: [{ title: 'LeetCode', type: 'tool', url: 'https://www.leetcode.com' }], successCriteria: ['✓ 3+ horas de práctica', '✓ Problemas resueltos', '✓ Progreso medido'] },

  20: { day: 20, title: 'Revisión del Punto Medio: Día 20', fullDescription: 'Revisión de punto medio. Evalúa si estás en track para cumplir objetivos del Día 30.', objective: 'Asegurar alineación y ajustar si es necesario', steps: [{ stepNumber: 1, title: 'Revisa visión del Día 1', description: 'Comparar con progreso actual', duration: '15 min' }, { stepNumber: 2, title: 'Mide KPIs principales', description: 'Entrevistas, ofertas, skills, relaciones construidas', duration: '20 min' }, { stepNumber: 3, title: 'Acelera o ajusta', description: 'Qué cambiar para los últimos 10 días', duration: '25 min' }], resources: [], successCriteria: ['✓ KPIs medidos', '✓ Comparativa realizada', '✓ Plan para últimos 10 días'] },

  21: { day: 21, title: 'Networking: Entrevistas Informativas', fullDescription: 'Realiza 2-3 conversaciones con profesionales en tu campo. Aprende, expande red, encuentra mentores.', objective: 'Obtener insights y expandir red de conexiones valiosas', steps: [{ stepNumber: 1, title: 'Identifica 3 personas para entrevistar', description: 'Profesionales en rol/empresa objetivo', duration: '20 min' }, { stepNumber: 2, title: 'Envía invitaciones personalizadas', description: 'Explica por qué quieres hablar con ellos', duration: '15 min' }, { stepNumber: 3, title: 'Realiza 3 llamadas de 30 min', description: 'Escucha, aprende, toma notas', duration: '90 min' }], resources: [], successCriteria: ['✓ 3 personas contactadas', '✓ 2-3 llamadas completadas', '✓ Insights documentados'] },

  22: { day: 22, title: 'Semana 3: Intensificar lo ganador', fullDescription: 'Basado en qué funcionó, aumenta volumen y calidad de esas acciones ganadores.', objective: 'Maximizar retorno de las tácticas probadas', steps: [{ stepNumber: 1, title: 'Analiza Semanas 1-2', description: 'Qué acciones generaron entrevistas/ofertas', duration: '20 min' }, { stepNumber: 2, title: 'Duplica volumen de ganadores', description: '2-3x más de lo que funcionó', duration: '480 min' }, { stepNumber: 3, title: 'Documenta cambios y resultados', description: 'Qué impacto tuvo intensificar', duration: '15 min' }], resources: [], successCriteria: ['✓ Análisis completado', '✓ Volumen duplicado', '✓ Resultados documentados'] },

  23: { day: 23, title: 'Preparación: Entrevista Real Agendada', fullDescription: 'Prepárate intensivamente para la entrevista que ya tienes agendada.', objective: 'Maximizar oportunidades de entrevista real', steps: [{ stepNumber: 1, title: 'Investiga empresa profundamente', description: 'Productos, cultura, valores, noticias recientes', duration: '45 min' }, { stepNumber: 2, title: 'Prepara ejemplos STAR', description: 'Situaciones relevantes para la empresa', duration: '30 min' }, { stepNumber: 3, title: 'Practica y prepara preguntas', description: 'Entrevista de práctica, preguntas para ellos', duration: '45 min' }], resources: [], successCriteria: ['✓ Empresa investigada', '✓ Ejemplos STAR preparados', '✓ Preguntas listas'] },

  24: { day: 24, title: 'Ejecuta: Entrevista Real', fullDescription: 'Realiza la entrevista y haz seguimiento profesional en 24 horas.', objective: 'Convertir entrevista en siguiente ronda', steps: [{ stepNumber: 1, title: 'Realiza entrevista', description: 'Puntual, profesional, auténtico, energético', duration: '60 min' }, { stepNumber: 2, title: 'Envía nota de agradecimiento', description: 'Correo personalizado dentro de 24 horas', duration: '20 min' }, { stepNumber: 3, title: 'Documenta retroalimentación', description: 'Qué te preguntaron, cómo respondiste', duration: '15 min' }], resources: [], successCriteria: ['✓ Entrevista realizada', '✓ Nota de agradecimiento enviada', '✓ Retroalimentación documentada'] },

  25: { day: 25, title: 'Networking: Otra Entrevista Informativa', fullDescription: 'Realiza otra conversación con profesional diferente. Expande red continuamente.', objective: 'Mantener red activa y aprender de otros profesionales', steps: [{ stepNumber: 1, title: 'Identifica otra persona clave', description: 'Diferente industria, empresa o nivel', duration: '10 min' }, { stepNumber: 2, title: 'Envía invitación personalizada', description: 'Referencia común o valor que ofreces', duration: '10 min' }, { stepNumber: 3, title: 'Realiza llamada de 30 min', description: 'Escucha, aprende, crea relación', duration: '30 min' }], resources: [], successCriteria: ['✓ Persona contactada', '✓ Llamada realizada', '✓ Relación iniciada'] },

  26: { day: 26, title: 'Aprendizaje: Continúa con curso', fullDescription: 'Sigue avanzando en tu educación formal. Completa otro módulo/semana del curso.', objective: 'Mantener momentum de aprendizaje hacia el Día 30', steps: [{ stepNumber: 1, title: 'Dedica 3+ horas al curso', description: 'Completar módulo o 3-4 lecciones', duration: '180 min' }, { stepNumber: 2, title: 'Realiza ejercicios prácticos', description: 'Implementa conceptos aprendidos', duration: '30 min' }, { stepNumber: 3, title: 'Reflexiona sobre progreso', description: 'Cómo esto te prepara para el rol objetivo', duration: '15 min' }], resources: [], successCriteria: ['✓ 3+ horas dedicadas', '✓ Módulo completado', '✓ Progreso reflexionado'] },

  27: { day: 27, title: 'Nuevas aplicaciones y outreach', fullDescription: 'Mantén pipeline activo. Aplica a nuevas posiciones y contacta recruiters.', objective: 'Asegurar múltiples oportunidades en movimiento', steps: [{ stepNumber: 1, title: 'Aplica a 3-5 posiciones nuevas', description: 'De tu lista de empresas objetivo', duration: '60 min' }, { stepNumber: 2, title: 'Contacta 5 recruiters', description: 'Especializados en tu industria/rol', duration: '30 min' }, { stepNumber: 3, title: 'Actualiza tracker', description: 'Documenta todas las acciones', duration: '10 min' }], resources: [], successCriteria: ['✓ 3-5 aplicaciones nuevas', '✓ 5 recruiters contactados', '✓ Tracker actualizado'] },

  28: { day: 28, title: 'Hito 30 días: Revisión Completa', fullDescription: 'Evaluación comprensiva del mes 1. Celebra logros, documenta lecciones, planifica meses 2-3.', objective: 'Consolidar aprendizajes y establecer visión clara para próximos 60 días', steps: [{ stepNumber: 1, title: 'Celebra tus logros', description: 'Documenta TODO lo que lograste en 30 días', duration: '30 min' }, { stepNumber: 2, title: 'Análisis cuantitativo', description: 'KPIs: entrevistas, ofertas, skills, conexiones', duration: '30 min' }, { stepNumber: 3, title: 'Planifica Meses 2-3', description: 'Objetivos, estrategias y tácticas para próximos 60 días', duration: '60 min' }], resources: [], successCriteria: ['✓ Logros celebrados', '✓ Métricas documentadas', '✓ Plan 60 días definido'] },

  29: { day: 29, title: 'Reflexión: Cambios en mentalidad y confianza', fullDescription: 'Reflexiona sobre cambios internos. Mentalidad, confianza, dirección de carrera más clara.', objective: 'Entender transformación personal y ajustar visión si es necesario', steps: [{ stepNumber: 1, title: 'Escribe reflexión personal', description: 'Cambios en cómo te ves profesionalmente', duration: '30 min' }, { stepNumber: 2, title: 'Analiza decisiones tomadas', description: 'Qué funcionó mejor de lo esperado?', duration: '20 min' }, { stepNumber: 3, title: 'Actualiza tu visión', description: 'Tu dirección sigue siendo la misma?', duration: '15 min' }], resources: [], successCriteria: ['✓ Reflexión documentada', '✓ Cambios identificados', '✓ Visión reconfirmada o actualizada'] },

  30: { day: 30, title: 'Mes 1 COMPLETADO: Full Assessment', fullDescription: 'Evaluación final comprensiva. Mide éxito, documenta lecciones clave, toma decisiones estratégicas.', objective: 'Tener claridad total sobre progreso y siguiente paso', steps: [{ stepNumber: 1, title: 'Revisión de Números (KPIs)', description: 'Entrevistas logradas, ofertas recibidas, skills adquiridos, conexiones construidas', duration: '30 min' }, { stepNumber: 2, title: 'Análisis Cualitativo', description: 'Mentalidad, confianza, si estás en el camino correcto', duration: '30 min' }, { stepNumber: 3, title: 'Decisiones Clave', description: '¿Continúo? ¿Qué cambio? ¿Próximos pasos inmediatos?', duration: '30 min' }], resources: [], successCriteria: ['✓ KPIs medidos', '✓ Análisis cualitativo completo', '✓ Decisiones registradas', '✓ Próximos 60 días planificados'] }
}

export function getTaskDetail(day: number): TaskDetail | undefined {
  return TASK_DETAILS[day]
}

export function getAvailableDays(): number[] {
  return Object.keys(TASK_DETAILS).map(Number).sort((a, b) => a - b)
}
