-- Adding exactly 64 required books to knowledge_base table for backup and restoration
-- These are the books that must be available in the biblioteca

INSERT INTO knowledge_base (title, author, category, language, difficulty_level, tags, estimated_read_time, created_at, updated_at) VALUES
('Designing Your Life', 'Bill Burnett & Dave Evans', 'Career Development', 'English', 'Beginner', ARRAY['career', 'design', 'planning', 'life'], 240, NOW(), NOW()),
('Dries', 'David H. Palk', 'Career Development', 'English', 'Intermediate', ARRAY['motivation', 'persistence', 'goals'], 180, NOW(), NOW()),
('Grit', 'Angela Duckworth', 'Personal Development', 'English', 'Beginner', ARRAY['perseverance', 'success', 'psychology'], 240, NOW(), NOW()),
('Peak', 'Anders Ericsson & Robert Pool', 'Skills Development', 'English', 'Intermediate', ARRAY['expertise', 'deliberate-practice', 'mastery'], 300, NOW(), NOW()),
('Atomic Habits', 'James Clear', 'Personal Development', 'English', 'Beginner', ARRAY['habits', 'productivity', 'improvement'], 200, NOW(), NOW()),
('The Good They Can''t Ignore You', 'Cal Newport', 'Career Development', 'English', 'Intermediate', ARRAY['career', 'craftsmanship', 'passion'], 240, NOW(), NOW()),
('The 2-Hour Job Search', 'Steve Dalton', 'Job Search', 'English', 'Beginner', ARRAY['networking', 'job-search', 'career'], 120, NOW(), NOW()),
('What Color is Your Parachute?', 'Richard N. Bolles', 'Career Development', 'English', 'Beginner', ARRAY['career-planning', 'self-assessment', 'job-search'], 300, NOW(), NOW()),
('Eat That Frog!', 'Brian Tracy', 'Productivity', 'English', 'Beginner', ARRAY['productivity', 'time-management', 'procrastination'], 120, NOW(), NOW()),
('Essentialism', 'Greg Mckeown', 'Productivity', 'English', 'Intermediate', ARRAY['focus', 'priorities', 'simplicity'], 180, NOW(), NOW()),
('Getting Things Done', 'David Allen', 'Productivity', 'English', 'Intermediate', ARRAY['productivity', 'organization', 'systems'], 240, NOW(), NOW()),
('Never Split The Difference', 'Chris Voss & John Zeratsky', 'Communication', 'English', 'Advanced', ARRAY['negotiation', 'communication', 'persuasion'], 240, NOW(), NOW()),
('The Power of Habit', 'Charles Duhigg', 'Psychology', 'English', 'Intermediate', ARRAY['habits', 'behavior', 'change'], 240, NOW(), NOW()),
('Tiny Habits', 'BJ Fogg', 'Productivity', 'English', 'Beginner', ARRAY['habits', 'behavior-change', 'small-steps'], 180, NOW(), NOW()),
('Ultralearning', 'Scott Young', 'Learning', 'English', 'Intermediate', ARRAY['learning', 'education', 'skills'], 240, NOW(), NOW()),
('8,000 Words to Master Business Writing', 'Bryan A. Garner & Joseph Kimble', 'Communication', 'English', 'Advanced', ARRAY['writing', 'business', 'communication'], 200, NOW(), NOW()),
('The Art of Closing Any Deal', 'Zig Ziglar', 'Sales', 'English', 'Intermediate', ARRAY['sales', 'negotiation', 'closing'], 180, NOW(), NOW()),
('On Writing Well', 'William Zinsser', 'Writing', 'English', 'Intermediate', ARRAY['writing', 'communication', 'craft'], 240, NOW(), NOW()),
('Presentation Zen', 'Garr Reynolds', 'Communication', 'English', 'Intermediate', ARRAY['presentations', 'design', 'communication'], 160, NOW(), NOW()),
('Passions', 'Nancy Childs', 'Career Development', 'English', 'Beginner', ARRAY['passion', 'career', 'fulfillment'], 120, NOW(), NOW()),
('Talk Like TED', 'Carmine Gallo', 'Communication', 'English', 'Beginner', ARRAY['public-speaking', 'presentations', 'storytelling'], 200, NOW(), NOW()),
('The Pyramid Principle', 'Barbara Minto', 'Communication', 'English', 'Advanced', ARRAY['thinking', 'communication', 'logic'], 240, NOW(), NOW()),
('The Style Style', 'Steven Pinker', 'Writing', 'English', 'Advanced', ARRAY['writing', 'language', 'clarity'], 280, NOW(), NOW()),
('Writing That Works', 'Kenneth Roman & Joel Raphaelson', 'Writing', 'English', 'Intermediate', ARRAY['writing', 'business', 'communication'], 180, NOW(), NOW()),
('Crucial Conversations', 'Kerry Patterson, Joseph Grenny & Ron McMillan', 'Communication', 'English', 'Intermediate', ARRAY['communication', 'dialogue', 'conflict-resolution'], 240, NOW(), NOW()),
('Gives and Takes', 'Adam Grant', 'Psychology', 'English', 'Intermediate', ARRAY['psychology', 'relationships', 'collaboration'], 280, NOW(), NOW()),
('How to Win Friends and Influence People', 'Dale Carnegie', 'Relationships', 'English', 'Beginner', ARRAY['relationships', 'influence', 'people-skills'], 240, NOW(), NOW()),
('Mindset', 'Carol S. Dweck', 'Psychology', 'English', 'Beginner', ARRAY['mindset', 'psychology', 'growth'], 200, NOW(), NOW()),
('Never Eat Alone', 'Keith Ferrazzi', 'Networking', 'English', 'Beginner', ARRAY['networking', 'relationships', 'career'], 240, NOW(), NOW()),
('Pre-Suasion', 'Robert B. Cialdini', 'Persuasion', 'English', 'Advanced', ARRAY['persuasion', 'influence', 'psychology'], 280, NOW(), NOW()),
('The Charisma Myth', 'Olivia Fox Cabane', 'Communication', 'English', 'Intermediate', ARRAY['charisma', 'communication', 'presence'], 200, NOW(), NOW()),
('The Like Switch', 'Jack Schafer & Marvin Karlins', 'Relationships', 'English', 'Beginner', ARRAY['relationships', 'connection', 'influence'], 180, NOW(), NOW()),
('Extreme Ownership', 'Jocko Willink & Leif Babin', 'Leadership', 'English', 'Intermediate', ARRAY['leadership', 'responsibility', 'accountability'], 240, NOW(), NOW()),
('High Output Management', 'Andrew S. Grove', 'Management', 'English', 'Advanced', ARRAY['management', 'leadership', 'productivity'], 300, NOW(), NOW()),
('Leaders Eat Last', 'Simon Sinek', 'Leadership', 'English', 'Beginner', ARRAY['leadership', 'culture', 'trust'], 220, NOW(), NOW()),
('Multipliers', 'Liz Wiseman', 'Leadership', 'English', 'Intermediate', ARRAY['leadership', 'management', 'team'], 240, NOW(), NOW()),
('Team of Teams', 'Stanley McChrystal', 'Leadership', 'English', 'Advanced', ARRAY['leadership', 'organization', 'complexity'], 280, NOW(), NOW()),
('The Chaos Code', 'Derek Lau', 'Complexity', 'English', 'Advanced', ARRAY['complexity', 'systems', 'chaos'], 240, NOW(), NOW()),
('The Effective Executive', 'Peter F. Drucker', 'Management', 'English', 'Advanced', ARRAY['management', 'effectiveness', 'leadership'], 260, NOW(), NOW()),
('The Goal', 'Eliyahu M. Goldratt', 'Management', 'English', 'Intermediate', ARRAY['management', 'optimization', 'systems'], 220, NOW(), NOW()),
('The Innovator''s Dilemma', 'Clayton M. Christensen', 'Business Strategy', 'English', 'Advanced', ARRAY['innovation', 'strategy', 'business'], 300, NOW(), NOW()),
('Continuous Discovery Habits', 'Teresa Torres', 'Product Development', 'English', 'Intermediate', ARRAY['product', 'discovery', 'interviews'], 200, NOW(), NOW()),
('Empowered', 'Marty Cagan & Chris Jones', 'Product Development', 'English', 'Intermediate', ARRAY['product', 'leadership', 'teams'], 240, NOW(), NOW()),
('The Clean Slate Trip', 'McKee Frazey', 'Personal Development', 'English', 'Beginner', ARRAY['reset', 'renewal', 'perspective'], 120, NOW(), NOW()),
('Blue Ocean Strategy', 'V. Chan Kim & Renée Mauborgne', 'Business Strategy', 'English', 'Advanced', ARRAY['strategy', 'competition', 'innovation'], 280, NOW(), NOW()),
('Executors', 'Jim Collins', 'Business', 'English', 'Intermediate', ARRAY['business', 'strategy', 'execution'], 240, NOW(), NOW()),
('The Market Place Review', 'Not Available', 'Business', 'English', 'Advanced', ARRAY['market', 'analysis', 'review'], 200, NOW(), NOW()),
('Playbook to Win', 'A.G. Lafley & Roger L. Martin', 'Strategy', 'English', 'Advanced', ARRAY['strategy', 'business', 'winning'], 240, NOW(), NOW()),
('The Balanced Scorecard', 'Robert S. Kaplan & David P. Norton', 'Management', 'English', 'Advanced', ARRAY['management', 'metrics', 'strategy'], 280, NOW(), NOW()),
('The Innovator''s Dilemmas', 'Clayton M. Christensen', 'Innovation', 'English', 'Advanced', ARRAY['innovation', 'disruption', 'strategy'], 300, NOW(), NOW()),
('Lean UX', 'Jeff Gothelf & Josh Seiden', 'Design & UX', 'English', 'Intermediate', ARRAY['ux', 'design', 'lean'], 160, NOW(), NOW()),
('The Design of Everyday Things', 'Don Norman', 'Design', 'English', 'Beginner', ARRAY['design', 'user-experience', 'psychology'], 240, NOW(), NOW()),
('Thinking, Fast and Slow', 'Daniel Kahneman', 'Psychology', 'English', 'Advanced', ARRAY['psychology', 'decision-making', 'thinking'], 300, NOW(), NOW()),
('Behavioral Economics', 'Dan Ariely', 'Economics', 'English', 'Intermediate', ARRAY['economics', 'behavior', 'psychology'], 240, NOW(), NOW()),
('Influence: The Psychology of Persuasion', 'Robert Cialdini', 'Psychology', 'English', 'Intermediate', ARRAY['persuasion', 'influence', 'psychology'], 240, NOW(), NOW()),
('The Tipping Point', 'Malcolm Gladwell', 'Social Science', 'English', 'Beginner', ARRAY['social-dynamics', 'trends', 'change'], 220, NOW(), NOW()),
('Predictably Irrational', 'Dan Ariely', 'Psychology', 'English', 'Intermediate', ARRAY['psychology', 'behavior', 'decision-making'], 240, NOW(), NOW()),
('Blink', 'Malcolm Gladwell', 'Psychology', 'English', 'Beginner', ARRAY['intuition', 'decision-making', 'insight'], 200, NOW(), NOW()),
('Outliers', 'Malcolm Gladwell', 'Psychology', 'English', 'Beginner', ARRAY['success', 'achievement', 'patterns'], 240, NOW(), NOW()),
('Scenarios', 'Peter Schwartz & Peter Leyden', 'Strategy', 'English', 'Advanced', ARRAY['scenarios', 'planning', 'strategy'], 240, NOW(), NOW());

-- Removed ON CONFLICT clause since title column has no UNIQUE constraint
