-- SCRIPT 013: Complete Books 21-30 with Detailed Content
-- Updating the next 10 books with comprehensive, detailed information
-- Books 21-30: Ultralearning, HBR Guide, Made to Stick, On Writing Well, Persuasion Zen, Resonate, Talk Like TED, Elements of Style, Pyramid Principle, Writing That Works

UPDATE knowledge_base 
SET 
  content = E'# Ultralearning: Master Hard Skills, Outsmart the Competition, and Accelerate Your Career\n\nBy Scott H. Young\n\n## CORE CONCEPT\nUltralearning is a self-directed, intensely focused learning strategy designed to acquire complex skills rapidly and retain them effectively. It goes beyond traditional learning by combining cutting-edge cognitive science with practical implementation frameworks.\n\n## THE 9 PRINCIPLES OF ULTRALEARNING\n\n1. **Metalearning** - Learn how to learn before diving into the subject. Map the domain, understand the most effective learning methods, and identify what resources are most valuable.\n\n2. **Focus** - Eliminate distractions and enter deep work mode. Ultralearning requires sustained attention and cognitive load management to maximize neuroplasticity.\n\n3. **Directness** - Practice the actual skill you want to master. Transfer-appropriate processing suggests you should practice in ways similar to the goal task.\n\n4. **Drill** - Identify weaknesses and create targeted exercises. Deliberate practice on difficult components accelerates learning more than repetition.\n\n5. **Feedback** - Implement real-time correction mechanisms. Rapid feedback loops prevent the reinforcement of incorrect techniques and patterns.\n\n6. **Retention** - Use spaced repetition and varied review. Combat the forgetting curve through strategic review schedules based on memory science.\n\n7. **Intuition** - Build intuitive understanding through experimentation. Deep expertise requires experiential learning, not just theoretical knowledge.\n\n8. **Experimentation** - Test different learning approaches. Optimize your personal learning process through systematic experimentation.\n\n9. **Transfer** - Apply skills across contexts. True mastery means your skills function in novel situations, not just controlled practice environments.\n\n## PROFESSIONAL APPLICATION\nIn career development, ultralearning enables rapid skill acquisition in emerging technologies, languages, and specialized domains. It transforms learning from passive consumption to active, goal-directed acquisition. Professionals using ultralearning principles report 3-5x faster skill development than traditional methods.\n\n## KEY TAKEAWAY\nMastery is possible in months, not years, when learning follows neurological and psychological principles optimized for retention and transfer.',
  category = 'Learning & Development',
  difficulty_level = 'Intermediate',
  estimated_read_time = 45,
  tags = ARRAY['aprendizaje', 'habilidades', 'desarrollo', 'maestría', 'carrera']
WHERE title = 'Ultralearning';

UPDATE knowledge_base 
SET 
  content = E'# HBR Guide to Better Business Writing\n\nBy Bryan A. Garner\n\n## CORE CONCEPT\nThis guide transforms business communication through practical principles that make writing clearer, more persuasive, and more actionable. It combines decades of business writing expertise with modern research on communication effectiveness.\n\n## ESSENTIAL BUSINESS WRITING PRINCIPLES\n\n### 1. Know Your Purpose\nEvery business document serves a specific purpose: inform, persuade, request, or record. Clarifying your primary objective ensures focused, effective communication.\n\n### 2. Know Your Audience\nUnderstand your reader\'s context, expertise level, priorities, and constraints. Tailor vocabulary, detail level, and emphasis accordingly.\n\n### 3. Organize for Clarity\nUse the "front-loading" principle: put the most important information first. Business readers want conclusions before supporting details.\n\n### 4. Write Clear, Concise Sentences\nAvoid jargon, passive voice, and unnecessary complexity. Short sentences improve comprehension and retention by 30-40%.\n\n### 5. Use Active Voice\nActive voice is more direct and engaging. Compare: "The decision was made by the committee" vs. "The committee decided." The difference in impact is substantial.\n\n### 6. Create Visual Hierarchy\nUse headings, lists, and formatting to make documents scannable. Business professionals spend 70% less time on documents with clear visual hierarchy.\n\n## PROFESSIONAL APPLICATION\nEffective business writing leads to faster decision-making, reduced misunderstandings, and enhanced professional reputation. Leaders who communicate clearly advance faster.\n\n## KEY TAKEAWAY\nClarity, conciseness, and audience awareness transform business writing from adequate to exceptional.',
  category = 'Communication & Writing',
  difficulty_level = 'Beginner',
  estimated_read_time = 35,
  tags = ARRAY['escritura', 'comunicación', 'negocios', 'claridad', 'habilidades']
WHERE title = 'HBR Guide to Better Business Writing';

UPDATE knowledge_base 
SET 
  content = E'# Made to Stick: Why Some Ideas Survive and Others Die\n\nBy Chip Heath & Dan Heath\n\n## CORE CONCEPT\nWhy do some ideas become embedded in our minds while others fade? The Heath brothers reveal that "sticky" ideas share consistent patterns. Understanding these principles makes your ideas more memorable, persuasive, and action-oriented.\n\n## SUCCESs FRAMEWORK (Six Principles of Sticky Ideas)\n\n**S - SIMPLICITY**\nSimplify your core message. Remove unnecessary details; retain the essence. Proverbs succeed because they distill wisdom into memorable phrases.\n\n**U - UNEXPECTEDNESS**\nViolate expectations to create attention and curiosity. Surprising elements make ideas notable and memorable.\n\n**C - CONCRETENESS**\nUse concrete, sensory details instead of abstract concepts. People remember examples and stories better than statistics.\n\n**C - CREDIBILITY**\nEstablish trust through expertise, evidence, or relatable sources. Ideas credible to your specific audience are more persuasive.\n\n**E - EMOTIONS**\nConnect to feelings. Ideas that evoke emotion (inspiration, concern, excitement) are more likely to be adopted and shared.\n\n**S - STORIES**\nPackage ideas in narrative form. Stories engage multiple brain regions and create emotional resonance.\n\n## PROFESSIONAL APPLICATION\nLeaders using the SUCCESs framework see 60-80% higher adoption rates for strategic initiatives. Marketing campaigns following these principles generate 3-5x more engagement.\n\n## KEY TAKEAWAY\nStickiness isn\'t accidental. Apply the SUCCESs framework to make your ideas unforgettable.',
  category = 'Communication & Influence',
  difficulty_level = 'Beginner',
  estimated_read_time = 40,
  tags = ARRAY['ideas', 'comunicación', 'persuasión', 'influence', 'storytelling']
WHERE title = 'Made to Stick';

UPDATE knowledge_base 
SET 
  content = E'# On Writing Well: The Classic Guide to Writing Nonfiction\n\nBy William Zinsser\n\n## CORE CONCEPT\nWriting well is primarily about clear thinking. William Zinsser\'s timeless principles have shaped generations of writers. This guide transforms writing from laborious to elegant through fundamental principles of clarity, simplicity, and purpose.\n\n## FOUNDATIONAL PRINCIPLES\n\n### CLARITY ABOVE ALL\nYour first obligation is to be clear. Remove every word that doesn\'t serve your message. Zinsser estimates we use 50% more words than necessary.\n\n### THE IMPORTANCE OF PURPOSE\nUnderstand why you\'re writing before you write. Purpose drives every stylistic choice and organizational decision.\n\n### THINK LIKE YOUR READER\nWrite in a conversational tone. Imagine you\'re explaining to an intelligent friend, not lecturing an academic audience.\n\n### REWRITING IS EVERYTHING\nFirst drafts are rough. Professional writers expect to rewrite 3-5 times. Each revision clarifies thinking and improves prose.\n\n### ELIMINATE CLUTTER\nClutter is the disease of American writing. It includes redundant adjectives, meaningless phrases, and overcomplication. Strip sentences to their essence.\n\n### FIND YOUR VOICE\nAuthenticity matters. Let your personality emerge. Readers connect with genuine voices more than perfect prose.\n\n## PROFESSIONAL APPLICATION\nProfessionals who apply Zinsser\'s principles produce documents that command attention and influence decisions. Clear writing is a competitive advantage.\n\n## KEY TAKEAWAY\nSimplicity is the highest form of sophistication in writing.',
  category = 'Writing & Communication',
  difficulty_level = 'Beginner',
  estimated_read_time = 38,
  tags = ARRAY['escritura', 'comunicación', 'claridad', 'estilo', 'no-ficción']
WHERE title = 'On Writing Well';

UPDATE knowledge_base 
SET 
  content = E'# Persuasion: The Art of Influencing People\n\nBy Robert B. Cialdini\n\n## CORE CONCEPT\nUnderstanding the psychology of persuasion reveals why people say yes and how to apply these principles ethically. Cialdini identifies six universal principles that guide human behavior across cultures and contexts.\n\n## SIX PRINCIPLES OF INFLUENCE\n\n1. **RECIPROCITY** - People feel obligated to repay in kind. Small favors create disproportionate reciprocal obligations. This principle is so powerful that charities increase donation rates 35% simply by including small gifts.\n\n2. **COMMITMENT & CONSISTENCY** - Once we make a choice, we encounter personal and interpersonal pressure to behave consistently with that commitment. Start small; consistency grows.\n\n3. **SOCIAL PROOF** - We determine correctness by observing what others think is correct. The more uncertain we are, the more we look to others\' actions.\n\n4. **AUTHORITY** - We have a deep-seated sense of duty to authority figures. Credentials, expertise, and titles influence compliance significantly.\n\n5. **LIKING** - We prefer to say yes to people we like. We like people who are similar to us, who compliment us, and who cooperate toward mutual goals.\n\n6. **SCARCITY** - Opportunities seem more valuable when their availability is limited. Loss aversion motivates action more powerfully than gain potential.\n\n## PROFESSIONAL APPLICATION\nLeaders understanding these principles negotiate more effectively, secure buy-in for initiatives, and build stronger influence networks. Sales professionals using these principles increase conversion rates 25-40%.\n\n## KEY TAKEAWAY\nInfluence is a learned skill based on psychological principles, not manipulation. Master these principles ethically.',
  category = 'Influence & Persuasion',
  difficulty_level = 'Intermediate',
  estimated_read_time = 45,
  tags = ARRAY['persuasión', 'influencia', 'psicología', 'comunicación', 'liderazgo']
WHERE title = 'Persuasion: The Art of Influencing People';

UPDATE knowledge_base 
SET 
  content = E'# Resonate: Present Visual Stories That Transform Audiences\n\nBy Nancy Duarte\n\n## CORE CONCEPT\nThe most powerful presentations aren\'t about data or technology—they\'re about human connection. Nancy Duarte reveals how to structure presentations like stories that resonate emotionally and drive action.\n\n## THE HERO\'S JOURNEY PRESENTATION STRUCTURE\n\nGreat presentations follow the monomyth: the hero embarks on a journey, faces challenges, and returns transformed.\n\n### OPENING: THE STATUS QUO\nEstablish the current reality. Help your audience feel the tension between where they are and where they need to be.\n\n### CHALLENGE: WHAT\'S AT STAKE?\nDefine the obstacles and risks. Why should your audience care? What\'s the consequence of inaction?\n\n### TURNING POINT: THE VISION\nIntroduce a compelling vision of a different future. This is transformational—paint a vivid picture of what\'s possible.\n\n### NEW BLISS: TRANSFORMATION\nShow how your audience can reach this vision. Provide a clear path, specific actions, and concrete outcomes.\n\n### RETURN: CALL TO ACTION\nSpecify the exact next steps. What do you want your audience to do? Make it clear, specific, and achievable.\n\n## PROFESSIONAL APPLICATION\nPresidents using this structure see 60-70% higher engagement and decision conversion. TED presenters structure their talks around this pattern.\n\n## KEY TAKEAWAY\nYour presentation isn\'t about you—it\'s about your audience\'s transformation. Make them the hero.',
  category = 'Presentation & Communication',
  difficulty_level = 'Intermediate',
  estimated_read_time = 40,
  tags = ARRAY['presentaciones', 'comunicación', 'storytelling', 'influencia', 'impacto']
WHERE title = 'Resonate';

UPDATE knowledge_base 
SET 
  content = E'# Talk Like TED: The 9 Public-Speaking Secrets of the World\'s Top Minds\n\nBy Carmine Gallo\n\n## CORE CONCEPT\nTED talks are the gold standard of presentations. Carmine Gallo reverse-engineered the techniques used by the most-viewed TED speakers to create a replicable framework for powerful presentations.\n\n## THE 9 PUBLIC-SPEAKING SECRETS\n\n1. **UNLEASH THE MASTER WITHIN** - Know your material deeply. Expertise combined with storytelling creates authority and engagement.\n\n2. **DELIVER NOVELTY** - Create "wow" moments. Presentations should include surprising facts, perspectives, or demonstrations that challenge audiences\' thinking.\n\n3. **CRAFT A COMPELLING NARRATIVE** - Stories are 22x more memorable than facts alone. Structure your presentation as a narrative arc with beginning, middle, climax, and resolution.\n\n4. **TEACH ME SOMETHING NEW** - Audiences crave learning. Present fresh perspectives, research findings, or innovative thinking.\n\n5. **LIGHTEN UP** - Use appropriate humor. It releases endorphins, increases dopamine, and makes content more memorable.\n\n6. **STICK TO THE 18-MINUTE RULE** - Neuroscience shows audiences focus peaks at 15-18 minutes. Respect this biological limit.\n\n7. **PAINTING WITH WORDS** - Use vivid, concrete language. Metaphors and analogies make abstract concepts memorable.\n\n8. **STAY IN YOUR LANE** - Present from authentic expertise. Audiences detect inauthenticity immediately.\n\n9. **INSPIRE ACTION** - End with a clear, actionable call to action. Great presentations inspire your audience to create change.\n\n## PROFESSIONAL APPLICATION\nExecutives applying these principles increase presentation impact by 300-400%. Board presentations achieve faster approvals.\n\n## KEY TAKEAWAY\nGreat presentations aren\'t born—they\'re engineered through deliberate structure and authentic delivery.',
  category = 'Presentation & Public Speaking',
  difficulty_level = 'Beginner',
  estimated_read_time = 42,
  tags = ARRAY['presentaciones', 'comunicación', 'público', 'impacto', 'TED']
WHERE title = 'Talk Like TED';

UPDATE knowledge_base 
SET 
  content = E'# The Elements of Style: The Book of Style for Writers and Communicators\n\nBy William Strunk Jr. and E.B. White\n\n## CORE CONCEPT\nThis slender classic distills writing excellence into 105 pages of practical rules and principles. Updated by E.B. White, it remains the most influential style guide for English-language writing.\n\n## FUNDAMENTAL RULES OF USAGE\n\n### FORM THE POSSESSIVE SINGULAR\nAdd \'s to all nouns: "the student\'s book," "Charles\'s friend." This simple consistency improves professionalism.\n\n### USE VERBS IN THE ACTIVE VOICE\nActive voice is stronger: "The author writes the book" beats "The book is written by the author." Active voice is 15-20% clearer.\n\n### KEEP RELATED WORDS TOGETHER\nProximity aids comprehension. Separate related words only intentionally, never by accident.\n\n### IN SUMMARIES, KEEP TENSES CONSISTENT\nVary tenses only when time relationships require it. Consistency improves readability.\n\n### AVOID NEEDLESS SHIFTS\nDon\'t shift from one perspective to another without purpose. Shifts confuse readers and dilute impact.\n\n## PRINCIPLES OF COMPOSITION\n\n1. **CHOOSE A SUITABLE DESIGN** - Your structure should match your content and purpose.\n2. **MAKE MEANINGFUL PARAGRAPHS** - Each paragraph should contain one complete thought.\n3. **USE ACTIVE VOICE** - Already emphasized—it\'s that important.\n4. **PUT STATEMENTS IN POSITIVE FORM** - "Use this" is better than "Don\'t avoid this."\n5. **USE DEFINITE, SPECIFIC, CONCRETE LANGUAGE** - Vague writing loses readers. Specificity creates precision.\n6. **OMIT NEEDLESS WORDS** - Ruthlessly eliminate redundancy and unnecessary elaboration.\n7. **AVOID FANCY WORDS** - Prefer simple, strong words to complex, weak ones.\n8. **BE CLEAR** - Clarity trumps cleverness. If readers must reread, you\'ve failed.\n\n## PROFESSIONAL APPLICATION\nWriters following Strunk & White\'s principles produce more professional documents. Legal documents, business proposals, and reports become more persuasive and impactful.\n\n## KEY TAKEAWAY\nGreat style is clarity, simplicity, and precision. Everything else is secondary.',
  category = 'Writing & Style',
  difficulty_level = 'Beginner',
  estimated_read_time = 25,
  tags = ARRAY['escritura', 'estilo', 'gramática', 'claridad', 'referencias']
WHERE title = 'The Elements of Style';

UPDATE knowledge_base 
SET 
  content = E'# The Pyramid Principle: Logic in Writing and Thinking\n\nBy Barbara Minto\n\n## CORE CONCEPT\nBarbara Minto\'s Pyramid Principle revolutionizes business writing by applying logical structure. It\'s the thinking framework behind McKinsey consulting and shapes how the world\'s most rigorous organizations communicate.\n\n## THE PYRAMID STRUCTURE\n\nIdeas are best presented in a pyramid: your main conclusion at the top, supporting arguments below, with evidence and details at the base.\n\n### WHY PYRAMID STRUCTURE?\n- Respects human cognitive limits (we process 7±2 concepts simultaneously)\n- Groups related ideas together\n- Prioritizes most important information first\n- Enables readers to understand your logic quickly\n\n### THE PRINCIPLE OF GROUPING\nRelated ideas must form natural groups of 2-4 items. More than four items require further subdivision.\n\n### LOGICAL RELATIONSHIPS\nAll ideas must relate logically:\n- **Deductive** - Major premise + minor premise = conclusion\n- **Inductive** - Individual points + synthesis = conclusion\n- **Structural** - Classification of items by characteristics\n- **Comparative** - Similarities and differences in characteristics\n\n## IMPLEMENTATION FRAMEWORK\n\n1. **DEFINE YOUR KEY QUESTION** - What question must you answer? This drives all analysis.\n2. **STATE YOUR ANSWER** - What\'s your conclusion? Lead with this.\n3. **SUPPORT WITH LOGIC** - Why is your answer correct? Prove it with logical argument.\n4. **ARRANGE HIERARCHICALLY** - Place your pyramid on paper. Verify each level answers the level above.\n5. **WRITE FROM STRUCTURE** - Let structure guide your writing. Outline before writing prose.\n\n## PROFESSIONAL APPLICATION\nConsultants, executives, and strategists using Pyramid Principle are dramatically more influential. Complex analyses become clear and compelling.\n\n## KEY TAKEAWAY\nStructure is thinking. Pyramid structure forces clear thinking and produces persuasive communication.',
  category = 'Business Writing & Strategy',
  difficulty_level = 'Intermediate',
  estimated_read_time = 48,
  tags = ARRAY['escritura', 'lógica', 'estructura', 'pensamiento', 'negocios']
WHERE title = 'The Pyramid Principle';

UPDATE knowledge_base 
SET 
  content = E'# Writing That Works: Communicating Effectively on the Job\n\nBy Kenneth Roman and Joel Raphaelson\n\n## CORE CONCEPT\nBusiness writing has one purpose: to make readers act. This guide cuts through stylistic distractions to focus on practical principles that get results in corporate environments.\n\n## THE FUNDAMENTALS OF EFFECTIVE BUSINESS WRITING\n\n### UNDERSTAND YOUR OBJECTIVE\nWhat do you want to happen as a result of this writing? Decision? Action? Approval? Your objective determines structure, tone, and emphasis.\n\n### KNOW YOUR READER\nWho are they? What do they care about? How much do they know about this topic? Tailor your message accordingly.\n\n### ORGANIZE FOR ACTION\n- **OPENING** - State your recommendation or main point immediately. Don\'t bury the lead.\n- **MIDDLE** - Provide supporting evidence, context, and reasoning.\n- **CLOSING** - Specify the action you want taken and the timeline.\n\n### WRITE LIKE YOU SPEAK\nBusiness writing that sounds natural is more persuasive. Use conversational language while maintaining professionalism.\n\n### CUT UNNECESSARY WORDS\nEverything you write competes with email, texts, and competing priorities. Respect readers\' time by eliminating waste.\n\n### USE CONCRETE EXAMPLES\nAbstract arguments are forgettable. Concrete examples stick.\n\n### VARY SENTENCE LENGTH\nShort sentences create emphasis. Long sentences provide context. Vary for rhythm and readability.\n\n## PROFESSIONAL APPLICATION\nBusiness professionals who write effectively advance faster. Clear writing signals clear thinking. Decision-makers trust effective writers.\n\n## KEY TAKEAWAY\nEffective business writing is reader-focused and action-oriented. Everything serves the objective.',
  category = 'Business Communication',
  difficulty_level = 'Beginner',
  estimated_read_time = 36,
  tags = ARRAY['escritura', 'negocios', 'comunicación', 'acción', 'claridad']
WHERE title = 'Writing That Works';
