-- Update all books in knowledge_base with comprehensive content where content is short
UPDATE knowledge_base 
SET content = CASE 
    WHEN title = 'Designing Your Life' THEN 'Designing Your Life presenta un enfoque revolucionario para crear una carrera y vida profesional satisfactoria. Basado en décadas de investigación en diseño y psicología, el libro propone que tu vida profesional no es un destino fijo sino un proyecto en constante evolución. Los autores enseñan cómo aplicar principios de diseño de pensamiento a tus desafíos profesionales. Este enfoque te permite explorar múltiples opciones de carrera simultáneamente, identificar patrones de éxito en tu vida, y crear un plan de acción flexible. El libro incluye herramientas prácticas como el mapa de vida que visualiza tu situación actual, planes de prueba para explorar nuevas direcciones sin compriso total, y conversaciones clave para entender lo que realmente quieres. Ideal para profesionales en cualquier etapa que busquen reorientar su carrera o explorar nuevas posibilidades. Aplicable a emprendimiento, cambios de carrera, y diseño de estilo de vida.'
    WHEN title = 'Grit' THEN 'Grit explora el factor crucial que diferencia a personas exitosas: la pasión y persistencia a largo plazo en la consecución de objetivos de gran valor. Basado en investigaciones con atletas, académicos, militares y emprendedores, Angela Duckworth demuestra que el grit—la combinación de determinación, resiliencia y dedicación—es más predictor de éxito que el talento o el cociente intelectual. El libro desglosa cómo construir grit en cuatro componentes: interés (encontrar lo que amas), práctica (mejora deliberada), propósito (conectar tu trabajo a algo mayor) y esperanza (creer que puedes superar obstáculos). Con ejemplos inspiradores y herramientas prácticas, Duckworth enseña cómo cultivas el grit en ti mismo y en otros. Esencial para líderes, educadores y profesionales que buscan entender qué impulsa el éxito a largo plazo y cómo desarrollar la resiliencia necesaria.'
    WHEN title = 'Mindset' THEN 'Mindset revela cómo nuestras creencias sobre nuestras propias capacidades definen nuestro potencial de éxito. Carol Dweck distingue entre mentalidad fija (creer que tus habilidades son innatas e inmutables) y mentalidad de crecimiento (creer que tus habilidades pueden desarrollarse con esfuerzo). La investigación demuestra que personas con mentalidad de crecimiento alcanzan mayores logros, son más resilientes ante fracasos y abrazan desafíos. El libro explora cómo la mentalidad afecta todas las áreas: educación, relaciones, deportes, negocios y liderazgo. Dweck proporciona estrategias concretas para cambiar de mentalidad fija a crecimiento, cómo reconocer patrones de mentalidad fija en ti mismo y en otros, y cómo fomentar mentalidad de crecimiento en equipos. Revolucionario para educadores, padres, líderes empresariales y cualquier profesional buscando maximizar potencial personal y de su equipo.'
    WHEN title = 'Atomic Habits' THEN 'Atomic Habits demuestra que pequeños cambios consistentes generan resultados extraordinarios. James Clear propone que en lugar de fijar grandes metas imposibles, debes enfocarse en mejorar 1% cada día a través de hábitos atómicos—cambios pequeños pero poderosos. El libro explica cómo funcionan los hábitos científicamente (señal, rutina, recompensa) y cómo diseñar tu entorno para hacer que los buenos hábitos sean automáticos y los malos sean difíciles. Clear presenta el sistema de 4 leyes del cambio de hábitos: hacerlo obvio, hacerlo atractivo, hacerlo fácil y hacerlo satisfactorio. Con 50+ estrategias prácticas y ejemplos de atletas, empresarios y personajes históricos, el libro es una guía completa para construir y mantener hábitos exitosos. Indispensable para productividad, desarrollo personal, salud, relaciones y cualquier área donde busques mejora continua.'
    ELSE content 
END
WHERE LENGTH(COALESCE(content, '')) < 500;

-- Para los recursos chilenos en tabla biblioteca, también actualizar si tienen descripción corta
UPDATE biblioteca
SET description = CASE
    WHEN description IS NULL OR LENGTH(COALESCE(description, '')) < 200 THEN 
        'Recurso público chileno de referencia para desarrollo profesional y orientación laboral. Este recurso proporciona información actualizada y confiable para apoyar tu crecimiento profesional, toma de decisiones de carrera, y desarrollo laboral basado en datos públicos chilenos. Accede regularmente para mantenerte informado sobre tendencias del mercado, oportunidades de formación y orientación vocacional.'
    ELSE description
END
WHERE (description IS NULL OR LENGTH(COALESCE(description, '')) < 200)
AND source_type = 'recurso_chileno';
