-- Insert sample Chilean job data
INSERT INTO public.jobs (title, company, location, salary_min, salary_max, currency, type, remote, description, requirements, benefits) VALUES
('Desarrollador Full Stack Senior', 'NotCo', 'Santiago, Chile', 2500000, 4000000, 'CLP', 'full-time', true, 'Únete al unicornio chileno que está revolucionando la industria alimentaria con tecnología de vanguardia. Trabajarás en el desarrollo de plataformas que impactan millones de usuarios en Latinoamérica.', ARRAY['React', 'Node.js', 'TypeScript', 'AWS', 'Inglés intermedio'], ARRAY['Seguro de salud complementario', 'Vacaciones flexibles', 'Stock options', 'Trabajo remoto']),

('Tech Lead Frontend', 'Fintual', 'Santiago, Chile', 3500000, 5500000, 'CLP', 'full-time', false, 'Lidera el equipo frontend de la fintech más innovadora de Chile. Ayuda a democratizar las inversiones y construye productos que simplifican las finanzas personales.', ARRAY['React', 'TypeScript', 'Leadership', 'Fintech experience', 'Inglés avanzado'], ARRAY['Seguro de salud premium', 'Bonos por performance', 'Capacitación continua', 'Oficina en Las Condes']),

('Desarrollador Backend Python', 'Cornershop by Uber', 'Santiago, Chile', 2200000, 3800000, 'CLP', 'full-time', true, 'Desarrolla la plataforma de delivery líder en Latinoamérica. Construye sistemas escalables que conectan millones de usuarios con sus productos favoritos.', ARRAY['Python', 'Django', 'PostgreSQL', 'Docker', 'AWS'], ARRAY['Seguro de salud', 'Descuentos en Uber', 'Trabajo híbrido', 'Bonos trimestrales']),

('Data Scientist', 'Banco de Chile', 'Santiago, Chile', 2800000, 4200000, 'CLP', 'full-time', false, 'Impulsa la transformación digital del sector bancario chileno. Utiliza machine learning y analytics para mejorar la experiencia de nuestros clientes.', ARRAY['Python', 'R', 'Machine Learning', 'SQL', 'Tableau'], ARRAY['Seguro de salud familiar', 'Préstamos preferenciales', 'Capacitación internacional', 'Estabilidad laboral']),

('UX/UI Designer', 'Ripley', 'Santiago, Chile', 1800000, 2800000, 'CLP', 'full-time', false, 'Diseña experiencias digitales para el retail más grande de Chile. Crea interfaces que mejoran la vida de millones de chilenos en sus compras online y offline.', ARRAY['Figma', 'Adobe Creative Suite', 'User Research', 'Prototyping', 'Design Systems'], ARRAY['Descuentos en tiendas', 'Seguro de salud', 'Horario flexible', 'Capacitación en diseño']),

('DevOps Engineer', 'Bci', 'Santiago, Chile', 2600000, 4000000, 'CLP', 'full-time', true, 'Moderniza la infraestructura tecnológica del banco más innovador de Chile. Implementa soluciones cloud que soportan millones de transacciones diarias.', ARRAY['AWS', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD'], ARRAY['Seguro de salud premium', 'Bonos por objetivos', 'Trabajo remoto', 'Certificaciones AWS']),

('Product Manager', 'Mercado Libre Chile', 'Santiago, Chile', 3200000, 4800000, 'CLP', 'full-time', false, 'Define la estrategia de productos para el marketplace líder de Latinoamérica en Chile. Impulsa la innovación en e-commerce y fintech.', ARRAY['Product Management', 'Analytics', 'Agile', 'E-commerce', 'Inglés avanzado'], ARRAY['Seguro de salud premium', 'Stock options', 'Capacitación internacional', 'Bonos anuales']),

('Desarrollador Mobile React Native', 'Pedidos Ya', 'Santiago, Chile', 2000000, 3200000, 'CLP', 'full-time', true, 'Desarrolla la app de delivery más usada en Chile. Crea funcionalidades que conectan restaurantes, repartidores y usuarios en tiempo real.', ARRAY['React Native', 'JavaScript', 'Redux', 'Firebase', 'Git'], ARRAY['Seguro de salud', 'Descuentos en pedidos', 'Trabajo remoto', 'Capacitación técnica']),

('Cybersecurity Analyst', 'Falabella', 'Santiago, Chile', 2400000, 3600000, 'CLP', 'full-time', false, 'Protege la infraestructura digital del grupo retail más grande de Sudamérica. Implementa soluciones de seguridad para proteger datos de millones de clientes.', ARRAY['Cybersecurity', 'SIEM', 'Incident Response', 'Risk Assessment', 'Certificaciones de seguridad'], ARRAY['Seguro de salud familiar', 'Descuentos en tiendas', 'Capacitación en seguridad', 'Estabilidad laboral']),

('Machine Learning Engineer', 'Entel', 'Santiago, Chile', 2800000, 4200000, 'CLP', 'full-time', false, 'Desarrolla soluciones de IA para la telco líder en Chile. Implementa modelos de machine learning que optimizan la red y mejoran la experiencia del cliente.', ARRAY['Python', 'TensorFlow', 'PyTorch', 'MLOps', 'Big Data'], ARRAY['Seguro de salud premium', 'Plan de telefonía', 'Capacitación en IA', 'Bonos por innovación']);
