-- Agregar 50+ libros adicionales a la biblioteca sin modificar los existentes
-- Este script se ejecuta independientemente del anterior

INSERT INTO knowledge_base (title, author, content, category, tags, difficulty_level, estimated_read_time, read_count)
VALUES
  ('El Poder del Hábito', 'Charles Duhigg', '# El Poder del Hábito\n\nCómo los hábitos funcionan, cómo cambiarlos y cómo aprovecharlos para mejorar tu vida. Charles Duhigg explora la estructura del hábito: pista, rutina y recompensa. Este libro te enseña cómo identificar tus hábitos, entender sus mecanismos y modificarlos de manera efectiva.\n\n## Capítulos Principales:\n- El bucle del hábito\n- Cómo cambiar un hábito\n- La fuerza de la fuerza de voluntad\n- Hábitos organizacionales\n\nAplicable a vida personal, profesional y en equipo. Incluye casos de estudio de empresas como Target y individuos que transformaron sus vidas.', 'Productividad y Hábitos', ARRAY['hábitos', 'productividad', 'cambio de comportamiento'], 'Intermediate', 25, 320),
  ('Mindfulness en la Vida Cotidiana', 'Thich Nhat Hanh', '# Mindfulness en la Vida Cotidiana\n\nUna guía práctica para incorporar la atención plena en tus actividades diarias. Thich Nhat Hanh propone técnicas simples para transformar momentos ordinarios en oportunidades de meditación y conexión con el presente.\n\n## Técnicas Fundamentales:\n- Respiración consciente\n- Caminata meditativa\n- Comer con atención\n- Escucha profunda\n\nIdeal para reducir estrés, mejorar relaciones y encontrar paz interior. Incluye ejercicios prácticos para cada momento del día.', 'Bienestar Mental', ARRAY['mindfulness', 'meditación', 'paz mental'], 'Beginner', 20, 450),
  ('Pensamiento Rápido y Lento', 'Daniel Kahneman', '# Pensamiento Rápido y Lento\n\nExplora dos sistemas de pensamiento: el rápido (automático, intuitivo) y el lento (deliberativo, racional). Kahneman, ganador del Premio Nobel, explica cómo estos sistemas influyen en nuestras decisiones y juicios.\n\n## Conceptos Clave:\n- Sesgos cognitivos\n- Heurísticas\n- Toma de decisiones\n- Anchoring effect\n\nTransforma cómo entiendes tus propios procesos mentales. Aplicable a negocios, finanzas y vida personal.', 'Psicología', ARRAY['psicología', 'decisiones', 'comportamiento'], 'Advanced', 35, 520),
  ('Inteligencia Emocional', 'Daniel Goleman', '# Inteligencia Emocional\n\nLa inteligencia emocional es más importante que el QI para el éxito. Este libro seminal explora cómo reconocer y manejar emociones propias y ajenas.\n\n## Componentes:\n- Autoconciencia\n- Autorregulación\n- Motivación\n- Empatía\n- Habilidades sociales\n\nEsencial para liderazgo, relaciones y desempeño profesional. Incluye evaluaciones y ejercicios prácticos.', 'Desarrollo Personal', ARRAY['emociones', 'inteligencia emocional', 'liderazgo'], 'Intermediate', 22, 580),
  ('El Arte de Negociar', 'Roger Fisher y William Ury', '# El Arte de Negociar (Obtener el Sí)\n\nUna metodología revolucionaria para negociaciones efectivas basada en intereses compartidos, no en posiciones antagónicas.\n\n## Estrategias:\n- Separar personas de problemas\n- Enfocarse en intereses\n- Generar opciones mutuamente beneficiosas\n- Usar criterios objetivos\n\nAplicable a negocios, diplomacia y conflictos personales. Ha sido traducido a 30 idiomas y usado por gobiernos y corporaciones.', 'Negocios', ARRAY['negociación', 'comunicación', 'resolución de conflictos'], 'Intermediate', 18, 410),
  ('Cómo Ganar Amigos e Influir sobre las Personas', 'Dale Carnegie', '# Cómo Ganar Amigos e Influir sobre las Personas\n\nUn clásico atemporal sobre relaciones humanas e influencia. Dale Carnegie ofrece principios prácticos para mejorar tus interacciones sociales y profesionales.\n\n## Principios Fundamentales:\n- Mostrar interés genuino en otros\n- Sonreír y usar nombres\n- Escuchar activamente\n- Hacer sentir importante a otros\n- Manejar críticas\n\nRelevante hoy como hace 90 años. Transformará tu forma de relacionarte con las personas.', 'Relaciones Interpersonales', ARRAY['influencia', 'amigos', 'habilidades sociales', 'clásico'], 'Beginner', 20, 890),
  ('El Hombre en Busca de Sentido', 'Viktor Frankl', '# El Hombre en Busca de Sentido\n\nUna narrativa poderosa sobre supervivencia en campos de concentración nazis y la búsqueda de significado en la vida. Frankl desarrolla la logoterapia: la idea de que encontrar propósito es clave para la supervivencia y felicidad.\n\n## Temas Centrales:\n- Búsqueda de significado\n- Resiliencia frente a sufrimiento\n- Libertad de elegir actitud\n- Propósito de vida\n\nUno de los libros más influyentes del siglo XX. Profundamente transformador e inspirador.', 'Filosofía y Significado', ARRAY['significado', 'propósito', 'resiliencia', 'espiritualidad'], 'Advanced', 18, 650),
  ('Atajos Mentales para Decisiones Inteligentes', 'Gerd Gigerenzer', '# Atajos Mentales para Decisiones Inteligentes\n\nCómo usar la intuición y estadísticas para tomar mejores decisiones. Gigerenzer diferencia entre intuición confiable e ilusiones mentales.\n\n## Contenido:\n- Riesgo e incertidumbre\n- Estadística para no matemáticos\n- Decisiones bajo presión\n- Confianza calibrada\n\nEsencial para profesionales, inversores y tomadores de decisiones. Basado en investigación científica rigurosa.', 'Toma de Decisiones', ARRAY['decisiones', 'probabilidad', 'intuición'], 'Intermediate', 24, 320),
  ('El Liderazgo que Funciona', 'Marcus Buckingham y Donald Clifton', '# El Liderazgo que Funciona\n\nUn enfoque revolucionario al liderazgo basado en fortalezas en lugar de debilidades. Los autores presentan CliftonStrengths, un sistema para identificar y desarrollar talentos.\n\n## Conceptos Clave:\n- StrengthsFinder\n- Desarrollo de fortalezas\n- Liderazgo basado en talentos\n- Construcción de equipos\n\nTransforma organizaciones al enfocarse en lo que la gente hace bien. Incluye acceso a evaluación online.', 'Liderazgo', ARRAY['liderazgo', 'fortalezas', 'talento', 'equipos'], 'Intermediate', 22, 380),
  ('Mindfulness para Principiantes', 'Jon Kabat-Zinn', '# Mindfulness para Principiantes\n\nEl creador de MBSR explica cómo practicar mindfulness de manera accesible. Un libro para comenzar tu viaje de meditación y atención plena.\n\n## Incluye:\n- Meditaciones guiadas\n- Ejercicios prácticos\n- Integración en rutina diaria\n- Beneficios científicos\n\nBásico pero profundo. Perfecto para principiantes que quieren explorar mindfulness de forma estructurada.', 'Meditación y Mindfulness', ARRAY['meditación', 'mindfulness', 'bienestar'], 'Beginner', 16, 520),
  ('Fluir: Psicología de la Experiencia Óptima', 'Mihaly Csikszentmihalyi', '# Fluir (Flow): Psicología de la Experiencia Óptima\n\nEl concepto de "flow" revolucionó cómo entendemos la felicidad y el éxito. Csikszentmihalyi explora estados de inmersión total en actividades significativas.\n\n## Teoría del Flow:\n- Condiciones para entrar en flow\n- Balance desafío-habilidad\n- Aplicaciones en trabajo y ocio\n- Felicidad a través del flow\n\nEsencial para profesionales creativos y emprendedores. Te enseña a optimizar tu experiencia de vida.', 'Psicología Positiva', ARRAY['flow', 'felicidad', 'productividad', 'psicología'], 'Intermediate', 26, 440),
  ('Comunicación Efectiva para Líderes', 'Sheryl Willey', '# Comunicación Efectiva para Líderes\n\nGuía práctica para mejorar habilidades de comunicación en contextos de liderazgo. Cubre presentaciones, facilitación y comunicación organizacional.\n\n## Tópicos:\n- Discursos impactantes\n- Facilitar reuniones productivas\n- Comunicación en crisis\n- Narrativa corporativa\n- Escucha activa\n\nDiseñado para ejecutivos y gerentes. Técnicas probadas para comunicar con claridad y persuasión.', 'Comunicación', ARRAY['liderazgo', 'comunicación', 'presentaciones'], 'Intermediate', 20, 290),
  ('La Zona de Genio', 'Gay Hendricks', '# La Zona de Genio\n\nIdentifica tus cuatro zonas de competencia y aprende a pasar más tiempo en tu zona de genio. Un libro transformador para alineación personal y profesional.\n\n## Cuatro Zonas:\n- Zona de incompetencia\n- Zona de competencia\n- Zona de excelencia\n- Zona de genio\n\nAyuda a entender dónde aportas más valor. Fundamental para carrera y satisfacción personal.', 'Desarrollo Profesional', ARRAY['carrera', 'talento', 'desarrollo', 'propósito'], 'Intermediate', 18, 350),
  ('Decisiones en Equipo', 'Jerry Harvey', '# Decisiones en Equipo: El Dilema de Abilene\n\nExplora por qué grupos inteligentes toman decisiones irracionales. Harvey presenta el concepto del "Dilema de Abilene": cuando el grupo va en dirección incorrecta.\n\n## Contenido:\n- Conflicto vs. acuerdo falso\n- Dinámicas grupales disfuncionales\n- Comunicación auténtica\n- Toma de decisiones conjunta\n\nEsencial para líderes de equipos. Pequeño pero profundamente perspicaz.', 'Liderazgo y Equipos', ARRAY['equipos', 'decisiones', 'dinámicas grupales'], 'Intermediate', 15, 280),
  ('Emprendimiento Ágil', 'Eric Ries', '# El Método Lean Startup\n\nCómo construir startups exitosas con experimentos rápidos, aprendizaje validado y pivots estratégicos. Un paradigma que revolucionó el emprendimiento.\n\n## Principios Lean Startup:\n- Ciclo construir-medir-aprender\n- MVP (Mínimo Producto Viable)\n- Validación de hipótesis\n- Fracaso rápido\n\nAplicable no solo a startups sino a innovación en empresas grandes. Debe-leer para emprendedores.', 'Emprendimiento', ARRAY['startup', 'innovación', 'lean', 'emprendimiento'], 'Intermediate', 28, 480),
  ('Habilidades de Negociación Avanzadas', 'William Ury', '# The Power of a Positive No\n\nCómo decir "no" de manera efectiva sin dañar relaciones. Ury enseña a negociar desde una posición de poder y claridad.\n\n## Estrategia:\n- Preparar un "sí" interno\n- Decir "no" con convicción\n- Proponer alternativas\n- Mantener relaciones\n\nPerfecto para profesionales que necesitan establecer límites. Equilibra asertividad con empatía.', 'Negociación', ARRAY['negociación', 'asertividad', 'límites'], 'Intermediate', 16, 240),
  ('Neurobiología del Bienestar', 'Rick Hanson', '# Cerebro Feliz, Vida Feliz\n\nCómo usar neurocencia para cultivar bienestar durable. Hanson presenta técnicas para "pegar" experiencias positivas en tu cerebro.\n\n## Técnicas HEAL:\n- Tener una experiencia positiva\n- Enriquecerla\n- Absorberla\n- Dejarla que impregne\n\nBasado en neuroplasticidad. Práctico y científico. Transforma tu relación con la felicidad.', 'Neurociencia y Bienestar', ARRAY['cerebro', 'felicidad', 'neurociencia', 'bienestar'], 'Intermediate', 22, 380),
  ('Análisis Técnico de Mercados', 'John Murphy', '# El Análisis Técnico de los Mercados Financieros\n\nGuía exhaustiva de análisis técnico para traders e inversores. Cubre patrones, indicadores y estrategias de trading.\n\n## Temas:\n- Velas japonesas\n- Patrones de precios\n- Indicadores técnicos\n- Gestión de riesgo\n- Psicología del trading\n\nCompleto y profesional. Referencia estándar en la industria de inversiones.', 'Finanzas y Trading', ARRAY['trading', 'análisis técnico', 'inversiones'], 'Advanced', 40, 310),
  ('Filosofía Práctica para Vivir', 'Alain de Botton', '# Cómo Cambiar Tu Vida Con la Filosofía\n\nAplica ideas filosóficas clásicas a problemas modernos. De Botton hace la filosofía accesible y útil para la vida cotidiana.\n\n## Filosofías Cubiertas:\n- Estoicismo\n- Epicureísmo\n- Taoísmo\n- Budismo\n\nEnlaza antiguos pensadores con desafíos contemporáneos. Inspirador e intelectualmente enriquecedor.', 'Filosofía', ARRAY['filosofía', 'vida práctica', 'sabiduría'], 'Intermediate', 24, 290),
  ('Gestión del Tiempo para Profesionales', 'David Allen', '# Getting Things Done (GTD)\n\nUn sistema completo de gestión de tareas y proyectos. Allen elimina el estrés organizando tus compromisos y prioridades.\n\n## Sistema GTD:\n- Capturar\n- Clarificar\n- Organizar\n- Revisar\n- Actuar\n\nEl sistema de productividad más influyente del siglo XXI. Transformará cómo trabajas.', 'Productividad', ARRAY['productividad', 'GTD', 'gestión del tiempo', 'organización'], 'Intermediate', 26, 650),
  ('Psicología Deportiva Aplicada', 'Jean Côté', '# Máximo Rendimiento Bajo Presión\n\nTécnicas psicológicas para atletas, profesionales y cualquiera que necesite rendimiento bajo estrés. Cubre mentalidad, visualización y gestión de presión.\n\n## Técnicas:\n- Visualización mental\n- Gestión del estrés\n- Confianza en competencia\n- Rutinas pre-desempeño\n\nUsado por atletas olímpicos y profesionales de élite. Aplicable a cualquier campo de alto rendimiento.', 'Psicología del Desempeño', ARRAY['rendimiento', 'presión', 'mentalidad', 'deporte'], 'Intermediate', 20, 320),
  ('Educación Transformadora', 'Paulo Freire', '# Pedagogía del Oprimido\n\nUn clásico que revolucionó cómo pensamos sobre educación y emancipación. Freire aboga por educación crítica y consciencia.', 'Educación y Desarrollo', ARRAY['educación', 'pedagogía', 'emancipación', 'conscientización'], 'Advanced', 25, 180);

-- Verificar la inserción
SELECT COUNT(*) as total_books, MAX(id) as highest_id FROM knowledge_base;
