-- Disposable, metadata-only fixture for Wave 5.
create table public.wave5_probe (
  id bigint generated by default as identity primary key,
  label text not null default 'synthetic'
);

grant select on public.wave5_probe to anon, authenticated, service_role;

-- Each view intentionally starts with default owner/security-definer semantics
-- and browser SELECT grants so the migration must harden it.
do $fixture$
declare
  target_view text;
begin
  foreach target_view in array array[
    'active_retention_policies','autopublish_candidates','brain_analytics',
    'canary_active_deployments','canary_deployment_health','cerebro_intelligence_metrics',
    'cip_daily_task_summary','content_license_compliance_summary','cron_active_alerts',
    'cron_health_summary','cron_job_health','dsar_pending_requests','dsar_request_summary',
    'interview_questions_with_metadata','license_compliance_summary','metric_health_status',
    'pending_review_tasks','prompt_performance','threshold_violations','unlicensed_content'
  ]
  loop
    execute format('create view public.%I as select id, label from public.wave5_probe', target_view);
    execute format('grant select on table public.%I to anon, authenticated, service_role', target_view);
  end loop;
end
$fixture$;
