-- Disposable function/trigger fixture for Wave 4 privilege verification.
create table public.wave4_trigger_probe (
  id bigint generated by default as identity primary key,
  note text
);

grant insert, select on public.wave4_trigger_probe to supabase_auth_admin;
grant usage, select on sequence public.wave4_trigger_probe_id_seq to supabase_auth_admin;

create function public.complete_a2_mission(uuid, jsonb)
returns jsonb language plpgsql security definer set search_path = public
as $$ begin return jsonb_build_object('ok', true, 'uid', auth.uid()); end $$;

create function public.cleanup_old_notifications()
returns integer language sql security definer as $$ select 0 $$;

create function public.complete_a2_day(integer, jsonb)
returns jsonb language plpgsql security definer set search_path = public
as $$ begin return jsonb_build_object('ok', true, 'uid', auth.uid()); end $$;

create function public.get_recent_achievements(uuid, integer)
returns json language sql security definer as $$ select '[]'::json $$;

create function public.get_recommended_books(uuid)
returns json language sql security definer as $$ select '[]'::json $$;

create function public.mark_all_notifications_as_read()
returns integer language sql security definer as $$ select 0 $$;

create function public.mark_all_notifications_as_read(uuid)
returns integer language sql security definer as $$ select 0 $$;

create function public.mark_notification_as_read(uuid)
returns boolean language sql security definer as $$ select false $$;

create function public.user_has_permission(uuid, text)
returns boolean language sql security definer as $$ select false $$;

create function public.notify_evaluation_completed()
returns trigger language plpgsql security definer
as $$ begin return new; end $$;

create function public.handle_new_auth_user()
returns trigger language plpgsql security definer
as $$ begin return new; end $$;

create function public.handle_new_user()
returns trigger language plpgsql security definer
as $$ begin return new; end $$;

create function public.handle_oauth_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin return new; end $$;

create function public.handle_oauth_user_creation()
returns trigger language plpgsql security definer set search_path = public
as $$ begin return new; end $$;

create function public.initialize_new_user()
returns trigger language plpgsql security definer
as $$ begin return new; end $$;

create function public.initialize_user_data()
returns trigger language plpgsql security definer
as $$ begin return new; end $$;

create trigger wave4_oauth_probe
  after insert on public.wave4_trigger_probe
  for each row execute function public.handle_oauth_user_creation();
