-- Disposable fixture for Wave 3 migration verification only.
-- Mirrors ownership column types observed in DTCFINAL without copying any data.

do $fixture$
declare
  target_table text;
begin
  foreach target_table in array array[
    'cerebro_conversation_memory','cerebro_feedback_learning','cerebro_predictive_insights',
    'cerebro_reasoning_chains','cerebro_user_patterns','user_chilevalora_interactions',
    'user_journey_progress','cv_data'
  ] loop
    execute format('create table public.%I (id bigint generated by default as identity primary key, user_id uuid)', target_table);
  end loop;

  foreach target_table in array array[
    'ab_test_events','ai_conversations','ai_insights','ai_interpretations','brain_analytics_events',
    'cerebro_cross_test_analysis','coach_conversations','spaced_repetition_items','user_ab_assignments',
    'user_achievements','user_bookmarks','user_learning_path_progress','user_reading_progress',
    'user_skill_assessments','book_reviews'
  ] loop
    execute format('create table public.%I (id bigint generated by default as identity primary key, user_email text)', target_table);
  end loop;

  foreach target_table in array array[
    'a3_module_unlock_rules','ab_test_variants','cerebro_market_insights','cerebro_test_combinations',
    'learning_path_steps','learning_paths','web_resources','skill_benchmarks'
  ] loop
    execute format('create table public.%I (id bigint generated by default as identity primary key)', target_table);
  end loop;

  foreach target_table in array array['api_usage_tracking','brain_response_cache','embedding_generation_logs'] loop
    execute format('create table public.%I (id bigint generated by default as identity primary key)', target_table);
  end loop;
end
$fixture$;

-- These two live relations use TEXT user IDs but are written through the
-- server-side service-role AdvancedBrainEngine, so they must remain server-only.
create table public.brain_feedback (
  id bigint generated by default as identity primary key,
  user_id text
);
create table public.successful_patterns (
  id bigint generated by default as identity primary key,
  user_id text
);

-- Minimal columns consumed by get_user_reading_stats(text).
alter table public.user_reading_progress
  add column status text,
  add column reading_time_minutes integer,
  add column reading_progress numeric,
  add column book_id bigint;
create table public.knowledge_base (
  id bigint primary key,
  category text
);

-- Legacy overload exists in DTCFINAL and must be safely revoked by Wave 3.
create function public.get_user_reading_stats(uuid)
returns integer
language sql
as $$ select 0 $$;
