-- Privacy-preserving product analytics for authenticated pilot users.
-- Raw events expire after 90 days. Aggregates may be retained separately later.

create table if not exists public.v1_analytics (
  id bigint generated by default as identity primary key,
  event_type varchar(64) not null,
  stage varchar(10) not null,
  "timestamp" timestamptz not null default now(),
  session_id varchar(128) not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '90 days'),
  constraint v1_analytics_stage_check
    check (stage in ('c1', 'a1', 'a2', 'a3', 'a4', 'cross')),
  constraint v1_analytics_metadata_object_check
    check (jsonb_typeof(metadata) = 'object'),
  constraint v1_analytics_retention_check
    check (expires_at <= created_at + interval '90 days')
);

-- Harden installations where the legacy SQL script created this table first.
alter table public.v1_analytics
  add column if not exists expires_at timestamptz;

update public.v1_analytics
set metadata = '{}'::jsonb
where metadata is null;

update public.v1_analytics
set created_at = coalesce(created_at, "timestamp", now())
where created_at is null;

update public.v1_analytics
set expires_at = created_at + interval '90 days'
where expires_at is null
   or expires_at > created_at + interval '90 days';

-- Legacy anonymous rows cannot satisfy the owner boundary and are intentionally removed.
delete from public.v1_analytics where user_id is null;

alter table public.v1_analytics
  alter column metadata set default '{}'::jsonb,
  alter column metadata set not null,
  alter column created_at set default now(),
  alter column created_at set not null,
  alter column expires_at set default (now() + interval '90 days'),
  alter column expires_at set not null,
  alter column user_id set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.v1_analytics'::regclass
      and conname = 'v1_analytics_stage_check'
  ) then
    alter table public.v1_analytics add constraint v1_analytics_stage_check
      check (stage in ('c1', 'a1', 'a2', 'a3', 'a4', 'cross'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.v1_analytics'::regclass
      and conname = 'v1_analytics_metadata_object_check'
  ) then
    alter table public.v1_analytics add constraint v1_analytics_metadata_object_check
      check (jsonb_typeof(metadata) = 'object');
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.v1_analytics'::regclass
      and conname = 'v1_analytics_retention_check'
  ) then
    alter table public.v1_analytics add constraint v1_analytics_retention_check
      check (expires_at <= created_at + interval '90 days');
  end if;
end $$;

create index if not exists idx_v1_analytics_user_created
  on public.v1_analytics (user_id, created_at desc);
create index if not exists idx_v1_analytics_event_created
  on public.v1_analytics (event_type, created_at desc);
create index if not exists idx_v1_analytics_expiry
  on public.v1_analytics (expires_at);

alter table public.v1_analytics enable row level security;
alter table public.v1_analytics force row level security;

drop policy if exists "Users can view own analytics" on public.v1_analytics;
drop policy if exists "Users insert own analytics" on public.v1_analytics;
drop policy if exists "Admin full access" on public.v1_analytics;

create policy "Users can view own analytics"
  on public.v1_analytics
  for select
  to authenticated
  using ((select auth.uid()) = user_id and expires_at > now());

create policy "Users insert own analytics"
  on public.v1_analytics
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

revoke all on table public.v1_analytics from anon;
grant select, insert on table public.v1_analytics to authenticated;
grant usage, select on sequence public.v1_analytics_id_seq to authenticated;

comment on table public.v1_analytics is
  'Allowlisted, owner-scoped product events. Raw rows have a maximum retention of 90 days.';
comment on column public.v1_analytics.metadata is
  'Non-PII allowlisted dimensions only; enforced by the authenticated API boundary.';
comment on column public.v1_analytics.expires_at is
  'Hard visibility boundary for raw analytics; expired rows must be purged by scheduled maintenance.';
